In [42]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [ ]:
# 20 Mannschaften * 19 = 380 Spiele pro Saison
# 2&3 Liga sogar 24!

In [842]:
# Read data from the CSV into a dataframe

# Python pandas will read a csv file using utf-8 encoding defautly. 
# If the character encoding of this csv file is not utf-8, UnicodeDecodeError may occur.

loc = "/home/max/Dokumente/Projekte/Football_Game_Prediction/Data_Gathering/Buli1_2_in_Game/"
raw_data_01 = pd.read_csv(loc + '2004_2005_01.csv', sep=',', encoding='gbk')
# raw_data_02 = pd.read_csv(loc + '2004_2005_02.csv', sep=',', encoding='gbk')

In [843]:
raw_data_01.head(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,B365AH,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,D1,06/08/04,Werder Bremen,Schalke 04,1,0,H,0,0,D,...,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,D1,07/08/04,Dortmund,Wolfsburg,1,2,A,1,1,D,...,-0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1,07/08/04,Freiburg,Hansa Rostock,0,0,D,0,0,D,...,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1,07/08/04,Hamburg,Bayern Munich,0,2,A,0,1,A,...,0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1,07/08/04,Hertha,Bochum,2,2,D,2,0,H,...,-0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,D1,07/08/04,Kaiserslautern,Nurnberg,1,3,A,0,1,A,...,-0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,D1,07/08/04,Leverkusen,Hannover,2,1,H,0,1,A,...,-1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,D1,08/08/04,Bielefeld,M'gladbach,0,0,D,0,0,D,...,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,D1,08/08/04,Stuttgart,Mainz,4,2,H,2,0,H,...,-1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,D1,14/08/04,Bayern Munich,Hertha,1,1,D,0,1,A,...,-1.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [844]:
raw_data_01.tail(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,B365AH,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
296,D1,14/05/05,Wolfsburg,Leverkusen,2,2,D,2,0,H,...,0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,D1,21/05/05,Bielefeld,Wolfsburg,1,2,A,1,1,D,...,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,D1,21/05/05,Dortmund,Hansa Rostock,2,1,H,0,1,A,...,-1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,D1,21/05/05,Freiburg,Schalke 04,2,3,A,1,1,D,...,1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
300,D1,21/05/05,Hamburg,Bochum,0,1,A,0,1,A,...,-1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
301,D1,21/05/05,Hertha,Hannover,0,0,D,0,0,D,...,-1.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
302,D1,21/05/05,Kaiserslautern,Werder Bremen,1,2,A,1,2,A,...,0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
303,D1,21/05/05,Leverkusen,M'gladbach,5,1,H,1,1,D,...,-1.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
304,D1,21/05/05,Nurnberg,Mainz,1,2,A,1,1,D,...,-0.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,D1,21/05/05,Stuttgart,Bayern Munich,1,3,A,0,2,A,...,-0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [845]:
raw_data_02.head(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
0,D2,2005-08-06,Cottbus,Braunschweig,2,1,H,0,1,A,...,1.87,1.77,2.07,1.90,9,-0.50,1.84,1.80,2.13,2.04
1,D2,2005-08-06,Greuther Furth,Dresden,3,1,H,1,0,H,...,1.83,1.72,2.11,1.96,8,-0.50,1.91,1.87,2.05,1.96
2,D2,2005-08-06,Saarbrucken,Bochum,0,4,A,0,0,D,...,1.85,1.69,2.10,1.97,8,0.25,2.11,2.02,1.89,1.84
3,D2,2005-08-07,Ahlen,Munich 1860,1,2,A,1,0,H,...,1.88,1.75,2.10,1.90,5,0.25,1.87,1.84,2.05,2.01
4,D2,2005-08-07,Freiburg,Burghausen,2,1,H,1,0,H,...,1.70,1.64,2.20,2.01,3,-0.50,1.80,1.75,2.15,2.14
5,D2,2005-08-07,Hansa Rostock,Offenbach,1,2,A,1,0,H,...,1.65,1.58,2.20,2.09,4,-1.00,2.00,1.93,1.97,1.84
6,D2,2005-08-07,Karlsruhe,Siegen,2,0,H,1,0,H,...,1.85,1.76,2.05,1.88,3,-0.75,2.05,2.03,1.87,1.85
7,D2,2005-08-07,Unterhaching,Paderborn,3,0,H,1,0,H,...,1.90,1.76,2.10,1.88,4,-0.50,2.05,1.98,1.94,1.86
8,D2,2005-08-08,Erzgebirge Aue,Aachen,2,1,H,1,0,H,...,1.91,1.77,2.05,1.88,5,0.00,1.83,1.78,2.11,2.01
9,D2,2005-08-12,Aachen,Karlsruhe,2,1,H,0,0,D,...,1.72,1.62,2.30,2.07,9,-0.75,2.01,1.96,1.95,1.90

In [846]:
raw_data_02.tail(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
296,D2,2006-05-07,Siegen,Burghausen,2,1,H,0,0,D,...,1.60,1.55,2.40,2.24,10,0.00,2.05,2.02,1.87,1.82
297,D2,2006-05-14,Ahlen,Offenbach,1,0,H,0,0,D,...,1.60,1.54,2.35,2.22,9,-0.25,2.11,2.03,1.88,1.85
298,D2,2006-05-14,Burghausen,Aachen,1,1,D,1,0,H,...,2.00,1.92,1.95,1.87,9,0.00,2.12,2.06,1.83,1.79
299,D2,2006-05-14,Cottbus,Munich 1860,3,1,H,1,1,D,...,1.65,1.64,2.15,2.04,9,-1.00,1.96,1.94,1.95,1.93
300,D2,2006-05-14,Erzgebirge Aue,Siegen,0,2,A,0,0,D,...,1.98,1.93,1.92,1.87,9,-1.00,2.00,1.92,1.98,1.93
301,D2,2006-05-14,Freiburg,Greuther Furth,1,0,H,1,0,H,...,1.60,1.55,2.45,2.21,10,-0.25,1.95,1.91,2.00,1.97
302,D2,2006-05-14,Hansa Rostock,Dresden,1,3,A,1,1,D,...,1.70,1.63,2.35,2.07,9,0.50,2.12,2.09,1.82,1.79
303,D2,2006-05-14,Karlsruhe,Paderborn,2,3,A,2,1,H,...,1.45,1.40,2.85,2.60,9,-1.50,1.86,1.82,2.14,2.04
304,D2,2006-05-14,Saarbrucken,Braunschweig,2,0,H,1,0,H,...,1.65,1.59,2.25,2.13,9,-0.25,2.08,2.05,1.85,1.84
305,D2,2006-05-14,Unterhaching,Bochum,0,0,D,0,0,D,...,1.90,1.73,2.00,1.92,9,0.00,1.94,1.86,2.06,1.99

In [847]:
raw_data_01.Date

0      06/08/04
1      07/08/04
2      07/08/04
3      07/08/04
4      07/08/04
         ...
301    21/05/05
302    21/05/05
303    21/05/05
304    21/05/05
305    21/05/05
Name: Date, Length: 306, dtype: object

In [848]:
raw_data_02.Date

0      2005-08-06
1      2005-08-06
2      2005-08-06
3      2005-08-07
4      2005-08-07
          ...
301    2006-05-14
302    2006-05-14
303    2006-05-14
304    2006-05-14
305    2006-05-14
Name: Date, Length: 306, dtype: object

In [506]:
# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

# funktion brauche ich nicht: form nur für obigen zwei!
def parse_date_other_2(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%Y-%m-%d').date()

In [849]:
raw_data_01.Date = raw_data_01.Date.apply(parse_date)   
# raw_data_02.Date = raw_data_02.Date.apply(parse_date)

In [850]:
#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR', "HS", "AS", "HST", "AST", "HC", 
                          "AC", "HF", "AF", "HY", "AY", "HR", "AR"]

playing_statistics_01 = raw_data_01[columns_req]          
# playing_statistics_02 = raw_data_02[columns_req]

KeyError: "['AST', 'HST'] not in index"

In [786]:
playing_statistics_02

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
0,2017-07-28,Bochum,St Pauli,0,1,A,17,16,5,7,8,2,12,10,1,1,0,0
1,2017-07-29,Bielefeld,Regensburg,2,1,H,19,14,5,3,7,4,13,12,3,3,1,0
2,2017-07-29,Darmstadt,Greuther Furth,1,0,H,10,10,5,1,2,5,13,21,1,4,0,0
3,2017-07-29,Ingolstadt,Union Berlin,0,1,A,13,13,4,3,3,3,13,17,0,3,0,0
4,2017-07-30,Dresden,Duisburg,1,0,H,18,15,8,3,7,3,10,17,1,4,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2018-05-13,Duisburg,St Pauli,2,0,H,13,11,4,3,4,5,13,15,2,2,0,0
302,2018-05-13,Heidenheim,Greuther Furth,1,1,D,16,8,4,4,7,6,11,14,1,4,0,0
303,2018-05-13,Holstein Kiel,Braunschweig,6,2,H,20,14,8,7,4,5,20,9,0,1,0,0
304,2018-05-13,Ingolstadt,Kaiserslautern,1,3,A,16,8,4,4,4,3,13,11,0,0,0,0
305,2018-05-13,Nurnberg,Fortuna Dusseldorf,2,3,A,13,11,4,6,3,5,14,12,2,2,0,0

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK **

In [787]:
# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [788]:
# Apply to each dataset

playing_statistics_01 = get_gss(playing_statistics_01)
playing_statistics_02 = get_gss(playing_statistics_02)

<ipython-input-787-24a31de75eb3>:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGS'] = HTGS
<ipython-input-787-24a31de75eb3>:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGS'] = ATGS
<ipython-input-787-24a31de75eb3>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGC'] = HTGC
<ipython-input-787-24a31de75eb3>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGC'] = ATGC

In [789]:
playing_statistics_02

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,HF,AF,HY,AY,HR,AR,HTGS,ATGS,HTGC,ATGC
0,2017-07-28,Bochum,St Pauli,0,1,A,17,16,5,7,...,12,10,1,1,0,0,0,0,0,0
1,2017-07-29,Bielefeld,Regensburg,2,1,H,19,14,5,3,...,13,12,3,3,1,0,0,0,0,0
2,2017-07-29,Darmstadt,Greuther Furth,1,0,H,10,10,5,1,...,13,21,1,4,0,0,0,0,0,0
3,2017-07-29,Ingolstadt,Union Berlin,0,1,A,13,13,4,3,...,13,17,0,3,0,0,0,0,0,0
4,2017-07-30,Dresden,Duisburg,1,0,H,18,15,8,3,...,10,17,1,4,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2018-05-13,Duisburg,St Pauli,2,0,H,13,11,4,3,...,13,15,2,2,0,0,50,35,56,46
302,2018-05-13,Heidenheim,Greuther Furth,1,1,D,16,8,4,4,...,11,14,1,4,0,0,49,36,55,47
303,2018-05-13,Holstein Kiel,Braunschweig,6,2,H,20,14,8,7,...,20,9,0,1,0,0,65,35,42,37
304,2018-05-13,Ingolstadt,Kaiserslautern,1,3,A,16,8,4,4,...,13,11,0,0,0,0,46,39,42,54
305,2018-05-13,Nurnberg,Fortuna Dusseldorf,2,3,A,13,11,4,6,...,14,12,2,2,0,0,59,54,36,42

Get Home and Away Shots

In [790]:
# Gets the shots fired agg arranged by teams and matchweek
def get_shots_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSF = playing_stat.iloc[i]['HS']
        # aggregated Home Team shots
        AGASF = playing_stat.iloc[i]['AS']
        # aggregated Away Team shots
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired




# Gets the goals conceded agg arranged by teams and matchweek
def get_shots_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASC = playing_stat.iloc[i]['HS']
        # aggregated home team shots conceded
        AGHSC = playing_stat.iloc[i]['AS']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded



def get_sf(playing_stat):
    SF = get_shots_fired(playing_stat)
    SC = get_shots_conceded(playing_stat)
   
    j = 0
    AGHSF = []
    AGASF = []
    AGHSC = []
    AGASC = []    

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSF.append(SF.loc[ht][j])
        AGASF.append(SF.loc[at][j])
        AGHSC.append(SC.loc[ht][j])
        AGASC.append(SC.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHSF'] = AGHSF
    playing_stat['AGASF'] = AGASF
    playing_stat['AGHSC'] = AGHSC
    playing_stat['AGASC'] = AGASC
    return playing_stat

In [791]:
playing_statistics_01 = get_sf(playing_statistics_01)
playing_statistics_02 = get_sf(playing_statistics_02)

<ipython-input-790-65a700481562>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSF'] = AGHSF
<ipython-input-790-65a700481562>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASF'] = AGASF
<ipython-input-790-65a700481562>:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSC'] = AGHSC
<ipython-input-790-65a700481562>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASC'] = AGASC

In [792]:
playing_statistics_01[['Date', "HomeTeam", "AwayTeam", "HS", "AS",'AGHSF', "AGASF", "AGHSC", "AGASC"]].head(50)

,Date,HomeTeam,AwayTeam,HS,AS,AGHSF,AGASF,AGHSC,AGASC
0,2017-08-18,Bayern Munich,Leverkusen,13,19,0,0,0,0
1,2017-08-19,Hamburg,Augsburg,11,13,0,0,0,0
2,2017-08-19,Hertha,Stuttgart,10,9,0,0,0,0
3,2017-08-19,Hoffenheim,Werder Bremen,14,11,0,0,0,0
4,2017-08-19,Mainz,Hannover,14,6,0,0,0,0
5,2017-08-19,Schalke 04,RB Leipzig,11,12,0,0,0,0
6,2017-08-19,Wolfsburg,Dortmund,9,13,0,0,0,0
7,2017-08-20,Freiburg,Ein Frankfurt,7,15,0,0,0,0
8,2017-08-20,M'gladbach,FC Koln,22,13,0,0,0,0
9,2017-08-25,FC Koln,Hamburg,20,12,13,11,22,13
10,2017-08-26,Augsburg,M'gladbach,24,15,13,22,11,13
11,2017-08-26,Dortmund,Hertha,18,7,13,10,9,9
12,2017-08-26,Ein Frankfurt,Wolfsburg,12,7,15,9,7,13
13,2017-08-26,Leverkusen,Hoffenheim,16,6,19,14,13,11
14,2017-08-26,Stuttgart,Mainz,17,13,9,14,10,6
15,2017-08-26,Werder Bremen,Bayern Munich,4,19,11,13,14,19
16,2017-08-27,Hannover,Schalke 04,11,8,6,11,14,12
17,2017-08-27,RB Leipzig,Freiburg,29,7,12,7,11,15
18,2017-09-08,Hamburg,RB Leipzig,9,19,23,41,33,18
19,2017-09-09,Augsburg,FC Koln,10,13,37,33,26,34
20,2017-09-09,Freiburg,Dortmund,5,27,14,31,44,16
21,2017-09-09,Hoffenheim,Bayern Munich,6,23,20,32,27,23
22,2017-09-09,Mainz,Leverkusen,14,13,27,35,23,19
23,2017-09-09,M'gladbach,Ein Frankfurt,15,12,37,27,37,14
24,2017-09-09,Wolfsburg,Hannover,17,7,16,17,25,22
25,2017-09-10,Hertha,Werder Bremen,8,10,17,15,27,33
26,2017-09-10,Schalke 04,Stuttgart,12,11,19,26,23,23
27,2017-09-15,Hannover,Hamburg,17,12,24,32,39,52
28,2017-09-16,Bayern Munich,Mainz,28,11,55,41,29,36
29,2017-09-16,Ein Frankfurt,Augsburg,23,11,39,47,29,39
30,2017-09-16,RB Leipzig,M'gladbach,10,10,60,52,27,49
31,2017-09-16,Stuttgart,Wolfsburg,8,8,37,33,35,32
32,2017-09-16,Werder Bremen,Schalke 04,16,11,25,31,41,34
33,2017-09-17,Dortmund,FC Koln,22,6,58,46,21,44
34,2017-09-17,Hoffenheim,Hertha,8,9,26,25,50,37
35,2017-09-17,Leverkusen,Freiburg,22,4,48,19,33,71
36,2017-09-19,Augsburg,RB Leipzig,11,14,58,70,62,37
37,2017-09-19,M'gladbach,Stuttgart,9,11,62,45,59,43
38,2017-09-19,Schalke 04,Bayern Munich,11,12,42,83,50,40
39,2017-09-19,Wolfsburg,Werder Bremen,13,11,41,41,40,52
40,2017-09-20,FC Koln,Ein Frankfurt,17,8,52,62,66,40
41,2017-09-20,Freiburg,Hannover,23,14,23,41,93,51
42,2017-09-20,Hamburg,Dortmund,6,17,44,80,69,27
43,2017-09-20,Hertha,Leverkusen,5,12,34,70,45,37
44,2017-09-20,Mainz,Hoffenheim,20,18,52,34,64,59
45,2017-09-22,Bayern Munich,Wolfsburg,19,8,95,54,51,51
46,2017-09-23,Dortmund,M'gladbach,18,8,97,71,33,70
47,2017-09-23,Hoffenheim,Schalke 04,12,17,52,53,79,62
48,2017-09-23,Mainz,Hertha,8,4,72,39,82,57
49,2017-09-23,RB Leipzig,Ein Frankfurt,17,9,84,70,48,57

Team Shots on Taget

In [793]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_shots_fired_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSTF = playing_stat.iloc[i]['HST']
        # aggregated Home Team shots on Taget
        AGASTF = playing_stat.iloc[i]['AST']
        # aggregated Away Team shots on Taget
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired

# Gets the goals conceded agg on target arranged by teams and matchweek
def get_shots_conceded_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASTC = playing_stat.iloc[i]['HST']
        # aggregated home team shots conceded
        AGHSTC = playing_stat.iloc[i]['AST']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded

def get_sf_target(playing_stat):
    SFT = get_shots_fired_target(playing_stat)
    SCT = get_shots_conceded_target(playing_stat)
    
    j = 0
    AGHSTF = []
    AGASTF = []
    AGHSTC = []
    AGASTC = []  

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSTF.append(SFT.loc[ht][j])
        AGASTF.append(SFT.loc[at][j])
        AGHSTC.append(SCT.loc[ht][j])
        AGASTC.append(SCT.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHSTF'] = AGHSTF
    playing_stat['AGASTF'] = AGASTF
    playing_stat['AGHSTC'] = AGHSTC
    playing_stat['AGASTC'] = AGASTC
    
    return playing_stat

In [794]:
playing_statistics_01 = get_sf_target(playing_statistics_01)
playing_statistics_02 = get_sf_target(playing_statistics_02)

<ipython-input-793-1d9d07eec275>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTF'] = AGHSTF
<ipython-input-793-1d9d07eec275>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTF'] = AGASTF
<ipython-input-793-1d9d07eec275>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTC'] = AGHSTC
<ipython-input-793-1d9d07eec275>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTC'] = AGASTC

In [795]:
playing_statistics_02[['Date', "HomeTeam", "AwayTeam", "HST", "AST",'AGHSTF', "AGASTF", "AGHSTC", "AGASTC"]].head(50)

,Date,HomeTeam,AwayTeam,HST,AST,AGHSTF,AGASTF,AGHSTC,AGASTC
0,2017-07-28,Bochum,St Pauli,5,7,0,0,0,0
1,2017-07-29,Bielefeld,Regensburg,5,3,0,0,0,0
2,2017-07-29,Darmstadt,Greuther Furth,5,1,0,0,0,0
3,2017-07-29,Ingolstadt,Union Berlin,4,3,0,0,0,0
4,2017-07-30,Dresden,Duisburg,8,3,0,0,0,0
5,2017-07-30,Holstein Kiel,Sandhausen,3,4,0,0,0,0
6,2017-07-30,Nurnberg,Kaiserslautern,3,3,0,0,0,0
7,2017-07-31,Fortuna Dusseldorf,Braunschweig,4,10,0,0,0,0
8,2017-08-04,Kaiserslautern,Darmstadt,2,5,0,0,0,0
9,2017-08-04,Sandhausen,Ingolstadt,3,4,4,4,3,3
10,2017-08-04,Union Berlin,Holstein Kiel,8,6,3,3,4,4
11,2017-08-05,Braunschweig,Heidenheim,2,3,10,3,4,2
12,2017-08-05,Duisburg,Bochum,5,3,3,5,8,7
13,2017-08-06,Erzgebirge Aue,Fortuna Dusseldorf,4,2,4,4,2,10
14,2017-08-06,Greuther Furth,Bielefeld,7,4,1,5,5,3
15,2017-08-06,Regensburg,Nurnberg,1,4,3,3,5,3
16,2017-08-07,St Pauli,Dresden,5,4,7,8,5,3
17,2017-08-09,Heidenheim,Erzgebirge Aue,2,5,3,4,2,2
18,2017-08-18,Braunschweig,Erzgebirge Aue,6,7,12,9,7,4
19,2017-08-18,Darmstadt,St Pauli,8,6,10,12,3,9
20,2017-08-19,Dresden,Sandhausen,1,6,12,7,8,7
21,2017-08-19,Fortuna Dusseldorf,Kaiserslautern,8,1,6,5,14,8
22,2017-08-19,Heidenheim,Duisburg,7,6,5,8,7,11
23,2017-08-20,Holstein Kiel,Greuther Furth,8,5,9,8,12,9
24,2017-08-20,Ingolstadt,Regensburg,8,11,8,4,6,9
25,2017-08-20,Nurnberg,Union Berlin,6,4,7,11,4,10
26,2017-08-21,Bielefeld,Bochum,6,5,9,8,10,12
27,2017-08-25,Duisburg,Darmstadt,4,6,14,18,18,9
28,2017-08-25,Greuther Furth,Ingolstadt,2,2,13,16,17,17
29,2017-08-26,Erzgebirge Aue,Nurnberg,10,6,16,13,10,8
30,2017-08-26,Regensburg,Holstein Kiel,2,7,15,17,17,17
31,2017-08-26,St Pauli,Heidenheim,4,1,18,12,17,13
32,2017-08-27,Bochum,Dresden,5,5,13,13,18,14
33,2017-08-27,Sandhausen,Fortuna Dusseldorf,3,5,13,14,8,15
34,2017-08-27,Union Berlin,Bielefeld,8,2,15,15,16,15
35,2017-08-28,Kaiserslautern,Braunschweig,4,4,6,18,16,14
36,2017-09-08,Dresden,Greuther Furth,4,6,18,15,19,19
37,2017-09-08,Heidenheim,Regensburg,5,5,13,17,17,24
38,2017-09-09,Bielefeld,Duisburg,3,9,17,18,23,24
39,2017-09-09,Holstein Kiel,Kaiserslautern,5,3,24,10,19,20
40,2017-09-09,Ingolstadt,Erzgebirge Aue,3,4,18,26,19,16
41,2017-09-10,Braunschweig,Sandhausen,6,4,22,16,18,13
42,2017-09-10,Darmstadt,Bochum,5,4,24,18,13,23
43,2017-09-10,Fortuna Dusseldorf,Union Berlin,6,4,19,23,18,18
44,2017-09-11,Nurnberg,St Pauli,3,2,19,22,18,18
45,2017-09-15,Erzgebirge Aue,Holstein Kiel,3,6,30,29,19,22
46,2017-09-15,Union Berlin,Braunschweig,6,4,27,28,24,22
47,2017-09-16,Duisburg,Nurnberg,10,9,27,22,27,20
48,2017-09-16,Sandhausen,Kaiserslautern,5,2,20,13,19,25
49,2017-09-16,St Pauli,Ingolstadt,3,7,24,21,21,23

Team Fouls Committed

In [796]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_fouls(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHF = playing_stat.iloc[i]['HF']
        # aggregated Home Team Fouls
        AGAF = playing_stat.iloc[i]['AF']
        # aggregated Away Team Fouls
        teams[playing_stat.iloc[i].HomeTeam].append(AGHF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Fouls = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    Fouls[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        Fouls[i] = Fouls[i] + Fouls[i-1]
    return Fouls


def get_fouls_agg(playing_stat):
    FA = get_fouls(playing_stat)
   
    j = 0
    AGHF = []
    AGAF = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHF.append(FA.loc[ht][j])
        AGAF.append(FA.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHF'] = AGHF
    playing_stat['AGAF'] = AGAF
    return playing_stat

In [797]:
playing_statistics_01 = get_fouls_agg(playing_statistics_01)
playing_statistics_02 = get_fouls_agg(playing_statistics_02)

<ipython-input-796-b2fa1f1aadea>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHF'] = AGHF
<ipython-input-796-b2fa1f1aadea>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAF'] = AGAF

In [798]:
playing_statistics_02[['Date', "HomeTeam", "AwayTeam", "HF", "AF",'AGHF', "AGAF"]].head(50)

          Date            HomeTeam            AwayTeam  HF  AF  AGHF  AGAF
0   2017-07-28              Bochum            St Pauli  12  10     0     0
1   2017-07-29           Bielefeld          Regensburg  13  12     0     0
2   2017-07-29           Darmstadt      Greuther Furth  13  21     0     0
3   2017-07-29          Ingolstadt        Union Berlin  13  17     0     0
4   2017-07-30             Dresden            Duisburg  10  17     0     0
5   2017-07-30       Holstein Kiel          Sandhausen  18  20     0     0
6   2017-07-30            Nurnberg      Kaiserslautern  11  14     0     0
7   2017-07-31  Fortuna Dusseldorf        Braunschweig  19  17     0     0
8   2017-08-04      Kaiserslautern           Darmstadt  18  11     0     0
9   2017-08-04          Sandhausen          Ingolstadt  17  15    20    13
10  2017-08-04        Union Berlin       Holstein Kiel  16  15    17    18
11  2017-08-05        Braunschweig          Heidenheim  11  19    17    19
12  2017-08-05            Duisburg              Bochum  12  13    17    12
13  2017-08-06      Erzgebirge Aue  Fortuna Dusseldorf  17  18    17    19
14  2017-08-06      Greuther Furth           Bielefeld  17  12    21    13
15  2017-08-06          Regensburg            Nurnberg  12  16    12    11
16  2017-08-07            St Pauli             Dresden  10  15    10    10
17  2017-08-09          Heidenheim      Erzgebirge Aue  20  17    19    17
18  2017-08-18        Braunschweig      Erzgebirge Aue  15  14    28    34
19  2017-08-18           Darmstadt            St Pauli  11  13    24    20
20  2017-08-19             Dresden          Sandhausen  15  24    25    37
21  2017-08-19  Fortuna Dusseldorf      Kaiserslautern  10  18    37    32
22  2017-08-19          Heidenheim            Duisburg  11  16    39    29
23  2017-08-20       Holstein Kiel      Greuther Furth  15  14    33    38
24  2017-08-20          Ingolstadt          Regensburg  16  20    28    24
25  2017-08-20            Nurnberg        Union Berlin  17  19    27    33
26  2017-08-21           Bielefeld              Bochum  19   4    25    25
27  2017-08-25            Duisburg           Darmstadt  17  13    45    35
28  2017-08-25      Greuther Furth          Ingolstadt  12  12    52    44
29  2017-08-26      Erzgebirge Aue            Nurnberg  12  15    48    44
30  2017-08-26          Regensburg       Holstein Kiel  18  22    44    48
31  2017-08-26            St Pauli          Heidenheim  10  14    33    50
32  2017-08-27              Bochum             Dresden  14  15    29    40
33  2017-08-27          Sandhausen  Fortuna Dusseldorf  23  24    61    47
34  2017-08-27        Union Berlin           Bielefeld  12  18    52    44
35  2017-08-28      Kaiserslautern        Braunschweig  20  23    50    43
36  2017-09-08             Dresden      Greuther Furth  12  17    55    64
37  2017-09-08          Heidenheim          Regensburg  13  15    64    62
38  2017-09-09           Bielefeld            Duisburg  10  10    62    62
39  2017-09-09       Holstein Kiel      Kaiserslautern  14  12    70    70
40  2017-09-09          Ingolstadt      Erzgebirge Aue  14  22    56    60
41  2017-09-10        Braunschweig          Sandhausen  17  22    66    84
42  2017-09-10           Darmstadt              Bochum  16  15    48    43
43  2017-09-10  Fortuna Dusseldorf        Union Berlin  16  22    71    64
44  2017-09-11            Nurnberg            St Pauli  10   6    59    43
45  2017-09-15      Erzgebirge Aue       Holstein Kiel  10  24    82    84
46  2017-09-15        Union Berlin        Braunschweig  11   9    86    83
47  2017-09-16            Duisburg            Nurnberg  11  10    72    69
48  2017-09-16          Sandhausen      Kaiserslautern  17  20   106    82
49  2017-09-16            St Pauli          Ingolstadt  12  21    49    70

Team Corners

In [799]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_corners_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHCF = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGACF = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners

def get_corners_conceived(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGACC = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGHCC = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACC)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners


def get_corners_agg(playing_stat):
    CF = get_corners_fired(playing_stat)
    CC = get_corners_conceived(playing_stat)
   
    j = 0
    AGHCF = []
    AGACF = []
    AGHCC = []
    AGACC = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHCF.append(CF.loc[ht][j])
        AGACF.append(CF.loc[at][j])
        AGHCC.append(CC.loc[ht][j])
        AGACC.append(CC.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHCF'] = AGHCF
    playing_stat['AGACF'] = AGACF
    playing_stat['AGHCC'] = AGHCC
    playing_stat['AGACC'] = AGACC
    
    return playing_stat

In [800]:
playing_statistics_01 = get_corners_agg(playing_statistics_01)
playing_statistics_02 = get_corners_agg(playing_statistics_02)

<ipython-input-799-e6a2ea22a806>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCF'] = AGHCF
<ipython-input-799-e6a2ea22a806>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACF'] = AGACF
<ipython-input-799-e6a2ea22a806>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCC'] = AGHCC
<ipython-input-799-e6a2ea22a806>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACC'] = AGACC

In [801]:
playing_statistics_02[['Date', "HomeTeam", "AwayTeam", "HC", "AC",'AGHCF', "AGACF", "AGHCC", "AGACC"]].head(50)

,Date,HomeTeam,AwayTeam,HC,AC,AGHCF,AGACF,AGHCC,AGACC
0,2017-07-28,Bochum,St Pauli,8,2,0,0,0,0
1,2017-07-29,Bielefeld,Regensburg,7,4,0,0,0,0
2,2017-07-29,Darmstadt,Greuther Furth,2,5,0,0,0,0
3,2017-07-29,Ingolstadt,Union Berlin,3,3,0,0,0,0
4,2017-07-30,Dresden,Duisburg,7,3,0,0,0,0
5,2017-07-30,Holstein Kiel,Sandhausen,12,2,0,0,0,0
6,2017-07-30,Nurnberg,Kaiserslautern,5,3,0,0,0,0
7,2017-07-31,Fortuna Dusseldorf,Braunschweig,5,5,0,0,0,0
8,2017-08-04,Kaiserslautern,Darmstadt,3,3,0,0,0,0
9,2017-08-04,Sandhausen,Ingolstadt,3,4,2,3,12,3
10,2017-08-04,Union Berlin,Holstein Kiel,3,0,3,12,3,2
11,2017-08-05,Braunschweig,Heidenheim,2,6,5,6,5,2
12,2017-08-05,Duisburg,Bochum,2,7,3,8,7,2
13,2017-08-06,Erzgebirge Aue,Fortuna Dusseldorf,9,2,9,5,2,5
14,2017-08-06,Greuther Furth,Bielefeld,6,4,5,7,2,4
15,2017-08-06,Regensburg,Nurnberg,4,7,4,5,7,3
16,2017-08-07,St Pauli,Dresden,5,3,2,7,8,3
17,2017-08-09,Heidenheim,Erzgebirge Aue,1,4,6,9,2,2
18,2017-08-18,Braunschweig,Erzgebirge Aue,3,4,7,13,11,3
19,2017-08-18,Darmstadt,St Pauli,6,9,5,7,8,11
20,2017-08-19,Dresden,Sandhausen,4,3,10,5,8,16
21,2017-08-19,Fortuna Dusseldorf,Kaiserslautern,10,4,7,6,14,8
22,2017-08-19,Heidenheim,Duisburg,2,6,7,5,6,14
23,2017-08-20,Holstein Kiel,Greuther Furth,4,3,12,11,5,6
24,2017-08-20,Ingolstadt,Regensburg,6,5,7,8,6,14
25,2017-08-20,Nurnberg,Union Berlin,6,5,12,6,7,3
26,2017-08-21,Bielefeld,Bochum,2,8,11,15,10,4
27,2017-08-25,Duisburg,Darmstadt,4,2,11,11,16,17
28,2017-08-25,Greuther Furth,Ingolstadt,4,6,14,13,10,11
29,2017-08-26,Erzgebirge Aue,Nurnberg,7,4,17,18,6,12
30,2017-08-26,Regensburg,Holstein Kiel,2,5,13,16,20,8
31,2017-08-26,St Pauli,Heidenheim,11,3,16,9,17,12
32,2017-08-27,Bochum,Dresden,3,8,23,14,6,11
33,2017-08-27,Sandhausen,Fortuna Dusseldorf,2,2,8,17,20,18
34,2017-08-27,Union Berlin,Bielefeld,6,4,11,13,9,18
35,2017-08-28,Kaiserslautern,Braunschweig,6,7,10,10,18,15
36,2017-09-08,Dresden,Greuther Furth,4,2,22,18,14,16
37,2017-09-08,Heidenheim,Regensburg,1,8,12,15,23,25
38,2017-09-09,Bielefeld,Duisburg,2,2,17,15,24,18
39,2017-09-09,Holstein Kiel,Kaiserslautern,7,2,21,16,10,25
40,2017-09-09,Ingolstadt,Erzgebirge Aue,15,2,19,24,15,10
41,2017-09-10,Braunschweig,Sandhausen,7,7,17,10,21,22
42,2017-09-10,Darmstadt,Bochum,3,6,13,26,21,14
43,2017-09-10,Fortuna Dusseldorf,Union Berlin,7,7,19,17,20,13
44,2017-09-11,Nurnberg,St Pauli,6,3,22,27,19,20
45,2017-09-15,Erzgebirge Aue,Holstein Kiel,4,4,26,28,25,12
46,2017-09-15,Union Berlin,Braunschweig,5,3,24,24,20,28
47,2017-09-16,Duisburg,Nurnberg,9,5,17,28,20,22
48,2017-09-16,Sandhausen,Kaiserslautern,2,5,17,18,29,32
49,2017-09-16,St Pauli,Ingolstadt,5,4,30,34,26,17

Yellow Cards

In [802]:
# Gets yellow cards agg arranged by teams and matchweek
def get_yellow(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHY = playing_stat.iloc[i]['HY']
        # aggregated Home Team yellow cards
        AGAY = playing_stat.iloc[i]['AY']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHY)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAY)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Yellow = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    Yellow[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        Yellow[i] = Yellow[i] + Yellow[i-1]
    return Yellow


def get_yellow_agg(playing_stat):
    Y = get_yellow(playing_stat)
   
    j = 0
    AGHY = []
    AGAY = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHY.append(Y.loc[ht][j])
        AGAY.append(Y.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHY'] = AGHY
    playing_stat['AGAY'] = AGAY
    return playing_stat

In [803]:
playing_statistics_01 = get_yellow_agg(playing_statistics_01)
playing_statistics_02 = get_yellow_agg(playing_statistics_02)

<ipython-input-802-dc9701e46946>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHY'] = AGHY
<ipython-input-802-dc9701e46946>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAY'] = AGAY

In [804]:
playing_statistics_01[['Date', "HomeTeam", "AwayTeam", "HY", "AY",'AGHY', "AGAY"]].head(50)

          Date       HomeTeam       AwayTeam  HY  AY  AGHY  AGAY
0   2017-08-18  Bayern Munich     Leverkusen   1   2     0     0
1   2017-08-19        Hamburg       Augsburg   4   3     0     0
2   2017-08-19         Hertha      Stuttgart   2   1     0     0
3   2017-08-19     Hoffenheim  Werder Bremen   1   3     0     0
4   2017-08-19          Mainz       Hannover   3   5     0     0
5   2017-08-19     Schalke 04     RB Leipzig   2   2     0     0
6   2017-08-19      Wolfsburg       Dortmund   0   0     0     0
7   2017-08-20       Freiburg  Ein Frankfurt   1   2     0     0
8   2017-08-20     M'gladbach        FC Koln   3   2     0     0
9   2017-08-25        FC Koln        Hamburg   2   2     2     4
10  2017-08-26       Augsburg     M'gladbach   2   2     3     3
11  2017-08-26       Dortmund         Hertha   1   1     0     2
12  2017-08-26  Ein Frankfurt      Wolfsburg   3   1     2     0
13  2017-08-26     Leverkusen     Hoffenheim   2   2     2     1
14  2017-08-26      Stuttgart          Mainz   2   1     1     3
15  2017-08-26  Werder Bremen  Bayern Munich   1   1     3     1
16  2017-08-27       Hannover     Schalke 04   1   2     5     2
17  2017-08-27     RB Leipzig       Freiburg   2   0     2     1
18  2017-09-08        Hamburg     RB Leipzig   1   1     6     4
19  2017-09-09       Augsburg        FC Koln   0   0     5     4
20  2017-09-09       Freiburg       Dortmund   0   0     1     1
21  2017-09-09     Hoffenheim  Bayern Munich   3   1     3     2
22  2017-09-09          Mainz     Leverkusen   2   2     4     4
23  2017-09-09     M'gladbach  Ein Frankfurt   3   2     5     5
24  2017-09-09      Wolfsburg       Hannover   0   1     1     6
25  2017-09-10         Hertha  Werder Bremen   1   0     3     4
26  2017-09-10     Schalke 04      Stuttgart   1   1     4     3
27  2017-09-15       Hannover        Hamburg   1   0     7     7
28  2017-09-16  Bayern Munich          Mainz   2   2     3     6
29  2017-09-16  Ein Frankfurt       Augsburg   2   3     7     5
30  2017-09-16     RB Leipzig     M'gladbach   1   1     5     8
31  2017-09-16      Stuttgart      Wolfsburg   2   3     4     1
32  2017-09-16  Werder Bremen     Schalke 04   2   2     4     5
33  2017-09-17       Dortmund        FC Koln   0   3     1     4
34  2017-09-17     Hoffenheim         Hertha   2   2     6     4
35  2017-09-17     Leverkusen       Freiburg   0   2     6     1
36  2017-09-19       Augsburg     RB Leipzig   2   2     8     6
37  2017-09-19     M'gladbach      Stuttgart   0   1     9     6
38  2017-09-19     Schalke 04  Bayern Munich   1   1     7     5
39  2017-09-19      Wolfsburg  Werder Bremen   1   2     4     6
40  2017-09-20        FC Koln  Ein Frankfurt   2   1     7     9
41  2017-09-20       Freiburg       Hannover   2   4     3     8
42  2017-09-20        Hamburg       Dortmund   3   0     7     1
43  2017-09-20         Hertha     Leverkusen   1   2     6     6
44  2017-09-20          Mainz     Hoffenheim   3   3     8     8
45  2017-09-22  Bayern Munich      Wolfsburg   1   2     6     5
46  2017-09-23       Dortmund     M'gladbach   0   1     1     9
47  2017-09-23     Hoffenheim     Schalke 04   3   2    11     8
48  2017-09-23          Mainz         Hertha   3   3    11     7
49  2017-09-23     RB Leipzig  Ein Frankfurt   1   2     8    10

Red cards

In [805]:
# Gets red cards agg arranged by teams and matchweek
def get_red(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHR = playing_stat.iloc[i]['HR']
        # aggregated Home Team yellow cards
        AGAR = playing_stat.iloc[i]['AR']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHR)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAR)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Red = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    Red[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        Red[i] = Red[i] + Red[i-1]
    return Red


def get_red_agg(playing_stat):
    R = get_red(playing_stat)
   
    j = 0
    AGHR = []
    AGAR = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHR.append(R.loc[ht][j])
        AGAR.append(R.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['AGHR'] = AGHR
    playing_stat['AGAR'] = AGAR
    return playing_stat

In [806]:
playing_statistics_01 = get_red_agg(playing_statistics_01)
playing_statistics_02 = get_red_agg(playing_statistics_02)

<ipython-input-805-b8b299be30fc>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHR'] = AGHR
<ipython-input-805-b8b299be30fc>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAR'] = AGAR

In [807]:
playing_statistics_02[['Date', "HomeTeam", "AwayTeam", "HR", "AR",'AGHR', "AGAR"]].head(50)

          Date            HomeTeam            AwayTeam  HR  AR  AGHR  AGAR
0   2017-07-28              Bochum            St Pauli   0   0     0     0
1   2017-07-29           Bielefeld          Regensburg   1   0     0     0
2   2017-07-29           Darmstadt      Greuther Furth   0   0     0     0
3   2017-07-29          Ingolstadt        Union Berlin   0   0     0     0
4   2017-07-30             Dresden            Duisburg   0   1     0     0
5   2017-07-30       Holstein Kiel          Sandhausen   0   0     0     0
6   2017-07-30            Nurnberg      Kaiserslautern   0   0     0     0
7   2017-07-31  Fortuna Dusseldorf        Braunschweig   0   1     0     0
8   2017-08-04      Kaiserslautern           Darmstadt   0   0     0     0
9   2017-08-04          Sandhausen          Ingolstadt   0   0     0     0
10  2017-08-04        Union Berlin       Holstein Kiel   0   0     0     0
11  2017-08-05        Braunschweig          Heidenheim   0   0     1     0
12  2017-08-05            Duisburg              Bochum   0   0     1     0
13  2017-08-06      Erzgebirge Aue  Fortuna Dusseldorf   0   0     0     0
14  2017-08-06      Greuther Furth           Bielefeld   0   0     0     1
15  2017-08-06          Regensburg            Nurnberg   0   0     0     0
16  2017-08-07            St Pauli             Dresden   0   0     0     0
17  2017-08-09          Heidenheim      Erzgebirge Aue   0   1     0     0
18  2017-08-18        Braunschweig      Erzgebirge Aue   0   0     1     1
19  2017-08-18           Darmstadt            St Pauli   0   0     0     0
20  2017-08-19             Dresden          Sandhausen   0   0     0     0
21  2017-08-19  Fortuna Dusseldorf      Kaiserslautern   0   0     0     0
22  2017-08-19          Heidenheim            Duisburg   0   0     0     1
23  2017-08-20       Holstein Kiel      Greuther Furth   0   0     0     0
24  2017-08-20          Ingolstadt          Regensburg   0   0     0     0
25  2017-08-20            Nurnberg        Union Berlin   0   1     0     0
26  2017-08-21           Bielefeld              Bochum   0   0     1     0
27  2017-08-25            Duisburg           Darmstadt   0   0     1     0
28  2017-08-25      Greuther Furth          Ingolstadt   1   0     0     0
29  2017-08-26      Erzgebirge Aue            Nurnberg   0   0     1     0
30  2017-08-26          Regensburg       Holstein Kiel   0   0     0     0
31  2017-08-26            St Pauli          Heidenheim   0   0     0     0
32  2017-08-27              Bochum             Dresden   0   0     0     0
33  2017-08-27          Sandhausen  Fortuna Dusseldorf   0   0     0     0
34  2017-08-27        Union Berlin           Bielefeld   0   0     1     1
35  2017-08-28      Kaiserslautern        Braunschweig   0   0     0     1
36  2017-09-08             Dresden      Greuther Furth   0   0     0     1
37  2017-09-08          Heidenheim          Regensburg   0   0     0     0
38  2017-09-09           Bielefeld            Duisburg   0   0     1     1
39  2017-09-09       Holstein Kiel      Kaiserslautern   0   0     0     0
40  2017-09-09          Ingolstadt      Erzgebirge Aue   0   0     0     1
41  2017-09-10        Braunschweig          Sandhausen   0   0     1     0
42  2017-09-10           Darmstadt              Bochum   0   0     0     0
43  2017-09-10  Fortuna Dusseldorf        Union Berlin   0   0     0     1
44  2017-09-11            Nurnberg            St Pauli   0   0     0     0
45  2017-09-15      Erzgebirge Aue       Holstein Kiel   0   0     1     0
46  2017-09-15        Union Berlin        Braunschweig   0   0     1     1
47  2017-09-16            Duisburg            Nurnberg   0   0     1     0
48  2017-09-16          Sandhausen      Kaiserslautern   0   0     0     0
49  2017-09-16            St Pauli          Ingolstadt   0   0     0     0

GET RESPECTIVE POINTS:

In [808]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0
    

def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,35):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(18)])
    return matchres_points


def get_matchres(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
            
    return pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []
    j = 0
    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

        if ((i + 1)% 9) == 0:
            j = j + 1
            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat

In [809]:
# Apply to each dataset

playing_statistics_01 = get_agg_points(playing_statistics_01)
playing_statistics_02 = get_agg_points(playing_statistics_02)

<ipython-input-808-ebeaecbf5df5>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTP'] = HTP
<ipython-input-808-ebeaecbf5df5>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATP'] = ATP

In [810]:
playing_statistics_01[['Date', "HomeTeam", "AwayTeam", "FTHG", "FTAG","HTP", "ATP"]].head(50)

          Date       HomeTeam       AwayTeam  FTHG  FTAG  HTP  ATP
0   2017-08-18  Bayern Munich     Leverkusen     3     1    0    0
1   2017-08-19        Hamburg       Augsburg     1     0    0    0
2   2017-08-19         Hertha      Stuttgart     2     0    0    0
3   2017-08-19     Hoffenheim  Werder Bremen     1     0    0    0
4   2017-08-19          Mainz       Hannover     0     1    0    0
5   2017-08-19     Schalke 04     RB Leipzig     2     0    0    0
6   2017-08-19      Wolfsburg       Dortmund     0     3    0    0
7   2017-08-20       Freiburg  Ein Frankfurt     0     0    0    0
8   2017-08-20     M'gladbach        FC Koln     1     0    0    0
9   2017-08-25        FC Koln        Hamburg     1     3    0    3
10  2017-08-26       Augsburg     M'gladbach     2     2    0    3
11  2017-08-26       Dortmund         Hertha     2     0    3    3
12  2017-08-26  Ein Frankfurt      Wolfsburg     0     1    1    0
13  2017-08-26     Leverkusen     Hoffenheim     2     2    0    3
14  2017-08-26      Stuttgart          Mainz     1     0    0    0
15  2017-08-26  Werder Bremen  Bayern Munich     0     2    0    3
16  2017-08-27       Hannover     Schalke 04     1     0    3    3
17  2017-08-27     RB Leipzig       Freiburg     4     1    0    1
18  2017-09-08        Hamburg     RB Leipzig     0     2    6    3
19  2017-09-09       Augsburg        FC Koln     3     0    1    0
20  2017-09-09       Freiburg       Dortmund     0     0    1    6
21  2017-09-09     Hoffenheim  Bayern Munich     2     0    4    6
22  2017-09-09          Mainz     Leverkusen     3     1    0    1
23  2017-09-09     M'gladbach  Ein Frankfurt     0     1    4    1
24  2017-09-09      Wolfsburg       Hannover     1     1    3    6
25  2017-09-10         Hertha  Werder Bremen     1     1    3    0
26  2017-09-10     Schalke 04      Stuttgart     3     1    3    3
27  2017-09-15       Hannover        Hamburg     2     0    7    6
28  2017-09-16  Bayern Munich          Mainz     4     0    6    3
29  2017-09-16  Ein Frankfurt       Augsburg     1     2    4    4
30  2017-09-16     RB Leipzig     M'gladbach     2     2    6    4
31  2017-09-16      Stuttgart      Wolfsburg     1     0    3    4
32  2017-09-16  Werder Bremen     Schalke 04     1     2    1    6
33  2017-09-17       Dortmund        FC Koln     5     0    7    0
34  2017-09-17     Hoffenheim         Hertha     1     1    7    4
35  2017-09-17     Leverkusen       Freiburg     4     0    1    2
36  2017-09-19       Augsburg     RB Leipzig     1     0    7    7
37  2017-09-19     M'gladbach      Stuttgart     2     0    5    6
38  2017-09-19     Schalke 04  Bayern Munich     0     3    9    9
39  2017-09-19      Wolfsburg  Werder Bremen     1     1    4    1
40  2017-09-20        FC Koln  Ein Frankfurt     0     1    0    4
41  2017-09-20       Freiburg       Hannover     1     1    2   10
42  2017-09-20        Hamburg       Dortmund     0     3    6   10
43  2017-09-20         Hertha     Leverkusen     2     1    5    4
44  2017-09-20          Mainz     Hoffenheim     2     3    3    8
45  2017-09-22  Bayern Munich      Wolfsburg     2     2   12    5
46  2017-09-23       Dortmund     M'gladbach     6     1   13    8
47  2017-09-23     Hoffenheim     Schalke 04     2     0   11    9
48  2017-09-23          Mainz         Hertha     1     0    3    8
49  2017-09-23     RB Leipzig  Ein Frankfurt     2     1    7    7

GET TEAM FORM:

In [811]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,35):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 9)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 9)]
    
    j = num
    for i in range((num*9),306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 9) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat


def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [812]:
# Make changes to df
playing_statistics_01 = add_form_df(playing_statistics_01)
playing_statistics_02 = add_form_df(playing_statistics_02)

<ipython-input-811-3d357d7021db>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HM' + str(num)] = h
<ipython-input-811-3d357d7021db>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AM' + str(num)] = a

Get MatchWeek:

In [813]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(306):
        MatchWeek.append(j)
        if ((i + 1)% 9) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

In [814]:
playing_statistics_01 = get_mw(playing_statistics_01)
playing_statistics_02 = get_mw(playing_statistics_02)

<ipython-input-813-cdb248787c58>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['MW'] = MatchWeek

In [815]:
playing_statistics_02

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2017-07-28,Bochum,St Pauli,0,1,A,17,16,5,7,...,M,M,M,M,M,M,M,M,M,1
1,2017-07-29,Bielefeld,Regensburg,2,1,H,19,14,5,3,...,M,M,M,M,M,M,M,M,M,1
2,2017-07-29,Darmstadt,Greuther Furth,1,0,H,10,10,5,1,...,M,M,M,M,M,M,M,M,M,1
3,2017-07-29,Ingolstadt,Union Berlin,0,1,A,13,13,4,3,...,M,M,M,M,M,M,M,M,M,1
4,2017-07-30,Dresden,Duisburg,1,0,H,18,15,8,3,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,2018-05-13,Duisburg,St Pauli,2,0,H,13,11,4,3,...,W,W,W,W,L,L,L,D,L,34
302,2018-05-13,Heidenheim,Greuther Furth,1,1,D,16,8,4,4,...,D,W,L,D,D,W,L,L,D,34
303,2018-05-13,Holstein Kiel,Braunschweig,6,2,H,20,14,8,7,...,L,W,L,L,D,W,D,D,D,34
304,2018-05-13,Ingolstadt,Kaiserslautern,1,3,A,16,8,4,4,...,W,L,L,L,L,D,L,D,D,34
305,2018-05-13,Nurnberg,Fortuna Dusseldorf,2,3,A,13,11,4,6,...,D,W,W,W,W,D,L,W,L,34

FINAL DATAFRAME

In [816]:
playing_stat = pd.concat([playing_statistics_01,
                          playing_statistics_02], ignore_index=True)

# playing_stat = pd.concat([playing_statistics_01], ignore_index=True)

In [817]:
playing_stat

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2017-08-18,Bayern Munich,Leverkusen,3,1,H,13,19,8,4,...,M,M,M,M,M,M,M,M,M,1
1,2017-08-19,Hamburg,Augsburg,1,0,H,11,13,5,1,...,M,M,M,M,M,M,M,M,M,1
2,2017-08-19,Hertha,Stuttgart,2,0,H,10,9,3,2,...,M,M,M,M,M,M,M,M,M,1
3,2017-08-19,Hoffenheim,Werder Bremen,1,0,H,14,11,3,2,...,M,M,M,M,M,M,M,M,M,1
4,2017-08-19,Mainz,Hannover,0,1,A,14,6,6,2,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,2018-05-13,Duisburg,St Pauli,2,0,H,13,11,4,3,...,W,W,W,W,L,L,L,D,L,34
608,2018-05-13,Heidenheim,Greuther Furth,1,1,D,16,8,4,4,...,D,W,L,D,D,W,L,L,D,34
609,2018-05-13,Holstein Kiel,Braunschweig,6,2,H,20,14,8,7,...,L,W,L,L,D,W,D,D,D,34
610,2018-05-13,Ingolstadt,Kaiserslautern,1,3,A,16,8,4,4,...,W,L,L,L,L,D,L,D,D,34
611,2018-05-13,Nurnberg,Fortuna Dusseldorf,2,3,A,13,11,4,6,...,D,W,W,W,W,D,L,W,L,34

In [818]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS',
       'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HTGS',
       'ATGS', 'HTGC', 'ATGC', 'AGHSF', 'AGASF', 'AGHSC', 'AGASC', 'AGHSTF',
       'AGASTF', 'AGHSTC', 'AGASTC', 'AGHF', 'AGAF', 'AGHCF', 'AGACF', 'AGHCC',
       'AGACC', 'AGHY', 'AGAY', 'AGHR', 'AGAR', 'HTP', 'ATP', 'HM1', 'AM1',
       'HM2', 'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5', 'MW',
       'HTFormPtsStr', 'ATFormPtsStr', 'HTFormPts', 'ATFormPts',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [819]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in Shots fired
playing_stat['HTSD'] = playing_stat['AGHSF'] - playing_stat['AGHSC']
playing_stat['ATSD'] = playing_stat['AGASF'] - playing_stat['AGASC']

# Diff in shots on target
playing_stat['HTSTD'] = playing_stat['AGHSTF'] - playing_stat['AGHSTC']
playing_stat['ATSTD'] = playing_stat['AGASTF'] - playing_stat['AGASTC']

# Diff in corners
playing_stat['HTCD'] = playing_stat['AGHCF'] - playing_stat['AGHCC']
playing_stat['ATCD'] = playing_stat['AGACF'] - playing_stat['AGACC']

In [820]:
# Datensatz nicht gescaled
#playing_stat_raw = playing_stat
#playing_stat_raw.to_csv(loc + "2019_2020_ingame_1und2_raw.csv")

In [821]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP', "HTSD", "ATSD", "HTSTD", "ATSTD", "HTCD", "ATCD",
        "AGHY", "AGHR", "AGAR"]
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [822]:
playing_stat.MW

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
607    34.0
608    34.0
609    34.0
610    34.0
611    34.0
Name: MW, Length: 612, dtype: float64

In [823]:
playing_stat.to_csv(loc + "2016_2017_ingame_1und2.csv")
# playing_stat_test.to_csv(loc+"test.csv")