In [1]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [24]:
# Read data from the CSV into a dataframe

# Python pandas will read a csv file using utf-8 encoding defautly. 
# If the character encoding of this csv file is not utf-8, UnicodeDecodeError may occur.

loc = "/home/max/Dokumente/Projekte/Football_Game_Prediction/Data_Gathering/Buli_zweite/clean/"
# raw_data_93 = pd.read_csv(loc + '1993-94_new.csv') -> hier 20 teams => neues python skript f√ºr 93
raw_data_94 = pd.read_csv(loc + '1994-95.csv')
raw_data_95 = pd.read_csv(loc + '1995-96_new.csv')
raw_data_96 = pd.read_csv(loc + '1996-97_new.csv')
raw_data_97 = pd.read_csv(loc + '1997-98_new.csv')
raw_data_98 = pd.read_csv(loc + '1998-99_new.csv')
raw_data_99 = pd.read_csv(loc + '1999-00_new.csv')

raw_data_1 = pd.read_csv(loc + '2000-01.csv', sep=',', encoding='gbk')
raw_data_2 = pd.read_csv(loc + '2001-02.csv', sep=',', encoding='gbk')
raw_data_3 = pd.read_csv(loc + '2002-03_new.csv') 
raw_data_4 = pd.read_csv(loc + '2003-04_new.csv', sep=',', encoding='gbk')
raw_data_5 = pd.read_csv(loc + '2004-05.csv', sep=',', encoding='gbk')
raw_data_6 = pd.read_csv(loc + '2005-06.csv', sep=',', encoding='gbk')
raw_data_7 = pd.read_csv(loc + '2006-07.csv', sep=',', encoding='gbk')
raw_data_8 = pd.read_csv(loc + '2007-08.csv', sep=',', encoding='gbk')
raw_data_9 = pd.read_csv(loc + '2008-09.csv', sep=',', encoding='gbk')
raw_data_10 = pd.read_csv(loc + '2009-10.csv', sep=',', encoding='gbk')
raw_data_11 = pd.read_csv(loc + '2010-11.csv', sep=',', encoding='gbk')
raw_data_12 = pd.read_csv(loc + '2011-12.csv', sep=',', encoding='gbk')
raw_data_13 = pd.read_csv(loc + '2012-13.csv', sep=',', encoding='gbk')
raw_data_14 = pd.read_csv(loc + '2013-14.csv', sep=',', encoding='gbk')
raw_data_15 = pd.read_csv(loc + '2014-15.csv', sep=',', encoding='gbk')
raw_data_16 = pd.read_csv(loc + '2015-16.csv', sep=',', encoding='gbk')
raw_data_17 = pd.read_csv(loc + '2016-17.csv', sep=',', encoding='gbk')
raw_data_18 = pd.read_csv(loc + '2017-18.csv', sep=',', encoding='gbk')
raw_data_19 = pd.read_csv(loc + '2018-19_new.csv')
raw_data_20 = pd.read_csv(loc + '2019-20.csv')

In [25]:
# nochmal Date f√ºr die saisons kontrollieren, ob auch richtig eingelsen
raw_data_94.head(25)

    Unnamed: 0 Div      Date        HomeTeam        AwayTeam  FTHG  FTAG FTR
0            1  D1  19/08/94      Leverkusen  Kaiserslautern     0     1   A
1            2  D1  19/08/94      Schalke 04      M'gladbach     1     1   D
2            3  D1  19/08/94       Stuttgart         Hamburg     2     1   H
3            4  D1  20/08/94   Bayern Munich          Bochum     3     1   H
4            5  D1  20/08/94        Dortmund     Munich 1860     4     0   H
5            6  D1  20/08/94         Dresden   Werder Bremen     1     1   D
6            7  D1  20/08/94   Ein Frankfurt         FC Koln     0     0   D
7            8  D1  20/08/94       Karlsruhe        Freiburg     2     0   H
8            9  D1  20/08/94       Uerdingen        Duisburg     1     1   D
9           10  D1  23/08/94          Bochum         Dresden     2     0   H
10          11  D1  23/08/94         FC Koln        Dortmund     1     6   A
11          12  D1  23/08/94        Freiburg   Bayern Munich     5     1   H
12          13  D1  23/08/94  Kaiserslautern   Ein Frankfurt     1     1   D
13          14  D1  23/08/94     Munich 1860       Stuttgart     0     2   A
14          15  D1  24/08/94        Duisburg      Schalke 04     2     2   D
15          16  D1  24/08/94         Hamburg       Uerdingen     0     0   D
16          17  D1  24/08/94      M'gladbach       Karlsruhe     2     2   D
17          18  D1  24/08/94   Werder Bremen      Leverkusen     3     2   H
18          19  D1  26/08/94        Dortmund  Kaiserslautern     2     1   H
19          20  D1  26/08/94         Dresden        Freiburg     1     3   A
20          21  D1  27/08/94   Bayern Munich      M'gladbach     3     0   H
21          22  D1  27/08/94       Karlsruhe        Duisburg     4     1   H
22          23  D1  27/08/94      Schalke 04         Hamburg     0     1   A
23          24  D1  27/08/94       Stuttgart         FC Koln     2     2   D
24          25  D1  27/08/94       Uerdingen     Munich 1860     1     1   D

In [ ]:
# Date f√ºr 93-18: DD/MM/YY
# date f√ºr 19-20: DD/MM/YYY

In [28]:
raw_data_94.Date

0      19/08/94
1      19/08/94
2      19/08/94
3      20/08/94
4      20/08/94
         ...
301    17/06/95
302    17/06/95
303    17/06/95
304    17/06/95
305    17/06/95
Name: Date, Length: 306, dtype: object

In [29]:
# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

# funktion brauche ich nicht: form nur f√ºr obigen zwei!
def parse_date_other_2(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%Y-%m-%d').date()

In [30]:
raw_data_93.Date = raw_data_93.Date.apply(parse_date)   
raw_data_94.Date = raw_data_94.Date.apply(parse_date)   
raw_data_95.Date = raw_data_95.Date.apply(parse_date)   
raw_data_96.Date = raw_data_96.Date.apply(parse_date)   
raw_data_97.Date = raw_data_97.Date.apply(parse_date)   
raw_data_98.Date = raw_data_98.Date.apply(parse_date)   
raw_data_99.Date = raw_data_99.Date.apply(parse_date)   


raw_data_1.Date = raw_data_1.Date.apply(parse_date)    
raw_data_2.Date = raw_data_2.Date.apply(parse_date)    
raw_data_3.Date = raw_data_3.Date.apply(parse_date)          
raw_data_4.Date = raw_data_4.Date.apply(parse_date)    
raw_data_5.Date = raw_data_5.Date.apply(parse_date)    
raw_data_6.Date = raw_data_6.Date.apply(parse_date)    
raw_data_7.Date = raw_data_7.Date.apply(parse_date)    
raw_data_8.Date = raw_data_8.Date.apply(parse_date)    
raw_data_9.Date = raw_data_9.Date.apply(parse_date)    
raw_data_10.Date = raw_data_10.Date.apply(parse_date)
raw_data_11.Date = raw_data_11.Date.apply(parse_date)
raw_data_12.Date = raw_data_12.Date.apply(parse_date)
raw_data_13.Date = raw_data_13.Date.apply(parse_date)
raw_data_14.Date = raw_data_14.Date.apply(parse_date)
raw_data_15.Date = raw_data_15.Date.apply(parse_date)
raw_data_16.Date = raw_data_16.Date.apply(parse_date)
raw_data_17.Date = raw_data_17.Date.apply(parse_date)
raw_data_18.Date = raw_data_18.Date.apply(parse_date)
raw_data_19.Date = raw_data_19.Date.apply(parse_date_other)

raw_data_93.Date = raw_data_93.Date.apply(parse_date)
raw_data_20.Date = raw_data_20.Date.apply(parse_date_other)

In [32]:
# Date changend to format:YYYY-MM-DD - dt object
raw_data_97.Date

0      1997-08-01
1      1997-08-01
2      1997-08-02
3      1997-08-02
4      1997-08-02
          ...
301    1998-05-09
302    1998-05-09
303    1998-05-09
304    1998-05-09
305    1998-05-09
Name: Date, Length: 306, dtype: object

In [33]:
#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']

playing_statistics_93 = raw_data_93[columns_req]          
playing_statistics_94 = raw_data_94[columns_req]      
playing_statistics_95 = raw_data_95[columns_req]          
playing_statistics_96 = raw_data_96[columns_req]   
playing_statistics_97 = raw_data_97[columns_req]          
playing_statistics_98 = raw_data_98[columns_req]   
playing_statistics_99 = raw_data_99[columns_req]   

playing_statistics_1 = raw_data_1[columns_req]                      
playing_statistics_2 = raw_data_2[columns_req]
playing_statistics_3 = raw_data_3[columns_req]
playing_statistics_4 = raw_data_4[columns_req]
playing_statistics_5 = raw_data_5[columns_req]
playing_statistics_6 = raw_data_6[columns_req]
playing_statistics_7 = raw_data_7[columns_req]
playing_statistics_8 = raw_data_8[columns_req]
playing_statistics_9 = raw_data_9[columns_req]
playing_statistics_10 = raw_data_10[columns_req]
playing_statistics_11 = raw_data_11[columns_req]   
playing_statistics_12 = raw_data_12[columns_req]
playing_statistics_13 = raw_data_13[columns_req]
playing_statistics_14 = raw_data_14[columns_req]
playing_statistics_15 = raw_data_15[columns_req]
playing_statistics_16 = raw_data_16[columns_req]
playing_statistics_17 = raw_data_17[columns_req]
playing_statistics_18 = raw_data_18[columns_req]
playing_statistics_19 = raw_data_19[columns_req]
playing_statistics_20 = raw_data_20[columns_req]

In [36]:
# check
playing_statistics_94

           Date       HomeTeam        AwayTeam  FTHG  FTAG FTR
0    1994-08-19     Leverkusen  Kaiserslautern     0     1   A
1    1994-08-19     Schalke 04      M'gladbach     1     1   D
2    1994-08-19      Stuttgart         Hamburg     2     1   H
3    1994-08-20  Bayern Munich          Bochum     3     1   H
4    1994-08-20       Dortmund     Munich 1860     4     0   H
..          ...            ...             ...   ...   ...  ..
301  1995-06-17      Karlsruhe          Bochum     2     2   D
302  1995-06-17     Leverkusen         Dresden     2     2   D
303  1995-06-17     Schalke 04        Freiburg     1     2   A
304  1995-06-17      Stuttgart        Duisburg     3     1   H
305  1995-06-17      Uerdingen      M'gladbach     3     2   H

[306 rows x 6 columns]

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK **

In [37]:
# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,35):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 9) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [38]:
# Apply to each dataset

playing_statistics_93 = get_gss(playing_statistics_93)
playing_statistics_94 = get_gss(playing_statistics_94)
playing_statistics_95 = get_gss(playing_statistics_95)
playing_statistics_96 = get_gss(playing_statistics_96)
playing_statistics_97 = get_gss(playing_statistics_97)
playing_statistics_98 = get_gss(playing_statistics_98)
playing_statistics_99 = get_gss(playing_statistics_99)

playing_statistics_1 = get_gss(playing_statistics_1)
playing_statistics_2 = get_gss(playing_statistics_2)
playing_statistics_3 = get_gss(playing_statistics_3)
playing_statistics_4 = get_gss(playing_statistics_4)
playing_statistics_5 = get_gss(playing_statistics_5)
playing_statistics_6 = get_gss(playing_statistics_6)
playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)
playing_statistics_9 = get_gss(playing_statistics_9)
playing_statistics_10 = get_gss(playing_statistics_10)
playing_statistics_11 = get_gss(playing_statistics_11)
playing_statistics_12 = get_gss(playing_statistics_12)
playing_statistics_13 = get_gss(playing_statistics_13)
playing_statistics_14 = get_gss(playing_statistics_14)
playing_statistics_15 = get_gss(playing_statistics_15)
playing_statistics_16 = get_gss(playing_statistics_16)

playing_statistics_17 = get_gss(playing_statistics_17)
playing_statistics_18 = get_gss(playing_statistics_18)
playing_statistics_19 = get_gss(playing_statistics_19)
playing_statistics_20 = get_gss(playing_statistics_20)

<ipython-input-37-24a31de75eb3>:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGS'] = HTGS
<ipython-input-37-24a31de75eb3>:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGS'] = ATGS
<ipython-input-37-24a31de75eb3>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGC'] = HTGC
<ipython-input-37-24a31de75eb3>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGC'] = ATGC

In [40]:
playing_statistics_93

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC
0,1993-08-07,Bayern Munich,Freiburg,3,1,H,0,0,0,0
1,1993-08-07,Dortmund,Karlsruhe,2,1,H,0,0,0,0
2,1993-08-07,Duisburg,Leverkusen,2,2,D,0,0,0,0
3,1993-08-07,FC Koln,Kaiserslautern,0,2,A,0,0,0,0
4,1993-08-07,Hamburg,Nurnberg,5,2,H,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
301,1994-05-07,Hamburg,Kaiserslautern,1,3,A,47,61,49,35
302,1994-05-07,Leipzig,Leverkusen,2,3,A,30,57,66,45
303,1994-05-07,Stuttgart,Dresden,3,0,H,48,33,43,41
304,1994-05-07,Wattenscheid,Karlsruhe,5,1,H,43,45,69,38
305,1994-05-07,Werder Bremen,M'Gladbach,4,2,H,47,63,42,55

GET RESPECTIVE POINTS:

In [41]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0
    

def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,35):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(18)])
    return matchres_points


def get_matchres(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
            
    return pd.DataFrame(data=teams, index = [i for i in range(1,35)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []
    j = 0
    for i in range(306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

        if ((i + 1)% 9) == 0:
            j = j + 1
            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat

In [42]:
# Apply to each dataset

playing_statistics_93 = get_agg_points(playing_statistics_93)
playing_statistics_94 = get_agg_points(playing_statistics_94)
playing_statistics_95 = get_agg_points(playing_statistics_95)
playing_statistics_96 = get_agg_points(playing_statistics_96)
playing_statistics_97 = get_agg_points(playing_statistics_97)
playing_statistics_98 = get_agg_points(playing_statistics_98)
playing_statistics_99 = get_agg_points(playing_statistics_99)

playing_statistics_1 = get_agg_points(playing_statistics_1)
playing_statistics_2 = get_agg_points(playing_statistics_2)
playing_statistics_3 = get_agg_points(playing_statistics_3)
playing_statistics_4 = get_agg_points(playing_statistics_4)
playing_statistics_5 = get_agg_points(playing_statistics_5)
playing_statistics_6 = get_agg_points(playing_statistics_6)
playing_statistics_7 = get_agg_points(playing_statistics_7)
playing_statistics_8 = get_agg_points(playing_statistics_8)
playing_statistics_9 = get_agg_points(playing_statistics_9)
playing_statistics_10 = get_agg_points(playing_statistics_10)
playing_statistics_11 = get_agg_points(playing_statistics_11)
playing_statistics_12 = get_agg_points(playing_statistics_12)
playing_statistics_13 = get_agg_points(playing_statistics_13)
playing_statistics_14 = get_agg_points(playing_statistics_14)
playing_statistics_15 = get_agg_points(playing_statistics_15)
playing_statistics_16 = get_agg_points(playing_statistics_16)

playing_statistics_17 = get_agg_points(playing_statistics_17)
playing_statistics_18 = get_agg_points(playing_statistics_18)
playing_statistics_19 = get_agg_points(playing_statistics_19)
playing_statistics_20 = get_agg_points(playing_statistics_20)

<ipython-input-41-ebeaecbf5df5>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTP'] = HTP
<ipython-input-41-ebeaecbf5df5>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATP'] = ATP

GET TEAM FORM:

In [43]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,35):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 9)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 9)]
    
    j = num
    for i in range((num*9),306):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 9) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat


def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [44]:
# Make changes to df
playing_statistics_93 = add_form_df(playing_statistics_93)
playing_statistics_94 = add_form_df(playing_statistics_94)
playing_statistics_95 = add_form_df(playing_statistics_95)
playing_statistics_96 = add_form_df(playing_statistics_96)
playing_statistics_97 = add_form_df(playing_statistics_97)
playing_statistics_98 = add_form_df(playing_statistics_98)
playing_statistics_99 = add_form_df(playing_statistics_99)


playing_statistics_1 = add_form_df(playing_statistics_1)
playing_statistics_2 = add_form_df(playing_statistics_2)
playing_statistics_3 = add_form_df(playing_statistics_3)
playing_statistics_4 = add_form_df(playing_statistics_4)
playing_statistics_5 = add_form_df(playing_statistics_5)
playing_statistics_6 = add_form_df(playing_statistics_6)
playing_statistics_7 = add_form_df(playing_statistics_7)
playing_statistics_8 = add_form_df(playing_statistics_8)
playing_statistics_9 = add_form_df(playing_statistics_9)
playing_statistics_10 = add_form_df(playing_statistics_10)
playing_statistics_11 = add_form_df(playing_statistics_11)
playing_statistics_12 = add_form_df(playing_statistics_12)
playing_statistics_13 = add_form_df(playing_statistics_13)
playing_statistics_14 = add_form_df(playing_statistics_14)
playing_statistics_15 = add_form_df(playing_statistics_15)    
playing_statistics_16 = add_form_df(playing_statistics_16)

playing_statistics_17 = add_form_df(playing_statistics_17)
playing_statistics_18 = add_form_df(playing_statistics_18)
playing_statistics_19 = add_form_df(playing_statistics_19)
playing_statistics_20 = add_form_df(playing_statistics_20)

<ipython-input-43-3d357d7021db>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HM' + str(num)] = h
<ipython-input-43-3d357d7021db>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AM' + str(num)] = a

In [45]:
playing_statistics_93

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,...,HM1,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5
0,1993-08-07,Bayern Munich,Freiburg,3,1,H,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
1,1993-08-07,Dortmund,Karlsruhe,2,1,H,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
2,1993-08-07,Duisburg,Leverkusen,2,2,D,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
3,1993-08-07,FC Koln,Kaiserslautern,0,2,A,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
4,1993-08-07,Hamburg,Nurnberg,5,2,H,0,0,0,0,...,M,M,M,M,M,M,M,M,M,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,1994-05-07,Hamburg,Kaiserslautern,1,3,A,47,61,49,35,...,D,W,L,W,L,W,D,W,D,W
302,1994-05-07,Leipzig,Leverkusen,2,3,A,30,57,66,45,...,L,D,D,D,L,L,L,W,L,D
303,1994-05-07,Stuttgart,Dresden,3,0,H,48,33,43,41,...,D,W,L,D,W,W,W,W,L,L
304,1994-05-07,Wattenscheid,Karlsruhe,5,1,H,43,45,69,38,...,L,D,L,W,L,W,W,L,L,W
305,1994-05-07,Werder Bremen,M'Gladbach,4,2,H,47,63,42,55,...,L,W,W,W,W,D,D,L,W,W

In [46]:
# Rearranging columns
cols = ['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS', 'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3',
        'HM4', 'HM5', 'AM1', 'AM2', 'AM3', 'AM4', 'AM5' ]

playing_statistics_93 = playing_statistics_93[cols]
playing_statistics_94 = playing_statistics_94[cols]
playing_statistics_95 = playing_statistics_95[cols]
playing_statistics_96 = playing_statistics_96[cols]
playing_statistics_97 = playing_statistics_97[cols]
playing_statistics_98 = playing_statistics_98[cols]
playing_statistics_99 = playing_statistics_99[cols]

playing_statistics_1 = playing_statistics_1[cols]
playing_statistics_2 = playing_statistics_2[cols]
playing_statistics_3 = playing_statistics_3[cols]
playing_statistics_4 = playing_statistics_4[cols]
playing_statistics_5 = playing_statistics_5[cols]
playing_statistics_6 = playing_statistics_6[cols]
playing_statistics_7 = playing_statistics_7[cols]
playing_statistics_8 = playing_statistics_8[cols]
playing_statistics_9 = playing_statistics_9[cols]
playing_statistics_10 = playing_statistics_10[cols]
playing_statistics_11 = playing_statistics_11[cols]
playing_statistics_12 = playing_statistics_12[cols]
playing_statistics_13 = playing_statistics_13[cols]
playing_statistics_14 = playing_statistics_14[cols]
playing_statistics_15 = playing_statistics_15[cols]
playing_statistics_16 = playing_statistics_16[cols]

playing_statistics_17 = playing_statistics_17[cols]
playing_statistics_18 = playing_statistics_18[cols]
playing_statistics_19 = playing_statistics_19[cols]
playing_statistics_20 = playing_statistics_20[cols]

Get MatchWeek:

In [47]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(306):
        MatchWeek.append(j)
        if ((i + 1)% 9) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

In [48]:
playing_statistics_93 = get_mw(playing_statistics_93)
playing_statistics_94 = get_mw(playing_statistics_94)
playing_statistics_95 = get_mw(playing_statistics_95)
playing_statistics_96 = get_mw(playing_statistics_96)
playing_statistics_97 = get_mw(playing_statistics_97)
playing_statistics_98 = get_mw(playing_statistics_98)
playing_statistics_99 = get_mw(playing_statistics_99)

playing_statistics_1 = get_mw(playing_statistics_1)
playing_statistics_2 = get_mw(playing_statistics_2)
playing_statistics_3 = get_mw(playing_statistics_3)
playing_statistics_4 = get_mw(playing_statistics_4)
playing_statistics_5 = get_mw(playing_statistics_5)
playing_statistics_6 = get_mw(playing_statistics_6)
playing_statistics_7 = get_mw(playing_statistics_7)
playing_statistics_8 = get_mw(playing_statistics_8)
playing_statistics_9 = get_mw(playing_statistics_9)
playing_statistics_10 = get_mw(playing_statistics_10)
playing_statistics_11 = get_mw(playing_statistics_11)
playing_statistics_12 = get_mw(playing_statistics_12)
playing_statistics_13 = get_mw(playing_statistics_13)
playing_statistics_14 = get_mw(playing_statistics_14)
playing_statistics_15 = get_mw(playing_statistics_15)
playing_statistics_16 = get_mw(playing_statistics_16)

playing_statistics_17 = get_mw(playing_statistics_17)
playing_statistics_18 = get_mw(playing_statistics_18)
playing_statistics_19 = get_mw(playing_statistics_19)
playing_statistics_20 = get_mw(playing_statistics_20)

<ipython-input-47-cdb248787c58>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['MW'] = MatchWeek

FINAL DATAFRAME

In [49]:
playing_stat = pd.concat([playing_statistics_93,
                          playing_statistics_94,
                          playing_statistics_95,
                          playing_statistics_96,
                          playing_statistics_97,
                          playing_statistics_98,
                          playing_statistics_99,
                          playing_statistics_1,
                          playing_statistics_2,
                          playing_statistics_3,
                          playing_statistics_4,
                          playing_statistics_5,
                          playing_statistics_6,
                          playing_statistics_7,
                          playing_statistics_8,
                          playing_statistics_9,
                          playing_statistics_10,
                          playing_statistics_11,
                          playing_statistics_12,
                          playing_statistics_13,
                          playing_statistics_14,
                          playing_statistics_15,
                          playing_statistics_16,
                          playing_statistics_17,
                          playing_statistics_18,
                          playing_statistics_19,
                          playing_statistics_20,], ignore_index=True)

In [50]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTGS', 'ATGS',
       'HTGC', 'ATGC', 'HTP', 'ATP', 'HM1', 'HM2', 'HM3', 'HM4', 'HM5', 'AM1',
       'AM2', 'AM3', 'AM4', 'AM5', 'MW', 'HTFormPtsStr', 'ATFormPtsStr',
       'HTFormPts', 'ATFormPts', 'HTWinStreak3', 'HTWinStreak5',
       'HTLossStreak3', 'HTLossStreak5', 'ATWinStreak3', 'ATWinStreak5',
       'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [51]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

In [213]:
# Datensatz nicht gescaled
playing_stat_raw = playing_stat
playing_stat_raw.to_csv(loc + "final_dataset_raw.csv")

In [52]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP']
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [53]:
playing_stat.MW

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
8257    34.0
8258    34.0
8259    34.0
8260    34.0
8261    34.0
Name: MW, Length: 8262, dtype: float64

In [54]:
playing_stat.to_csv(loc + "final_dataset.csv")
# playing_stat_test.to_csv(loc+"test.csv")