In [181]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [182]:
# 20 Mannschaften * 19 = 380 Spiele pro Saison
# 2&3 Liga sogar 24!

In [183]:
# Read data from the CSV into a dataframe

# Python pandas will read a csv file using utf_8 encoding defautly. 
# If the character encoding of this csv file is not utf_8, UnicodeDecodeError may occur.

loc = "/home/max/Dokumente/Projekte/Football_Game_Prediction/Data_Gathering/La_Liga_1_und_2_in_Game_Spanien/Primera/"
#raw_data_1 = pd.read_csv(loc + '2000_2001.csv', sep=',', encoding='gbk')
#raw_data_2 = pd.read_csv(loc + '2001_2002.csv', sep=',', encoding='gbk')
#raw_data_3 = pd.read_csv(loc + '2002_2003.csv', sep=',', encoding='gbk') 
# raw_data_4 = pd.read_csv(loc + '2003_2004.csv')
# raw_data_5 = pd.read_csv(loc + '2004_2005.csv', sep=';', encoding='gbk')
raw_data_6 = pd.read_csv(loc + '2005_2006.csv', sep=',', encoding='gbk')
raw_data_7 = pd.read_csv(loc + '2006_2007.csv', sep=',', encoding='gbk')
raw_data_8 = pd.read_csv(loc + '2007_2008.csv', sep=',', encoding='gbk')
raw_data_9 = pd.read_csv(loc + '2008_2009.csv', sep=',', encoding='gbk')
raw_data_10 = pd.read_csv(loc + '2009_2010.csv', sep=',', encoding='gbk')
raw_data_11 = pd.read_csv(loc + '2010_2011.csv', sep=',', encoding='gbk')
raw_data_12 = pd.read_csv(loc + '2011_2012.csv', sep=',', encoding='gbk')
raw_data_13 = pd.read_csv(loc + '2012_2013.csv', sep=',', encoding='gbk')
raw_data_14 = pd.read_csv(loc + '2013_2014.csv', sep=',', encoding='gbk')
raw_data_15 = pd.read_csv(loc + '2014_2015.csv', sep=',', encoding='gbk')
raw_data_16 = pd.read_csv(loc + '2015_2016.csv', sep=',', encoding='gbk')
raw_data_17 = pd.read_csv(loc + '2016_2017.csv', sep=',', encoding='gbk')
raw_data_18 = pd.read_csv(loc + '2017_2018.csv', sep=',', encoding='gbk')
raw_data_19 = pd.read_csv(loc + '2018_2019.csv', sep=',', encoding='gbk')
raw_data_20 = pd.read_csv(loc + '2019_2020.csv', sep=',', encoding='gbk')

In [184]:
#raw_data_15.drop(raw_data_15.tail(1).index,inplace=True) # drop last n rows

In [185]:
raw_data_15

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,SP1,23/08/14,Almeria,Espanol,1,1,D,0,0,D,...,1.64,26,0.00,1.98,1.91,2.00,1.94,3.19,3.26,2.50
1,SP1,23/08/14,Granada,La Coruna,2,1,H,0,1,A,...,1.54,24,-0.50,2.11,2.04,1.88,1.84,2.20,3.34,3.75
2,SP1,23/08/14,Malaga,Ath Bilbao,1,0,H,1,0,H,...,1.77,26,0.00,2.09,2.03,1.88,1.83,3.14,3.23,2.56
3,SP1,23/08/14,Sevilla,Valencia,1,1,D,1,0,H,...,1.92,23,-0.50,2.10,2.03,1.90,1.84,2.29,3.46,3.40
4,SP1,24/08/14,Barcelona,Elche,3,0,H,1,0,H,...,3.48,27,-2.50,1.89,1.77,2.18,2.10,1.11,12.80,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,SP1,23/05/15,Granada,Ath Madrid,0,0,D,0,0,D,...,1.59,25,0.25,1.98,1.92,1.98,1.94,7.58,2.36,2.14
376,SP1,23/05/15,Levante,Elche,0,0,D,0,0,D,...,1.81,26,-0.50,2.03,1.99,1.92,1.86,2.06,3.49,4.04
377,SP1,23/05/15,Malaga,Sevilla,2,3,A,0,0,D,...,2.60,25,0.25,2.02,1.98,1.94,1.88,2.94,3.74,2.42
378,SP1,23/05/15,Real Madrid,Getafe,7,3,H,3,3,D,...,4.51,22,-2.50,1.80,1.76,2.21,2.12,1.13,12.59,19.71
379,SP1,23/05/15,Vallecano,Sociedad,2,4,A,1,2,A,...,2.53,26,-0.50,1.91,1.87,2.03,1.98,2.15,3.85,3.37

In [186]:
raw_data_20.Date

0      16/08/2019
1      17/08/2019
2      17/08/2019
3      17/08/2019
4      17/08/2019
          ...
375    19/07/2020
376    19/07/2020
377    19/07/2020
378    19/07/2020
379    19/07/2020
Name: Date, Length: 380, dtype: object

In [187]:
# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

# funktion brauche ich nicht: form nur für obigen zwei!
def parse_date_other_2(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%Y-%m-%d').date()

In [188]:
#raw_data_1.Date = raw_data_1.Date.apply(parse_date)    
#raw_data_2.Date = raw_data_2.Date.apply(parse_date)    
#raw_data_3.Date = raw_data_3.Date.apply(parse_date_other)          
# raw_data_4.Date = raw_data_4.Date.apply(parse_date)    
# raw_data_5.Date = raw_data_5.Date.apply(parse_date)    
raw_data_6.Date = raw_data_6.Date.apply(parse_date)    
raw_data_7.Date = raw_data_7.Date.apply(parse_date)    
raw_data_8.Date = raw_data_8.Date.apply(parse_date)    
raw_data_9.Date = raw_data_9.Date.apply(parse_date)    
raw_data_10.Date = raw_data_10.Date.apply(parse_date)
raw_data_11.Date = raw_data_11.Date.apply(parse_date)
raw_data_12.Date = raw_data_12.Date.apply(parse_date)
raw_data_13.Date = raw_data_13.Date.apply(parse_date)
raw_data_14.Date = raw_data_14.Date.apply(parse_date)
raw_data_15.Date = raw_data_15.Date.apply(parse_date)
raw_data_16.Date = raw_data_16.Date.apply(parse_date)
raw_data_17.Date = raw_data_17.Date.apply(parse_date)
raw_data_18.Date = raw_data_18.Date.apply(parse_date)
raw_data_19.Date = raw_data_19.Date.apply(parse_date_other)
raw_data_20.Date = raw_data_20.Date.apply(parse_date_other)

In [189]:
#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR', "HS", "AS", "HST", "AST", "HC", 
                          "AC", "HF", "AF", "HY", "AY", "HR", "AR"]

#playing_statistics_1 = raw_data_1[columns_req]    
#playing_statistics_2 = raw_data_2[columns_req]   
#playing_statistics_3 = raw_data_3[columns_req]    
#playing_statistics_4 = raw_data_4[columns_req]   
#playing_statistics_5 = raw_data_5[columns_req]  
playing_statistics_6 = raw_data_6[columns_req]    
playing_statistics_7 = raw_data_7[columns_req]    
playing_statistics_8 = raw_data_8[columns_req] 
playing_statistics_9 = raw_data_9[columns_req]    
playing_statistics_10 = raw_data_10[columns_req]    
playing_statistics_11 = raw_data_12[columns_req]  
playing_statistics_12 = raw_data_12[columns_req]  
playing_statistics_13 = raw_data_13[columns_req]  
playing_statistics_14 = raw_data_14[columns_req] 
playing_statistics_15 = raw_data_15[columns_req]   
playing_statistics_16 = raw_data_16[columns_req]
playing_statistics_17 = raw_data_17[columns_req] 
playing_statistics_18 = raw_data_18[columns_req]  
playing_statistics_19 = raw_data_19[columns_req]  
playing_statistics_20 = raw_data_20[columns_req]

In [190]:
playing_statistics_17

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
0,2016-08-19,La Coruna,Eibar,2,1,H,11,12,6,6,1,8,14,17,3,3,0,0
1,2016-08-19,Malaga,Osasuna,1,1,D,14,8,4,3,5,3,11,22,2,3,0,0
2,2016-08-20,Barcelona,Betis,6,2,H,30,6,12,2,10,2,17,13,1,3,0,0
3,2016-08-20,Granada,Villarreal,1,1,D,7,12,1,3,7,3,17,11,2,3,0,0
4,2016-08-20,Sevilla,Espanol,6,4,H,16,10,11,7,8,2,8,15,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2017-05-21,Ath Madrid,Ath Bilbao,3,1,H,12,16,4,1,2,5,13,11,2,0,0,0
376,2017-05-21,Barcelona,Eibar,4,2,H,18,6,11,4,10,4,3,16,1,2,0,1
377,2017-05-21,Celta,Sociedad,2,2,D,13,18,5,8,3,7,8,17,2,1,0,0
378,2017-05-21,Malaga,Real Madrid,0,2,A,22,16,6,8,9,7,6,9,2,0,0,0
379,2017-05-21,Valencia,Villarreal,1,3,A,16,14,5,6,9,0,15,10,2,2,0,0

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK **

Bundesliga sind 18 Teams => 18x17 sind 306 Spiele
Premier League: sind 20 Teams => 20x19 sind 380 Spiele
=> ändere if ((i + 1)% 9) == 0: zu if ((i + 1)% 10) == 0:

In [191]:
# alle 302 mit 380 ersetzen!
# Shape of passed values is (38, 20), indices imply (34, 20) => jede 39 mit 39 ersetzen!

# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [192]:
# Apply to each dataset

#playing_statistics_1 = get_gss(playing_statistics_1)
#playing_statistics_2 = get_gss(playing_statistics_2)
#playing_statistics_3 = get_gss(playing_statistics_3)
#playing_statistics_4 = get_gss(playing_statistics_4)
#playing_statistics_5 = get_gss(playing_statistics_5)
playing_statistics_6 = get_gss(playing_statistics_6)
playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)
playing_statistics_9 = get_gss(playing_statistics_9)
playing_statistics_10 = get_gss(playing_statistics_10)
playing_statistics_11 = get_gss(playing_statistics_11)
playing_statistics_12 = get_gss(playing_statistics_12)
playing_statistics_13 = get_gss(playing_statistics_13)
playing_statistics_14 = get_gss(playing_statistics_14)
playing_statistics_15 = get_gss(playing_statistics_15)
playing_statistics_16 = get_gss(playing_statistics_16)
playing_statistics_17 = get_gss(playing_statistics_17)
playing_statistics_18 = get_gss(playing_statistics_18)
playing_statistics_19 = get_gss(playing_statistics_19)
playing_statistics_20 = get_gss(playing_statistics_20)

# danach immer kopieren und befehlt get_gss mit jeweiliger funktion für alle ersetzen! + loops verbessern!

<ipython-input-191-744d34d6ae2f>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGS'] = HTGS
<ipython-input-191-744d34d6ae2f>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGS'] = ATGS
<ipython-input-191-744d34d6ae2f>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGC'] = HTGC
<ipython-input-191-744d34d6ae2f>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGC'] = ATGC

In [193]:
playing_statistics_8[['Date', "HomeTeam", "AwayTeam", "FTHG", "FTAG", "HTGS", "ATGS", "HTGC", "ATGC"]].head(60)

          Date     HomeTeam     AwayTeam  FTHG  FTAG  HTGS  ATGS  HTGC  ATGC
0   2007-08-25  Real Madrid   Ath Madrid     2     1     0     0     0     0
1   2007-08-25      Sevilla       Getafe     4     1     0     0     0     0
2   2007-08-26   Ath Bilbao      Osasuna     0     0     0     0     0     0
3   2007-08-26      Espanol   Valladolid     0     1     0     0     0     0
4   2007-08-26    La Coruna      Almeria     0     3     0     0     0     0
5   2007-08-26     Mallorca      Levante     3     0     0     0     0     0
6   2007-08-26       Murcia     Zaragoza     2     1     0     0     0     0
7   2007-08-26   Recreativo        Betis     1     1     0     0     0     0
8   2007-08-26    Santander    Barcelona     0     0     0     0     0     0
9   2007-08-26     Valencia   Villarreal     0     3     0     0     0     0
10  2007-09-01      Levante       Murcia     0     0     0     2     3     1
11  2007-09-01     Zaragoza    Santander     1     1     1     0     2     0
12  2007-09-02      Almeria     Valencia     1     2     3     0     0     3
13  2007-09-02   Ath Madrid     Mallorca     1     1     1     3     2     0
14  2007-09-02    Barcelona   Ath Bilbao     3     1     0     0     0     0
15  2007-09-02        Betis      Espanol     2     2     1     0     1     1
16  2007-09-02       Getafe   Recreativo     1     1     1     1     4     1
17  2007-09-02   Valladolid    La Coruna     2     2     1     0     0     3
18  2007-09-02   Villarreal  Real Madrid     0     5     3     2     0     1
19  2007-09-15   Ath Bilbao     Zaragoza     1     1     0     1     0     2
20  2007-09-15  Real Madrid      Almeria     3     1     7     4     1     2
21  2007-09-15     Valencia   Valladolid     2     1     2     3     4     2
22  2007-09-16      Espanol       Getafe     1     0     2     2     3     5
23  2007-09-16    La Coruna        Betis     1     0     2     3     5     3
24  2007-09-16     Mallorca   Villarreal     0     1     4     3     1     5
25  2007-09-16       Murcia   Ath Madrid     1     1     2     2     1     3
26  2007-09-16      Osasuna    Barcelona     0     0     0     3     0     1
27  2007-09-16    Santander      Levante     1     0     1     0     1     3
28  2007-09-16      Sevilla   Recreativo     4     1     8     2     2     2
29  2007-09-22    Barcelona      Sevilla     2     1     3     8     1     2
30  2007-09-22   Recreativo      Espanol     2     1     3     3     6     3
31  2007-09-23      Almeria     Mallorca     1     1     5     4     5     2
32  2007-09-23   Ath Madrid    Santander     4     0     3     2     4     1
33  2007-09-23        Betis     Valencia     1     2     3     4     4     5
34  2007-09-23       Getafe    La Coruna     0     0     2     3     6     5
35  2007-09-23      Levante   Ath Bilbao     1     2     0     2     4     4
36  2007-09-23   Valladolid  Real Madrid     1     1     4    10     4     2
37  2007-09-23   Villarreal       Murcia     2     0     4     3     5     2
38  2007-09-23     Zaragoza      Osasuna     2     1     3     1     4     2
39  2007-09-25      Sevilla      Espanol     2     3     9     3     4     3
40  2007-09-26   Ath Bilbao   Ath Madrid     0     2     4     7     5     4
41  2007-09-26    Barcelona     Zaragoza     4     1     5     5     2     5
42  2007-09-26    La Coruna   Recreativo     0     2     3     5     5     7
43  2007-09-26     Mallorca   Valladolid     4     2     5     5     3     5
44  2007-09-26       Murcia      Almeria     0     1     3     6     4     6
45  2007-09-26      Osasuna      Levante     4     1     5     1     3     6
46  2007-09-26    Santander   Villarreal     0     2     2     6     5     5
47  2007-09-26     Valencia       Getafe     2     1     6     2     6     6
48  2007-09-27  Real Madrid        Betis     2     0    11     4     3     6
49  2007-09-29      Levante    Barcelona     1     4     1     5     6     2
50  2007-09-29     Zaragoza      Sevilla     2     0     6    11     9     9
51  2007-09-30      Almeria    Santander     0     1     7     2     6     7
52  2007-09-30   Ath Madrid      Osasuna     2     0     9     5     4     5
53  2007-09-30        Betis     Mallorca     3     0     4     9     8     5
54  2007-09-30      Espanol    La Coruna     1     0     7     3     7     7
55  2007-09-30       Getafe  Real Madrid     0     1     3    13     8     3
56  2007-09-30   Recreativo     Valencia     0     1     7     8     7     7
57  2007-09-30   Valladolid       Murcia     1     4     7     3     9     5
58  2007-09-30   Villarreal   Ath Bilbao     1     0     8     4     5     7
59  2007-10-06     Valencia      Espanol     1     2     8     7     7     7

Get Home and Away Shots

In [194]:
# Gets the shots fired agg arranged by teams and matchweek
def get_shots_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSF = playing_stat.iloc[i]['HS']
        # aggregated Home Team shots
        AGASF = playing_stat.iloc[i]['AS']
        # aggregated Away Team shots
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired




# Gets the goals conceded agg arranged by teams and matchweek
def get_shots_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASC = playing_stat.iloc[i]['HS']
        # aggregated home team shots conceded
        AGHSC = playing_stat.iloc[i]['AS']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded



def get_sf(playing_stat):
    SF = get_shots_fired(playing_stat)
    SC = get_shots_conceded(playing_stat)
   
    j = 0
    AGHSF = []
    AGASF = []
    AGHSC = []
    AGASC = []    

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSF.append(SF.loc[ht][j])
        AGASF.append(SF.loc[at][j])
        AGHSC.append(SC.loc[ht][j])
        AGASC.append(SC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHSF'] = AGHSF
    playing_stat['AGASF'] = AGASF
    playing_stat['AGHSC'] = AGHSC
    playing_stat['AGASC'] = AGASC
    return playing_stat

In [195]:
#playing_statistics_1 = get_sf(playing_statistics_1)
#playing_statistics_2 = get_sf(playing_statistics_2)
#playing_statistics_3 = get_sf(playing_statistics_3)
#playing_statistics_4 = get_sf(playing_statistics_4)
#playing_statistics_5 = get_sf(playing_statistics_5)
playing_statistics_6 = get_sf(playing_statistics_6)
playing_statistics_7 = get_sf(playing_statistics_7)
playing_statistics_8 = get_sf(playing_statistics_8)
playing_statistics_9 = get_sf(playing_statistics_9)
playing_statistics_10 = get_sf(playing_statistics_10)
playing_statistics_11 = get_sf(playing_statistics_11)
playing_statistics_12 = get_sf(playing_statistics_12)
playing_statistics_13 = get_sf(playing_statistics_13)
playing_statistics_14 = get_sf(playing_statistics_14)
playing_statistics_15 = get_sf(playing_statistics_15)
playing_statistics_16 = get_sf(playing_statistics_16)
playing_statistics_17 = get_sf(playing_statistics_17)
playing_statistics_18 = get_sf(playing_statistics_18)
playing_statistics_19 = get_sf(playing_statistics_19)
playing_statistics_20 = get_sf(playing_statistics_20)

<ipython-input-194-86deb0bf7e72>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSF'] = AGHSF
<ipython-input-194-86deb0bf7e72>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASF'] = AGASF
<ipython-input-194-86deb0bf7e72>:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSC'] = AGHSC
<ipython-input-194-86deb0bf7e72>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASC'] = AGASC

In [196]:
playing_statistics_9[['Date', "HomeTeam", "AwayTeam", "HS", "AS",'AGHSF', "AGASF", "AGHSC", "AGASC"]].head(50)

          Date     HomeTeam     AwayTeam  HS  AS  AGHSF  AGASF  AGHSC  AGASC
0   2008-08-30      Espanol   Valladolid  10  11      0      0      0      0
1   2008-08-30     Valencia     Mallorca  17  16      0      0      0      0
2   2008-08-31   Ath Bilbao      Almeria  10  11      0      0      0      0
3   2008-08-31   Ath Madrid       Malaga  25   7      0      0      0      0
4   2008-08-31        Betis   Recreativo   8  13      0      0      0      0
5   2008-08-31    La Coruna  Real Madrid  11  18      0      0      0      0
6   2008-08-31     Numancia    Barcelona   5  25      0      0      0      0
7   2008-08-31      Osasuna   Villarreal  10  12      0      0      0      0
8   2008-08-31    Santander      Sevilla   7  13      0      0      0      0
9   2008-08-31     Sp Gijon       Getafe  13  16      0      0      0      0
10  2008-09-13    Barcelona    Santander  18   2     25      7      5     13
11  2008-09-13   Valladolid   Ath Madrid   9  19     11     25     10      7
12  2008-09-14      Almeria     Valencia  12  11     11     17     10     16
13  2008-09-14       Getafe        Betis  26  16     16      8     13     13
14  2008-09-14       Malaga   Ath Bilbao  11  11      7     10     25     11
15  2008-09-14     Mallorca      Osasuna  11  14     16     10     17     12
16  2008-09-14  Real Madrid     Numancia  19  12     18      5     11     25
17  2008-09-14   Recreativo      Espanol   8   4     13     10      8     11
18  2008-09-14      Sevilla     Sp Gijon  26  13     13     13      7     16
19  2008-09-14   Villarreal    La Coruna  19   6     12     11     10     18
20  2008-09-20   Ath Madrid   Recreativo  14   9     44     21     16     12
21  2008-09-20      Espanol       Getafe   8  17     14     42     19     29
22  2008-09-21      Almeria       Malaga  11   3     23     18     21     36
23  2008-09-21   Ath Bilbao   Valladolid  20  12     21     20     22     29
24  2008-09-21        Betis      Sevilla  14  11     24     39     39     20
25  2008-09-21    La Coruna     Mallorca  17  14     17     27     37     31
26  2008-09-21     Numancia   Villarreal  14  20     17     31     44     16
27  2008-09-21    Santander  Real Madrid  13   9      9     37     31     23
28  2008-09-21     Sp Gijon    Barcelona   5  23     26     43     42      7
29  2008-09-21     Valencia      Osasuna  12   6     28     24     28     23
30  2008-09-24    Barcelona        Betis  18   8     66     38     12     50
31  2008-09-24       Getafe   Ath Madrid  18   9     59     58     37     25
32  2008-09-24      Osasuna    La Coruna  14   6     30     34     35     51
33  2008-09-24  Real Madrid     Sp Gijon  16  15     46     31     36     65
34  2008-09-24      Sevilla      Espanol  20   5     50     22     34     36
35  2008-09-24   Villarreal    Santander   7   6     51     22     30     40
36  2008-09-25       Malaga     Valencia   9  10     21     40     47     34
37  2008-09-25     Mallorca     Numancia  11  11     41     31     48     64
38  2008-09-25   Recreativo   Ath Bilbao  13  10     30     41     26     34
39  2008-09-25   Valladolid      Almeria  14   4     32     34     49     24
40  2008-09-27        Betis  Real Madrid  15  17     46     62     68     51
41  2008-09-27      Espanol    Barcelona   5  33     27     84     56     20
42  2008-09-27     Sp Gijon   Villarreal  15   8     46     58     81     36
43  2008-09-28      Almeria   Recreativo  10   5     38     43     38     36
44  2008-09-28   Ath Bilbao       Getafe  14   9     51     77     47     46
45  2008-09-28   Ath Madrid      Sevilla  18  10     67     70     43     39
46  2008-09-28       Malaga   Valladolid  12  15     30     46     57     53
47  2008-09-28     Numancia      Osasuna   4   8     42     44     75     41
48  2008-09-28    Santander     Mallorca  18  16     28     52     47     59
49  2008-09-28     Valencia    La Coruna  24   7     50     40     43     65

Team Shots on Taget

In [197]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_shots_fired_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSTF = playing_stat.iloc[i]['HST']
        # aggregated Home Team shots on Taget
        AGASTF = playing_stat.iloc[i]['AST']
        # aggregated Away Team shots on Taget
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired

# Gets the goals conceded agg on target arranged by teams and matchweek
def get_shots_conceded_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASTC = playing_stat.iloc[i]['HST']
        # aggregated home team shots conceded
        AGHSTC = playing_stat.iloc[i]['AST']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded

def get_sf_target(playing_stat):
    SFT = get_shots_fired_target(playing_stat)
    SCT = get_shots_conceded_target(playing_stat)
    
    j = 0
    AGHSTF = []
    AGASTF = []
    AGHSTC = []
    AGASTC = []  

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSTF.append(SFT.loc[ht][j])
        AGASTF.append(SFT.loc[at][j])
        AGHSTC.append(SCT.loc[ht][j])
        AGASTC.append(SCT.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHSTF'] = AGHSTF
    playing_stat['AGASTF'] = AGASTF
    playing_stat['AGHSTC'] = AGHSTC
    playing_stat['AGASTC'] = AGASTC
    
    return playing_stat

In [198]:
#playing_statistics_1 = get_sf_target(playing_statistics_1)
#playing_statistics_2 = get_sf_target(playing_statistics_2)
#playing_statistics_3 = get_sf_target(playing_statistics_3)
#playing_statistics_4 = get_sf_target(playing_statistics_4)
#playing_statistics_5 = get_sf_target(playing_statistics_5)
playing_statistics_6 = get_sf_target(playing_statistics_6)
playing_statistics_7 = get_sf_target(playing_statistics_7)
playing_statistics_8 = get_sf_target(playing_statistics_8)
playing_statistics_9 = get_sf_target(playing_statistics_9)
playing_statistics_10 = get_sf_target(playing_statistics_10)
playing_statistics_11 = get_sf_target(playing_statistics_11)
playing_statistics_12 = get_sf_target(playing_statistics_12)
playing_statistics_13 = get_sf_target(playing_statistics_13)
playing_statistics_14 = get_sf_target(playing_statistics_14)
playing_statistics_15 = get_sf_target(playing_statistics_15)
playing_statistics_16 = get_sf_target(playing_statistics_16)
playing_statistics_17 = get_sf_target(playing_statistics_17)
playing_statistics_18 = get_sf_target(playing_statistics_18)
playing_statistics_19 = get_sf_target(playing_statistics_19)
playing_statistics_20 = get_sf_target(playing_statistics_20)

<ipython-input-197-d1efa55e6e86>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTF'] = AGHSTF
<ipython-input-197-d1efa55e6e86>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTF'] = AGASTF
<ipython-input-197-d1efa55e6e86>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTC'] = AGHSTC
<ipython-input-197-d1efa55e6e86>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTC'] = AGASTC

In [199]:
playing_statistics_12[['Date', "HomeTeam", "AwayTeam", "HST", "AST",'AGHSTF', "AGASTF", "AGHSTC", "AGASTC"]].head(60)

,Date,HomeTeam,AwayTeam,HST,AST,AGHSTF,AGASTF,AGHSTC,AGASTC
0,2011-08-27,Granada,Betis,2,3,0,0,0,0
1,2011-08-27,Sp Gijon,Sociedad,4,2,0,0,0,0
2,2011-08-27,Valencia,Santander,11,3,0,0,0,0
3,2011-08-28,Ath Bilbao,Vallecano,4,6,0,0,0,0
4,2011-08-28,Ath Madrid,Osasuna,8,2,0,0,0,0
5,2011-08-28,Getafe,Levante,2,1,0,0,0,0
6,2011-08-28,Mallorca,Espanol,4,3,0,0,0,0
7,2011-08-28,Sevilla,Malaga,9,1,0,0,0,0
8,2011-08-28,Zaragoza,Real Madrid,1,16,0,0,0,0
9,2011-08-29,Barcelona,Villarreal,9,1,0,0,0,0
10,2011-09-10,Real Madrid,Getafe,10,6,16,2,1,1
11,2011-09-10,Sociedad,Barcelona,4,6,2,9,4,1
12,2011-09-10,Valencia,Ath Madrid,6,2,11,8,3,2
13,2011-09-10,Villarreal,Sevilla,5,5,1,9,9,1
14,2011-09-11,Betis,Mallorca,7,2,3,4,2,3
15,2011-09-11,Espanol,Ath Bilbao,6,7,3,4,4,6
16,2011-09-11,Osasuna,Sp Gijon,7,2,2,4,8,2
17,2011-09-11,Santander,Levante,1,2,3,1,11,2
18,2011-09-11,Vallecano,Zaragoza,5,1,6,1,4,16
19,2011-09-12,Malaga,Granada,9,4,1,2,9,3
20,2011-09-17,Barcelona,Osasuna,14,1,15,9,5,10
21,2011-09-17,Granada,Villarreal,2,4,6,6,12,14
22,2011-09-17,Mallorca,Malaga,1,4,6,10,10,13
23,2011-09-17,Sevilla,Sociedad,5,1,14,6,6,10
24,2011-09-17,Sp Gijon,Valencia,4,5,6,17,9,5
25,2011-09-18,Ath Bilbao,Betis,9,6,11,10,12,4
26,2011-09-18,Ath Madrid,Santander,7,0,10,4,8,13
27,2011-09-18,Getafe,Vallecano,2,4,8,11,11,5
28,2011-09-18,Levante,Real Madrid,4,3,3,26,3,7
29,2011-09-18,Zaragoza,Espanol,5,4,2,9,21,11
30,2011-09-20,Osasuna,Sevilla,8,5,10,19,24,7
31,2011-09-20,Sociedad,Granada,4,4,7,8,15,16
32,2011-09-20,Villarreal,Mallorca,9,3,10,7,16,14
33,2011-09-21,Ath Madrid,Sp Gijon,11,1,17,10,8,14
34,2011-09-21,Malaga,Ath Bilbao,4,3,14,20,14,18
35,2011-09-21,Santander,Real Madrid,2,2,4,29,20,11
36,2011-09-21,Valencia,Barcelona,1,7,22,29,9,6
37,2011-09-21,Vallecano,Levante,7,5,15,7,7,6
38,2011-09-22,Betis,Zaragoza,6,8,16,7,13,25
39,2011-09-22,Espanol,Getafe,6,0,13,10,16,15
40,2011-09-24,Ath Bilbao,Villarreal,6,3,23,19,22,19
41,2011-09-24,Barcelona,Ath Madrid,8,2,36,28,7,9
42,2011-09-24,Real Madrid,Vallecano,11,6,31,22,13,12
43,2011-09-24,Sevilla,Valencia,6,6,24,23,15,16
44,2011-09-25,Granada,Osasuna,2,6,12,18,20,29
45,2011-09-25,Levante,Espanol,5,6,12,19,13,16
46,2011-09-25,Mallorca,Sociedad,4,5,10,11,23,19
47,2011-09-25,Sp Gijon,Santander,1,3,11,6,25,22
48,2011-09-25,Zaragoza,Malaga,4,4,15,18,31,17
49,2011-09-26,Getafe,Betis,5,3,10,22,21,21
50,2011-10-01,Malaga,Getafe,8,2,22,15,21,24
51,2011-10-01,Osasuna,Mallorca,6,6,24,14,31,28
52,2011-10-01,Santander,Vallecano,4,5,9,28,23,23
53,2011-10-01,Valencia,Granada,11,5,29,14,22,26
54,2011-10-01,Villarreal,Zaragoza,12,9,22,19,25,35
55,2011-10-02,Ath Madrid,Sevilla,4,5,30,30,17,21
56,2011-10-02,Betis,Levante,4,3,25,17,26,19
57,2011-10-02,Espanol,Real Madrid,3,7,25,42,21,19
58,2011-10-02,Sociedad,Ath Bilbao,4,7,16,29,23,25
59,2011-10-02,Sp Gijon,Barcelona,1,4,12,44,28,9

Team Fouls Committed

In [200]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_fouls(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHF = playing_stat.iloc[i]['HF']
        # aggregated Home Team Fouls
        AGAF = playing_stat.iloc[i]['AF']
        # aggregated Away Team Fouls
        teams[playing_stat.iloc[i].HomeTeam].append(AGHF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Fouls = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Fouls[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Fouls[i] = Fouls[i] + Fouls[i-1]
    return Fouls


def get_fouls_agg(playing_stat):
    FA = get_fouls(playing_stat)
   
    j = 0
    AGHF = []
    AGAF = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHF.append(FA.loc[ht][j])
        AGAF.append(FA.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHF'] = AGHF
    playing_stat['AGAF'] = AGAF
    return playing_stat

In [201]:
#playing_statistics_1 = get_fouls_agg(playing_statistics_1)
#playing_statistics_2 = get_fouls_agg(playing_statistics_2)
#playing_statistics_3 = get_fouls_agg(playing_statistics_3)
#playing_statistics_4 = get_fouls_agg(playing_statistics_4)
#playing_statistics_5 = get_fouls_agg(playing_statistics_5)
playing_statistics_6 = get_fouls_agg(playing_statistics_6)
playing_statistics_7 = get_fouls_agg(playing_statistics_7)
playing_statistics_8 = get_fouls_agg(playing_statistics_8)
playing_statistics_9 = get_fouls_agg(playing_statistics_9)
playing_statistics_10 = get_fouls_agg(playing_statistics_10)
playing_statistics_11 = get_fouls_agg(playing_statistics_11)
playing_statistics_12 = get_fouls_agg(playing_statistics_12)
playing_statistics_13 = get_fouls_agg(playing_statistics_13)
playing_statistics_14 = get_fouls_agg(playing_statistics_14)
playing_statistics_15 = get_fouls_agg(playing_statistics_15)
playing_statistics_16 = get_fouls_agg(playing_statistics_16)
playing_statistics_17 = get_fouls_agg(playing_statistics_17)
playing_statistics_18 = get_fouls_agg(playing_statistics_18)
playing_statistics_19 = get_fouls_agg(playing_statistics_19)
playing_statistics_20 = get_fouls_agg(playing_statistics_20)

<ipython-input-200-b86ba37f240e>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHF'] = AGHF
<ipython-input-200-b86ba37f240e>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAF'] = AGAF

In [202]:
playing_statistics_7[['Date', "HomeTeam", "AwayTeam", "HF", "AF",'AGHF', "AGAF"]].head(60)

          Date     HomeTeam     AwayTeam  HF  AF  AGHF  AGAF
0   2006-08-26     Valencia        Betis  18  26     0     0
1   2006-08-27   Ath Bilbao     Sociedad  19  23     0     0
2   2006-08-27      Espanol    Gimnastic  25  27     0     0
3   2006-08-27    La Coruna     Zaragoza  22  19     0     0
4   2006-08-27      Osasuna       Getafe  26  22     0     0
5   2006-08-27  Real Madrid   Villarreal  22  18     0     0
6   2006-08-27   Recreativo     Mallorca  19  15     0     0
7   2006-08-27    Santander   Ath Madrid  25  25     0     0
8   2006-08-28        Celta    Barcelona  21  16     0     0
9   2006-08-29      Sevilla      Levante   1   3     0     0
10  2006-09-09   Ath Madrid     Valencia  24  23    25    18
11  2006-09-09    Barcelona      Osasuna   8  15    16    26
12  2006-09-10        Betis   Ath Bilbao  15  17    26    19
13  2006-09-10       Getafe    Santander  18  15    22    25
14  2006-09-10    Gimnastic        Celta  19  20    27    21
15  2006-09-10      Levante  Real Madrid  21  13     3    22
16  2006-09-10     Mallorca    La Coruna  19  24    15    22
17  2006-09-10     Sociedad      Sevilla   3   4    23     1
18  2006-09-10   Villarreal   Recreativo  17  14    18    19
19  2006-09-10     Zaragoza      Espanol  16  20    19    25
20  2006-09-16    La Coruna   Villarreal  23  24    46    35
21  2006-09-17   Ath Bilbao   Ath Madrid  12  11    36    49
22  2006-09-17      Espanol        Celta  21  14    45    41
23  2006-09-17      Osasuna    Gimnastic  13  26    41    46
24  2006-09-17  Real Madrid     Sociedad  18  22    35    26
25  2006-09-17   Recreativo      Levante  16  26    33    24
26  2006-09-17    Santander    Barcelona  31  14    40    24
27  2006-09-17      Sevilla        Betis   2   2     5    41
28  2006-09-17     Valencia       Getafe  17  17    41    40
29  2006-09-17     Zaragoza     Mallorca  22  20    35    34
30  2006-09-23        Betis  Real Madrid  17  24    43    53
31  2006-09-24   Ath Madrid      Sevilla   8   6    60     7
32  2006-09-24    Barcelona     Valencia  12  12    38    58
33  2006-09-24        Celta      Osasuna  15  17    55    54
34  2006-09-24       Getafe   Ath Bilbao  20  14    57    48
35  2006-09-24    Gimnastic    Santander  20  15    72    71
36  2006-09-24      Levante    La Coruna  21  25    50    69
37  2006-09-24     Mallorca      Espanol  21  24    54    66
38  2006-09-24     Sociedad   Recreativo  20  15    48    49
39  2006-09-24   Villarreal     Zaragoza  20  23    59    57
40  2006-09-30   Ath Bilbao    Barcelona   6  10    62    50
41  2006-10-01      Espanol      Osasuna  19  24    90    71
42  2006-10-01    La Coruna     Sociedad  18  29    94    68
43  2006-10-01     Mallorca   Villarreal  16  15    75    79
44  2006-10-01  Real Madrid   Ath Madrid  23  29    77    68
45  2006-10-01   Recreativo        Betis  15  15    64    60
46  2006-10-01    Santander        Celta  33  20    86    70
47  2006-10-01      Sevilla       Getafe  16  19    13    77
48  2006-10-01     Valencia    Gimnastic  15  16    70    92
49  2006-10-01     Zaragoza      Levante  12  21    80    71
50  2006-10-14   Ath Madrid   Recreativo  15  17    97    79
51  2006-10-14       Getafe  Real Madrid  22  20    96   100
52  2006-10-15    Barcelona      Sevilla   1   3    60    29
53  2006-10-15        Betis    La Coruna  17  12    75   112
54  2006-10-15        Celta     Valencia  18  15    90    85
55  2006-10-15    Gimnastic   Ath Bilbao  19  14   108    68
56  2006-10-15      Levante     Mallorca  28  13    92    91
57  2006-10-15      Osasuna    Santander  19  13    95   119
58  2006-10-15     Sociedad     Zaragoza  21  11    97    92
59  2006-10-15   Villarreal      Espanol  17  18    94   109

Team Corners

In [203]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_corners_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHCF = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGACF = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners

def get_corners_conceived(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGACC = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGHCC = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACC)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners


def get_corners_agg(playing_stat):
    CF = get_corners_fired(playing_stat)
    CC = get_corners_conceived(playing_stat)
   
    j = 0
    AGHCF = []
    AGACF = []
    AGHCC = []
    AGACC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHCF.append(CF.loc[ht][j])
        AGACF.append(CF.loc[at][j])
        AGHCC.append(CC.loc[ht][j])
        AGACC.append(CC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHCF'] = AGHCF
    playing_stat['AGACF'] = AGACF
    playing_stat['AGHCC'] = AGHCC
    playing_stat['AGACC'] = AGACC
    
    return playing_stat

In [204]:
#playing_statistics_1 = get_corners_agg(playing_statistics_1)
#playing_statistics_2 = get_corners_agg(playing_statistics_2)
#playing_statistics_3 = get_corners_agg(playing_statistics_3)
#playing_statistics_4 = get_corners_agg(playing_statistics_4)
#playing_statistics_5 = get_corners_agg(playing_statistics_5)
playing_statistics_6 = get_corners_agg(playing_statistics_6)
playing_statistics_7 = get_corners_agg(playing_statistics_7)
playing_statistics_8 = get_corners_agg(playing_statistics_8)
playing_statistics_9 = get_corners_agg(playing_statistics_9)
playing_statistics_10 = get_corners_agg(playing_statistics_10)
playing_statistics_11 = get_corners_agg(playing_statistics_11)
playing_statistics_12 = get_corners_agg(playing_statistics_12)
playing_statistics_13 = get_corners_agg(playing_statistics_13)
playing_statistics_14 = get_corners_agg(playing_statistics_14)
playing_statistics_15 = get_corners_agg(playing_statistics_15)
playing_statistics_16 = get_corners_agg(playing_statistics_16)
playing_statistics_17 = get_corners_agg(playing_statistics_17)
playing_statistics_18 = get_corners_agg(playing_statistics_18)
playing_statistics_19 = get_corners_agg(playing_statistics_19)
playing_statistics_20 = get_corners_agg(playing_statistics_20)

<ipython-input-203-8a4066657f67>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCF'] = AGHCF
<ipython-input-203-8a4066657f67>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACF'] = AGACF
<ipython-input-203-8a4066657f67>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCC'] = AGHCC
<ipython-input-203-8a4066657f67>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACC'] = AGACC

In [205]:
playing_statistics_12[['Date', "HomeTeam", "AwayTeam", "HC", "AC",'AGHCF', "AGACF", "AGHCC", "AGACC"]].head(50)

          Date     HomeTeam     AwayTeam  HC  AC  AGHCF  AGACF  AGHCC  AGACC
0   2011-08-27      Granada        Betis   8   5      0      0      0      0
1   2011-08-27     Sp Gijon     Sociedad   9   2      0      0      0      0
2   2011-08-27     Valencia    Santander  10   3      0      0      0      0
3   2011-08-28   Ath Bilbao    Vallecano   9   4      0      0      0      0
4   2011-08-28   Ath Madrid      Osasuna  12   5      0      0      0      0
5   2011-08-28       Getafe      Levante   1   4      0      0      0      0
6   2011-08-28     Mallorca      Espanol   5   4      0      0      0      0
7   2011-08-28      Sevilla       Malaga   2   8      0      0      0      0
8   2011-08-28     Zaragoza  Real Madrid   7   9      0      0      0      0
9   2011-08-29    Barcelona   Villarreal  12   0      0      0      0      0
10  2011-09-10  Real Madrid       Getafe   4   6      9      1      7      4
11  2011-09-10     Sociedad    Barcelona   5   4      2     12      9      0
12  2011-09-10     Valencia   Ath Madrid   3   7     10     12      3      5
13  2011-09-10   Villarreal      Sevilla   2   1      0      2     12      8
14  2011-09-11        Betis     Mallorca   7   5      5      5      8      4
15  2011-09-11      Espanol   Ath Bilbao   2   3      4      9      5      4
16  2011-09-11      Osasuna     Sp Gijon   6   8      5      9     12      2
17  2011-09-11    Santander      Levante   3   4      3      4     10      1
18  2011-09-11    Vallecano     Zaragoza   3   1      4      7      9      9
19  2011-09-12       Malaga      Granada   4   3      8      8      2      5
20  2011-09-17    Barcelona      Osasuna   8   3     16     11      5     20
21  2011-09-17      Granada   Villarreal   0   7     11      2      9     13
22  2011-09-17     Mallorca       Malaga   4   8     10     12     11      5
23  2011-09-17      Sevilla     Sociedad   8   1      3      7     10     13
24  2011-09-17     Sp Gijon     Valencia   6   6     17     13      8     10
25  2011-09-18   Ath Bilbao        Betis  10   1     12     12      6     13
26  2011-09-18   Ath Madrid    Santander   5   4     19      6      8     14
27  2011-09-18       Getafe    Vallecano   5   8      7      7      8     10
28  2011-09-18      Levante  Real Madrid   3   6      8     13      4     13
29  2011-09-18     Zaragoza      Espanol   3   4      8      6     12      8
30  2011-09-20      Osasuna      Sevilla   5   3     14     11     28     11
31  2011-09-20     Sociedad      Granada   5   4      8     11     21     16
32  2011-09-20   Villarreal     Mallorca   3   2      9     14     13     19
33  2011-09-21   Ath Madrid     Sp Gijon  11   2     24     23     12     14
34  2011-09-21       Malaga   Ath Bilbao   6   6     20     22      9      7
35  2011-09-21    Santander  Real Madrid   2  10     10     19     19     16
36  2011-09-21     Valencia    Barcelona   4   3     19     24     16      8
37  2011-09-21    Vallecano      Levante   7   5     15     11     15     10
38  2011-09-22        Betis     Zaragoza   2  10     13     11     23     16
39  2011-09-22      Espanol       Getafe  10   0     10     12     11     16
40  2011-09-24   Ath Bilbao   Villarreal   8   4     28     12     13     15
41  2011-09-24    Barcelona   Ath Madrid   8   1     27     35     12     14
42  2011-09-24  Real Madrid    Vallecano   7   6     29     22     18     20
43  2011-09-24      Sevilla     Valencia   4   8     14     23     16     19
44  2011-09-25      Granada      Osasuna   4   6     15     19     21     31
45  2011-09-25      Levante      Espanol   7   8     16     20     17     11
46  2011-09-25     Mallorca     Sociedad   6   1     16     13     22     25
47  2011-09-25     Sp Gijon    Santander   3   5     25     12     25     29
48  2011-09-25     Zaragoza       Malaga   3   7     21     26     18     15
49  2011-09-26       Getafe        Betis   2   4     12     15     26     33

Yellow Cards

In [206]:
# Gets yellow cards agg arranged by teams and matchweek
def get_yellow(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHY = playing_stat.iloc[i]['HY']
        # aggregated Home Team yellow cards
        AGAY = playing_stat.iloc[i]['AY']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHY)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAY)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Yellow = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Yellow[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Yellow[i] = Yellow[i] + Yellow[i-1]
    return Yellow


def get_yellow_agg(playing_stat):
    Y = get_yellow(playing_stat)
   
    j = 0
    AGHY = []
    AGAY = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHY.append(Y.loc[ht][j])
        AGAY.append(Y.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHY'] = AGHY
    playing_stat['AGAY'] = AGAY
    return playing_stat

In [207]:
#playing_statistics_1 = get_yellow_agg(playing_statistics_1)
#playing_statistics_2 = get_yellow_agg(playing_statistics_2)
#playing_statistics_3 = get_yellow_agg(playing_statistics_3)
#playing_statistics_4 = get_yellow_agg(playing_statistics_4)
#playing_statistics_5 = get_yellow_agg(playing_statistics_5)
playing_statistics_6 = get_yellow_agg(playing_statistics_6)
playing_statistics_7 = get_yellow_agg(playing_statistics_7)
playing_statistics_8 = get_yellow_agg(playing_statistics_8)
playing_statistics_9 = get_yellow_agg(playing_statistics_9)
playing_statistics_10 = get_yellow_agg(playing_statistics_10)
playing_statistics_11 = get_yellow_agg(playing_statistics_11)
playing_statistics_12 = get_yellow_agg(playing_statistics_12)
playing_statistics_13 = get_yellow_agg(playing_statistics_13)
playing_statistics_14 = get_yellow_agg(playing_statistics_14)
playing_statistics_15 = get_yellow_agg(playing_statistics_15)
playing_statistics_16 = get_yellow_agg(playing_statistics_16)
playing_statistics_17 = get_yellow_agg(playing_statistics_17)
playing_statistics_18 = get_yellow_agg(playing_statistics_18)
playing_statistics_19 = get_yellow_agg(playing_statistics_19)
playing_statistics_20 = get_yellow_agg(playing_statistics_20)

<ipython-input-206-697b7ad671dc>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHY'] = AGHY
<ipython-input-206-697b7ad671dc>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAY'] = AGAY

In [208]:
playing_statistics_20[['Date', "HomeTeam", "AwayTeam", "HY", "AY",'AGHY', "AGAY"]].head(50)

          Date     HomeTeam     AwayTeam  HY  AY  AGHY  AGAY
0   2019-08-16   Ath Bilbao    Barcelona   1   1     0     0
1   2019-08-17        Celta  Real Madrid   5   2     0     0
2   2019-08-17     Valencia     Sociedad   4   4     0     0
3   2019-08-17     Mallorca        Eibar   2   3     0     0
4   2019-08-17      Leganes      Osasuna   1   4     0     0
5   2019-08-17   Villarreal      Granada   3   1     0     0
6   2019-08-18       Alaves      Levante   2   1     0     0
7   2019-08-18      Espanol      Sevilla   2   2     0     0
8   2019-08-18        Betis   Valladolid   2   6     0     0
9   2019-08-18   Ath Madrid       Getafe   3   4     0     0
10  2019-08-23      Granada      Sevilla   1   1     1     2
11  2019-08-23      Levante   Villarreal   1   2     1     3
12  2019-08-24      Osasuna        Eibar   4   4     4     3
13  2019-08-24  Real Madrid   Valladolid   2   2     2     6
14  2019-08-24        Celta     Valencia   1   2     5     4
15  2019-08-24       Getafe   Ath Bilbao   2   1     4     1
16  2019-08-25       Alaves      Espanol   3   1     2     2
17  2019-08-25     Mallorca     Sociedad   1   2     2     4
18  2019-08-25      Leganes   Ath Madrid   4   5     1     3
19  2019-08-25    Barcelona        Betis   1   1     1     2
20  2019-08-30      Sevilla        Celta   4   2     3     6
21  2019-08-30   Ath Bilbao     Sociedad   2   3     2     6
22  2019-08-31      Osasuna    Barcelona   3   4     8     2
23  2019-08-31       Getafe       Alaves   3   1     6     5
24  2019-08-31      Levante   Valladolid   2   2     2     8
25  2019-08-31        Betis      Leganes   4   2     3     5
26  2019-09-01     Valencia     Mallorca   0   1     6     3
27  2019-09-01   Ath Madrid        Eibar   0   3     8     7
28  2019-09-01      Espanol      Granada   2   3     3     2
29  2019-09-01   Villarreal  Real Madrid   1   4     5     4
30  2019-09-13     Mallorca   Ath Bilbao   4   3     4     4
31  2019-09-14  Real Madrid      Levante   2   2     8     4
32  2019-09-14      Leganes   Villarreal   2   0     7     6
33  2019-09-14     Sociedad   Ath Madrid   1   3     9     8
34  2019-09-14    Barcelona     Valencia   1   4     6     6
35  2019-09-15        Eibar      Espanol   2   4    10     5
36  2019-09-15       Alaves      Sevilla   5   5     6     7
37  2019-09-15        Celta      Granada   4   2     8     5
38  2019-09-15   Valladolid      Osasuna   0   1    10    11
39  2019-09-15        Betis       Getafe   3   6     7     9
40  2019-09-20      Osasuna        Betis   1   2    12    10
41  2019-09-21   Villarreal   Valladolid   2   1     6    10
42  2019-09-21      Levante        Eibar   0   2     6    12
43  2019-09-21   Ath Madrid        Celta   3   5    11    12
44  2019-09-21      Granada    Barcelona   3   2     7     7
45  2019-09-22       Getafe     Mallorca   4   5    15     8
46  2019-09-22      Espanol     Sociedad   1   0     9    10
47  2019-09-22     Valencia      Leganes   3   4    10     9
48  2019-09-22   Ath Bilbao       Alaves   1   4     7    11
49  2019-09-22      Sevilla  Real Madrid   3   2    12    10

Red cards

In [209]:
# Gets red cards agg arranged by teams and matchweek
def get_red(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHR = playing_stat.iloc[i]['HR']
        # aggregated Home Team yellow cards
        AGAR = playing_stat.iloc[i]['AR']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHR)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAR)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Red = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Red[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Red[i] = Red[i] + Red[i-1]
    return Red


def get_red_agg(playing_stat):
    R = get_red(playing_stat)
   
    j = 0
    AGHR = []
    AGAR = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHR.append(R.loc[ht][j])
        AGAR.append(R.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHR'] = AGHR
    playing_stat['AGAR'] = AGAR
    return playing_stat

In [210]:
#playing_statistics_1 = get_red_agg(playing_statistics_1)
#playing_statistics_2 = get_red_agg(playing_statistics_2)
#playing_statistics_3 = get_red_agg(playing_statistics_3)
#playing_statistics_4 = get_red_agg(playing_statistics_4)
#playing_statistics_5 = get_red_agg(playing_statistics_5)
playing_statistics_6 = get_red_agg(playing_statistics_6)
playing_statistics_7 = get_red_agg(playing_statistics_7)
playing_statistics_8 = get_red_agg(playing_statistics_8)
playing_statistics_9 = get_red_agg(playing_statistics_9)
playing_statistics_10 = get_red_agg(playing_statistics_10)
playing_statistics_11 = get_red_agg(playing_statistics_11)
playing_statistics_12 = get_red_agg(playing_statistics_12)
playing_statistics_13 = get_red_agg(playing_statistics_13)
playing_statistics_14 = get_red_agg(playing_statistics_14)
playing_statistics_15 = get_red_agg(playing_statistics_15)
playing_statistics_16 = get_red_agg(playing_statistics_16)
playing_statistics_17 = get_red_agg(playing_statistics_17)
playing_statistics_18 = get_red_agg(playing_statistics_18)
playing_statistics_19 = get_red_agg(playing_statistics_19)
playing_statistics_20 = get_red_agg(playing_statistics_20)

<ipython-input-209-e098fe44355b>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHR'] = AGHR
<ipython-input-209-e098fe44355b>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAR'] = AGAR

In [211]:
playing_statistics_18[['Date', "HomeTeam", "AwayTeam", "HR", "AR",'AGHR', "AGAR"]].head(60)

          Date     HomeTeam     AwayTeam  HR  AR  AGHR  AGAR
0   2017-08-18      Leganes       Alaves   0   0     0     0
1   2017-08-18     Valencia   Las Palmas   0   1     0     0
2   2017-08-19        Celta     Sociedad   0   0     0     0
3   2017-08-19       Girona   Ath Madrid   0   1     0     0
4   2017-08-19      Sevilla      Espanol   1   0     0     0
5   2017-08-20   Ath Bilbao       Getafe   0   1     0     0
6   2017-08-20    Barcelona        Betis   0   0     0     0
7   2017-08-20    La Coruna  Real Madrid   0   1     0     0
8   2017-08-21      Levante   Villarreal   0   0     0     0
9   2017-08-21       Malaga        Eibar   0   0     0     0
10  2017-08-25        Betis        Celta   0   0     0     0
11  2017-08-25     Sociedad   Villarreal   0   0     0     0
12  2017-08-26       Alaves    Barcelona   0   0     0     0
13  2017-08-26       Girona       Malaga   0   0     0     0
14  2017-08-26   Las Palmas   Ath Madrid   0   0     1     1
15  2017-08-26      Levante    La Coruna   1   0     0     0
16  2017-08-27        Eibar   Ath Bilbao   1   0     0     0
17  2017-08-27      Espanol      Leganes   0   0     0     0
18  2017-08-27       Getafe      Sevilla   0   0     1     1
19  2017-08-27  Real Madrid     Valencia   0   0     1     0
20  2017-09-08      Leganes       Getafe   0   0     0     1
21  2017-09-09    Barcelona      Espanol   0   0     0     0
22  2017-09-09  Real Madrid      Levante   1   0     1     1
23  2017-09-09      Sevilla        Eibar   0   0     1     1
24  2017-09-09     Valencia   Ath Madrid   0   0     0     1
25  2017-09-10   Ath Bilbao       Girona   0   0     0     0
26  2017-09-10        Celta       Alaves   0   0     0     0
27  2017-09-10    La Coruna     Sociedad   0   0     0     0
28  2017-09-10   Villarreal        Betis   0   0     0     0
29  2017-09-11       Malaga   Las Palmas   0   0     0     1
30  2017-09-15        Eibar      Leganes   0   0     1     0
31  2017-09-16   Ath Madrid       Malaga   0   0     1     0
32  2017-09-16        Betis    La Coruna   0   0     0     0
33  2017-09-16       Getafe    Barcelona   0   0     1     0
34  2017-09-16      Levante     Valencia   0   0     1     0
35  2017-09-17       Alaves   Villarreal   0   0     0     0
36  2017-09-17       Girona      Sevilla   0   0     0     1
37  2017-09-17   Las Palmas   Ath Bilbao   0   0     1     0
38  2017-09-17     Sociedad  Real Madrid   0   0     0     2
39  2017-09-18      Espanol        Celta   0   0     0     0
40  2017-09-19    Barcelona        Eibar   0   0     0     1
41  2017-09-19     Valencia       Malaga   0   0     0     0
42  2017-09-20   Ath Bilbao   Ath Madrid   0   0     0     1
43  2017-09-20    La Coruna       Alaves   0   0     0     0
44  2017-09-20      Leganes       Girona   0   0     0     0
45  2017-09-20  Real Madrid        Betis   0   0     2     0
46  2017-09-20      Sevilla   Las Palmas   0   0     1     1
47  2017-09-21        Celta       Getafe   0   0     0     1
48  2017-09-21      Levante     Sociedad   0   1     1     0
49  2017-09-21   Villarreal      Espanol   0   0     0     0
50  2017-09-23       Alaves  Real Madrid   0   0     0     2
51  2017-09-23   Ath Madrid      Sevilla   0   0     1     1
52  2017-09-23       Girona    Barcelona   0   0     0     0
53  2017-09-23       Malaga   Ath Bilbao   1   0     0     0
54  2017-09-24        Eibar        Celta   0   0     1     0
55  2017-09-24      Espanol    La Coruna   0   0     0     0
56  2017-09-24       Getafe   Villarreal   0   0     1     0
57  2017-09-24   Las Palmas      Leganes   0   0     1     0
58  2017-09-24     Sociedad     Valencia   1   1     1     0
59  2017-09-25        Betis      Levante   0   0     0     1

GET RESPECTIVE POINTS: 
-> 18 mit 20 ersetzen: number of teams

In [212]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0
    

def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,39):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(20)])
    return matchres_points


def get_matchres(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
            
    return pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []
    j = 0
    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

        if ((i + 1)% 10) == 0:
            j = j + 1
            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat

In [213]:
# Apply to each dataset

#playing_statistics_1 = get_agg_points(playing_statistics_1)
#playing_statistics_2 = get_agg_points(playing_statistics_2)
#playing_statistics_3 = get_agg_points(playing_statistics_3)
#playing_statistics_4 = get_agg_points(playing_statistics_4)
#playing_statistics_5 = get_agg_points(playing_statistics_5)
playing_statistics_6 = get_agg_points(playing_statistics_6)
playing_statistics_7 = get_agg_points(playing_statistics_7)
playing_statistics_8 = get_agg_points(playing_statistics_8)
playing_statistics_9 = get_agg_points(playing_statistics_9)
playing_statistics_10 = get_agg_points(playing_statistics_10)
playing_statistics_11 = get_agg_points(playing_statistics_11)
playing_statistics_12 = get_agg_points(playing_statistics_12)
playing_statistics_13 = get_agg_points(playing_statistics_13)
playing_statistics_14 = get_agg_points(playing_statistics_14)
playing_statistics_15 = get_agg_points(playing_statistics_15)
playing_statistics_16 = get_agg_points(playing_statistics_16)
playing_statistics_17 = get_agg_points(playing_statistics_17)
playing_statistics_18 = get_agg_points(playing_statistics_18)
playing_statistics_19 = get_agg_points(playing_statistics_19)
playing_statistics_20 = get_agg_points(playing_statistics_20)

<ipython-input-212-cae68c17b88e>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTP'] = HTP
<ipython-input-212-cae68c17b88e>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATP'] = ATP

In [214]:
playing_statistics_13[['Date', "HomeTeam", "AwayTeam", "FTHG", "FTAG","HTP", "ATP"]].head(60)

          Date     HomeTeam     AwayTeam  FTHG  FTAG  HTP  ATP
0   2012-08-18        Celta       Malaga     0     1    0    0
1   2012-08-18     Mallorca      Espanol     2     1    0    0
2   2012-08-18      Sevilla       Getafe     2     1    0    0
3   2012-08-19   Ath Bilbao        Betis     3     5    0    0
4   2012-08-19    Barcelona     Sociedad     5     1    0    0
5   2012-08-19      Levante   Ath Madrid     1     1    0    0
6   2012-08-19  Real Madrid     Valencia     1     1    0    0
7   2012-08-20    La Coruna      Osasuna     2     0    0    0
8   2012-08-20    Vallecano      Granada     1     0    0    0
9   2012-08-20     Zaragoza   Valladolid     0     1    0    0
10  2012-08-25        Betis    Vallecano     1     2    3    3
11  2012-08-25      Espanol     Zaragoza     1     2    0    0
12  2012-08-25       Malaga     Mallorca     1     1    3    3
13  2012-08-25     Sociedad        Celta     2     1    0    0
14  2012-08-26       Getafe  Real Madrid     2     1    0    1
15  2012-08-26      Granada      Sevilla     1     1    0    3
16  2012-08-26      Osasuna    Barcelona     1     2    0    3
17  2012-08-26     Valencia    La Coruna     3     3    1    3
18  2012-08-27   Ath Madrid   Ath Bilbao     4     0    1    0
19  2012-08-27   Valladolid      Levante     2     0    3    1
20  2012-09-01        Celta      Osasuna     2     0    0    0
21  2012-09-01    La Coruna       Getafe     1     1    4    3
22  2012-09-01     Mallorca     Sociedad     1     0    4    3
23  2012-09-01     Zaragoza       Malaga     0     1    3    4
24  2012-09-02   Ath Bilbao   Valladolid     2     0    0    6
25  2012-09-02    Barcelona     Valencia     1     0    6    2
26  2012-09-02      Levante      Espanol     3     2    1    0
27  2012-09-02  Real Madrid      Granada     3     0    1    1
28  2012-09-02    Vallecano      Sevilla     0     0    6    4
29  2012-09-15       Getafe    Barcelona     1     4    3    6
30  2012-09-15       Malaga      Levante     3     1    7    4
31  2012-09-15      Sevilla  Real Madrid     1     0    5    4
32  2012-09-15     Valencia        Celta     2     1    2    3
33  2012-09-16   Ath Madrid    Vallecano     4     3    7    7
34  2012-09-16      Espanol   Ath Bilbao     3     3    0    3
35  2012-09-16      Granada    La Coruna     1     1    1    5
36  2012-09-16      Osasuna     Mallorca     1     1    0    7
37  2012-09-16     Sociedad     Zaragoza     2     0    3    3
38  2012-09-17   Valladolid        Betis     0     1    6    6
39  2012-09-22    Barcelona      Granada     2     0    9    1
40  2012-09-22        Betis      Espanol     1     0    9    1
41  2012-09-22        Celta       Getafe     2     1    3    4
42  2012-09-22     Zaragoza      Osasuna     3     1    3    1
43  2012-09-23   Ath Bilbao       Malaga     0     0    4   10
44  2012-09-23   Ath Madrid   Valladolid     2     1   10    6
45  2012-09-23      Levante     Sociedad     2     1    4    6
46  2012-09-23     Mallorca     Valencia     2     0    8    5
47  2012-09-24    La Coruna      Sevilla     0     2    6    8
48  2012-09-24    Vallecano  Real Madrid     0     2    7    4
49  2012-09-26        Betis   Ath Madrid     2     4    9   10
50  2012-09-29       Malaga        Betis     4     0   11    9
51  2012-09-29      Sevilla    Barcelona     2     3   11   15
52  2012-09-29     Sociedad   Ath Bilbao     2     0    6    5
53  2012-09-29     Valencia     Zaragoza     2     0    5    6
54  2012-09-30      Espanol   Ath Madrid     0     1    1   13
55  2012-09-30      Granada        Celta     2     1    2    6
56  2012-09-30      Osasuna      Levante     4     0    1    7
57  2012-09-30  Real Madrid    La Coruna     5     1    7    6
58  2012-09-30   Valladolid    Vallecano     6     1    6    7
59  2012-10-01       Getafe     Mallorca     1     0    4   11

GET TEAM FORM: 
-> 9 mit 10 ersetzen!

In [215]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,39):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 10)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 10)]
    
    j = num
    for i in range((num*10),380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 10) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat


def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [216]:
# Make changes to df
#playing_statistics_1 = add_form_df(playing_statistics_1)
#playing_statistics_2 = add_form_df(playing_statistics_2)
#playing_statistics_3 = add_form_df(playing_statistics_3)
#playing_statistics_4 = add_form_df(playing_statistics_4)
#playing_statistics_5 = add_form_df(playing_statistics_5)
playing_statistics_6 = add_form_df(playing_statistics_6)
playing_statistics_7 = add_form_df(playing_statistics_7)
playing_statistics_8 = add_form_df(playing_statistics_8)
playing_statistics_9 = add_form_df(playing_statistics_9)
playing_statistics_10 = add_form_df(playing_statistics_10)
playing_statistics_11 = add_form_df(playing_statistics_11)
playing_statistics_12 = add_form_df(playing_statistics_12)
playing_statistics_13 = add_form_df(playing_statistics_13)
playing_statistics_14 = add_form_df(playing_statistics_14)
playing_statistics_15 = add_form_df(playing_statistics_15)
playing_statistics_16 = add_form_df(playing_statistics_16)
playing_statistics_17 = add_form_df(playing_statistics_17)
playing_statistics_18 = add_form_df(playing_statistics_18)
playing_statistics_19 = add_form_df(playing_statistics_19)
playing_statistics_20 = add_form_df(playing_statistics_20)

<ipython-input-215-7790a7af0e3e>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HM' + str(num)] = h
<ipython-input-215-7790a7af0e3e>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AM' + str(num)] = a

Get MatchWeek:

In [217]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(380):
        MatchWeek.append(j)
        if ((i + 1)% 10) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

In [218]:
#playing_statistics_1 = get_mw(playing_statistics_1)
#playing_statistics_2 = get_mw(playing_statistics_2)
#playing_statistics_3 = get_mw(playing_statistics_3)
#playing_statistics_4 = get_mw(playing_statistics_4)
#playing_statistics_5 = get_mw(playing_statistics_5)
playing_statistics_6 = get_mw(playing_statistics_6)
playing_statistics_7 = get_mw(playing_statistics_7)
playing_statistics_8 = get_mw(playing_statistics_8)
playing_statistics_9 = get_mw(playing_statistics_9)
playing_statistics_10 = get_mw(playing_statistics_10)
playing_statistics_11 = get_mw(playing_statistics_11)
playing_statistics_12 = get_mw(playing_statistics_12)
playing_statistics_13 = get_mw(playing_statistics_13)
playing_statistics_14 = get_mw(playing_statistics_14)
playing_statistics_15 = get_mw(playing_statistics_15)
playing_statistics_16 = get_mw(playing_statistics_16)
playing_statistics_17 = get_mw(playing_statistics_17)
playing_statistics_18 = get_mw(playing_statistics_18)
playing_statistics_19 = get_mw(playing_statistics_19)
playing_statistics_20 = get_mw(playing_statistics_20)

<ipython-input-217-4940c39006da>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['MW'] = MatchWeek

In [219]:
playing_statistics_14

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2013-08-17,Sociedad,Getafe,2,0,H,16,15,6,2,...,M,M,M,M,M,M,M,M,M,1
1,2013-08-17,Valencia,Malaga,1,0,H,9,11,1,2,...,M,M,M,M,M,M,M,M,M,1
2,2013-08-17,Valladolid,Ath Bilbao,1,2,A,8,13,2,3,...,M,M,M,M,M,M,M,M,M,1
3,2013-08-18,Barcelona,Levante,7,0,H,22,4,13,1,...,M,M,M,M,M,M,M,M,M,1
4,2013-08-18,Osasuna,Granada,1,2,A,14,13,5,4,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2014-05-18,Osasuna,Betis,2,1,H,14,16,3,8,...,W,L,L,L,L,D,L,D,L,38
376,2014-05-18,Sevilla,Elche,3,1,H,15,14,5,4,...,D,D,W,L,D,W,L,W,L,38
377,2014-05-18,Sociedad,Villarreal,1,2,A,13,15,3,5,...,W,D,D,W,L,W,L,D,W,38
378,2014-05-18,Valladolid,Granada,0,1,A,10,6,4,3,...,L,D,D,W,L,L,L,D,W,38
379,2014-05-18,Vallecano,Getafe,1,2,A,16,15,4,4,...,W,L,D,W,W,W,D,D,L,38

FINAL DATAFRAME

In [220]:
playing_stat = pd.concat([#playing_statistics_1,
                          #playing_statistics_2,
                          #playing_statistics_3,
                          #playing_statistics_4,
                          #playing_statistics_5,
                          playing_statistics_6,
                          playing_statistics_7,
                          playing_statistics_8,
                          playing_statistics_9,
                          playing_statistics_10,
                          playing_statistics_11,
                          playing_statistics_12,
                          playing_statistics_13,
                          playing_statistics_14,
                          playing_statistics_15,
                          playing_statistics_16,
                          playing_statistics_17,
                          playing_statistics_18,
                          playing_statistics_19,
                          playing_statistics_20,], ignore_index=True)

In [221]:
playing_stat

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2005-08-27,Alaves,Barcelona,0,0,D,5,17,0,10,...,M,M,M,M,M,M,M,M,M,1
1,2005-08-27,Ath Bilbao,Sociedad,3,0,H,10,9,6,2,...,M,M,M,M,M,M,M,M,M,1
2,2005-08-27,Valencia,Betis,1,0,H,9,14,2,3,...,M,M,M,M,M,M,M,M,M,1
3,2005-08-28,Ath Madrid,Zaragoza,0,0,D,16,9,5,2,...,M,M,M,M,M,M,M,M,M,1
4,2005-08-28,Cadiz,Real Madrid,1,2,A,15,17,5,6,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,2020-07-19,Granada,Ath Bilbao,4,0,H,11,11,6,3,...,L,L,W,W,L,D,L,W,W,38
5696,2020-07-19,Leganes,Real Madrid,2,2,D,15,7,7,4,...,W,W,W,D,W,W,W,L,W,38
5697,2020-07-19,Levante,Getafe,1,0,H,13,13,4,4,...,L,L,D,L,L,D,D,D,L,38
5698,2020-07-19,Osasuna,Mallorca,2,2,D,12,12,5,4,...,L,W,L,L,W,D,L,W,W,38
5699,2020-07-19,Sevilla,Valencia,1,0,H,16,8,4,2,...,W,W,L,W,W,W,D,W,L,38

In [222]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS',
       'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HTGS',
       'ATGS', 'HTGC', 'ATGC', 'AGHSF', 'AGASF', 'AGHSC', 'AGASC', 'AGHSTF',
       'AGASTF', 'AGHSTC', 'AGASTC', 'AGHF', 'AGAF', 'AGHCF', 'AGACF', 'AGHCC',
       'AGACC', 'AGHY', 'AGAY', 'AGHR', 'AGAR', 'HTP', 'ATP', 'HM1', 'AM1',
       'HM2', 'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5', 'MW',
       'HTFormPtsStr', 'ATFormPtsStr', 'HTFormPts', 'ATFormPts',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [223]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in Shots fired
playing_stat['HTSD'] = playing_stat['AGHSF'] - playing_stat['AGHSC']
playing_stat['ATSD'] = playing_stat['AGASF'] - playing_stat['AGASC']

# Diff in shots on target
playing_stat['HTSTD'] = playing_stat['AGHSTF'] - playing_stat['AGHSTC']
playing_stat['ATSTD'] = playing_stat['AGASTF'] - playing_stat['AGASTC']

# Diff in corners
playing_stat['HTCD'] = playing_stat['AGHCF'] - playing_stat['AGHCC']
playing_stat['ATCD'] = playing_stat['AGACF'] - playing_stat['AGACC']

In [224]:
# Datensatz nicht gescaled
#playing_stat_raw = playing_stat
#playing_stat_raw.to_csv(loc + "2019_2020_ingame_1und2_raw.csv")

In [225]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP', "HTSD", "ATSD", "HTSTD", "ATSTD", "HTCD", "ATCD",
        "AGHY", "AGHR", "AGAR", "AGHF", "AGAF", "AGAY", 'AGHSF','AGASF', 'AGHSC', 'AGASC', 'AGHSTF', 'AGASTF', 
        'AGHSTC', 'AGASTC', 'AGHCF', 'AGACF', 'AGHCC', 'AGACC']
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [226]:
playing_stat.MW

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
5695    38.0
5696    38.0
5697    38.0
5698    38.0
5699    38.0
Name: MW, Length: 5700, dtype: float64

In [227]:
playing_stat

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,HTGD,ATGD,DiffPts,DiffFormPts,HTSD,ATSD,HTSTD,ATSTD,HTCD,ATCD
0,2005-08-27,Alaves,Barcelona,0,0,D,5,17,0,10,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2005-08-27,Ath Bilbao,Sociedad,3,0,H,10,9,6,2,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2005-08-27,Valencia,Betis,1,0,H,9,14,2,3,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2005-08-28,Ath Madrid,Zaragoza,0,0,D,16,9,5,2,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2005-08-28,Cadiz,Real Madrid,1,2,A,15,17,5,6,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,2020-07-19,Granada,Ath Bilbao,4,0,H,11,11,6,3,...,0.078947,0.184211,0.052632,0.105263,-1.447368,0.578947,-0.789474,0.315789,-0.447368,0.105263
5696,2020-07-19,Leganes,Real Madrid,2,2,D,15,7,7,4,...,-0.552632,1.184211,-1.342105,-0.131579,1.921053,6.157895,0.157895,3.342105,0.026316,1.236842
5697,2020-07-19,Levante,Getafe,1,0,H,13,13,4,4,...,-0.184211,0.184211,-0.210526,0.078947,-3.947368,3.447368,-2.000000,0.500000,-0.736842,1.342105
5698,2020-07-19,Osasuna,Mallorca,2,2,D,12,12,5,4,...,-0.210526,-0.657895,0.500000,0.105263,0.921053,-2.000000,0.105263,-1.552632,0.157895,-0.210526
5699,2020-07-19,Sevilla,Valencia,1,0,H,16,8,4,2,...,0.500000,-0.157895,0.368421,0.157895,2.447368,-5.763158,1.289474,-1.815789,2.184211,-0.315789

In [228]:
playing_stat.to_csv(loc + "final_dataset_primera.csv")
# playing_stat_test.to_csv(loc+"test.csv")