In [237]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools

%matplotlib inline

In [238]:
# 20 Mannschaften * 19 = 380 Spiele pro Saison
# 2&3 Liga sogar 24!

In [239]:
# Read data from the CSV into a dataframe

# Python pandas will read a csv file using utf_8 encoding defautly. 
# If the character encoding of this csv file is not utf_8, UnicodeDecodeError may occur.

loc = "/home/max/Dokumente/Projekte/Football_Game_Prediction/Data_Gathering/Frankreich/Erste/"
#raw_data_1 = pd.read_csv(loc + '2000_2001.csv', sep=',', encoding='gbk')
#raw_data_2 = pd.read_csv(loc + '2001_2002.csv', sep=',', encoding='gbk')
#raw_data_3 = pd.read_csv(loc + '2002_2003.csv', sep=',', encoding='gbk') 
# raw_data_4 = pd.read_csv(loc + '2003_2004.csv')
# raw_data_5 = pd.read_csv(loc + '2004_2005.csv', sep=';', encoding='gbk')
# raw_data_6 = pd.read_csv(loc + '2005_2006.csv', sep=',', encoding='gbk') -> noch nicht alle game stats!
# raw_data_7 = pd.read_csv(loc + '2006_2007.csv', sep=',', encoding='gbk') -> noch nicht alle game stats!
raw_data_8 = pd.read_csv(loc + '2007_2008.csv', sep=',', encoding='gbk')
raw_data_9 = pd.read_csv(loc + '2008_2009.csv', sep=',', encoding='gbk')
raw_data_10 = pd.read_csv(loc + '2009_2010.csv', sep=',', encoding='gbk')
raw_data_11 = pd.read_csv(loc + '2010_2011.csv', sep=',', encoding='gbk')
raw_data_12 = pd.read_csv(loc + '2011_2012.csv', sep=',', encoding='gbk')
raw_data_13 = pd.read_csv(loc + '2012_2013.csv', sep=',', encoding='gbk')
raw_data_14 = pd.read_csv(loc + '2013_2014.csv', sep=',', encoding='gbk')
raw_data_15 = pd.read_csv(loc + '2014_2015.csv', sep=',', encoding='gbk')
raw_data_16 = pd.read_csv(loc + '2015_2016.csv', sep=',', encoding='gbk')
raw_data_17 = pd.read_csv(loc + '2016_2017.csv', sep=',', encoding='gbk')
raw_data_18 = pd.read_csv(loc + '2017_2018.csv', sep=',', encoding='gbk')
raw_data_19 = pd.read_csv(loc + '2018_2019.csv', sep=',', encoding='gbk')
#raw_data_20 = pd.read_csv(loc + '2019_2020.csv', sep=',', encoding='gbk')

In [240]:
raw_data_14.drop(raw_data_14.tail(1).index,inplace=True) # drop last n rows
raw_data_16.drop(raw_data_16.tail(1).index,inplace=True) # drop last n rows

In [241]:
raw_data_16

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,F1,07/08/15,Lille,Paris SG,0.0,1.0,A,0.0,0.0,D,...,1.63,25.0,0.75,2.11,2.03,1.85,1.80,7.58,3.91,1.58
1,F1,08/08/15,Bastia,Rennes,2.0,1.0,H,0.0,1.0,A,...,1.50,27.0,0.00,1.87,1.80,2.10,2.03,2.81,2.93,3.10
2,F1,08/08/15,Marseille,Caen,0.0,1.0,A,0.0,1.0,A,...,2.15,31.0,-1.00,2.00,1.92,1.95,1.90,1.57,4.13,7.04
3,F1,08/08/15,Montpellier,Angers,0.0,2.0,A,0.0,1.0,A,...,1.54,26.0,-0.50,1.84,1.78,2.13,2.06,1.84,3.42,5.42
4,F1,08/08/15,Nantes,Guingamp,1.0,0.0,H,0.0,0.0,D,...,1.44,25.0,-0.25,1.87,1.82,2.10,2.01,2.37,3.01,3.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,F1,14/05/16,Paris SG,Nantes,4.0,0.0,H,2.0,0.0,H,...,2.87,30.0,-1.75,2.06,1.98,1.90,1.85,1.21,7.85,15.31
376,F1,14/05/16,Reims,Lyon,4.0,1.0,H,2.0,0.0,H,...,2.41,28.0,0.50,1.85,1.81,2.10,2.05,3.91,4.19,1.90
377,F1,14/05/16,Rennes,Bastia,1.0,2.0,A,0.0,1.0,A,...,1.91,29.0,-0.50,1.90,1.86,2.05,1.98,1.85,3.80,4.64
378,F1,14/05/16,St Etienne,Lille,0.0,1.0,A,0.0,1.0,A,...,1.59,30.0,-0.25,2.11,2.04,1.85,1.81,2.70,3.23,2.94
379,F1,14/05/16,Troyes,Marseille,1.0,1.0,D,1.0,0.0,H,...,2.62,30.0,0.75,2.15,2.02,1.88,1.83,4.85,4.45,1.70

In [242]:
raw_data_18.Date

0      04/08/17
1      05/08/17
2      05/08/17
3      05/08/17
4      05/08/17
         ...
375    19/05/18
376    19/05/18
377    19/05/18
378    19/05/18
379    19/05/18
Name: Date, Length: 380, dtype: object

In [243]:
# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

# funktion brauche ich nicht: form nur für obigen zwei!
def parse_date_other_2(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%Y-%m-%d').date()

In [244]:
#raw_data_1.Date = raw_data_1.Date.apply(parse_date)    
#raw_data_2.Date = raw_data_2.Date.apply(parse_date)    
#raw_data_3.Date = raw_data_3.Date.apply(parse_date_other)          
# raw_data_4.Date = raw_data_4.Date.apply(parse_date)    
# raw_data_5.Date = raw_data_5.Date.apply(parse_date)    
#raw_data_6.Date = raw_data_6.Date.apply(parse_date)    
#raw_data_7.Date = raw_data_7.Date.apply(parse_date_other)    
raw_data_8.Date = raw_data_8.Date.apply(parse_date)    
raw_data_9.Date = raw_data_9.Date.apply(parse_date)    
raw_data_10.Date = raw_data_10.Date.apply(parse_date)
raw_data_11.Date = raw_data_11.Date.apply(parse_date)
raw_data_12.Date = raw_data_12.Date.apply(parse_date)
raw_data_13.Date = raw_data_13.Date.apply(parse_date)
raw_data_14.Date = raw_data_14.Date.apply(parse_date)
raw_data_15.Date = raw_data_15.Date.apply(parse_date)
raw_data_16.Date = raw_data_16.Date.apply(parse_date)
raw_data_17.Date = raw_data_17.Date.apply(parse_date)
raw_data_18.Date = raw_data_18.Date.apply(parse_date)
raw_data_19.Date = raw_data_19.Date.apply(parse_date_other)
#raw_data_20.Date = raw_data_20.Date.apply(parse_date_other)

In [245]:
#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR', "HS", "AS", "HST", "AST", "HC", 
                          "AC", "HF", "AF", "HY", "AY", "HR", "AR"]

#playing_statistics_1 = raw_data_1[columns_req]    
#playing_statistics_2 = raw_data_2[columns_req]   
#playing_statistics_3 = raw_data_3[columns_req]    
#playing_statistics_4 = raw_data_4[columns_req]   
#playing_statistics_5 = raw_data_5[columns_req]  
#playing_statistics_6 = raw_data_6[columns_req]    
#playing_statistics_7 = raw_data_7[columns_req]    
playing_statistics_8 = raw_data_8[columns_req] 
playing_statistics_9 = raw_data_9[columns_req]    
playing_statistics_10 = raw_data_10[columns_req]    
playing_statistics_11 = raw_data_12[columns_req]  
playing_statistics_12 = raw_data_12[columns_req]  
playing_statistics_13 = raw_data_13[columns_req]  
playing_statistics_14 = raw_data_14[columns_req] 
playing_statistics_15 = raw_data_15[columns_req]   
playing_statistics_16 = raw_data_16[columns_req]
playing_statistics_17 = raw_data_17[columns_req] 
playing_statistics_18 = raw_data_18[columns_req]  
playing_statistics_19 = raw_data_19[columns_req]  
# playing_statistics_20 = raw_data_20[columns_req]

In [246]:
playing_statistics_14

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR
0,2013-08-09,Montpellier,Paris SG,1.0,1.0,D,6.0,12.0,1.0,4.0,1.0,8.0,22.0,18.0,2.0,2.0,1.0,0.0
1,2013-08-10,Bordeaux,Monaco,0.0,2.0,A,11.0,13.0,2.0,6.0,3.0,7.0,16.0,11.0,1.0,0.0,0.0,0.0
2,2013-08-10,Evian Thonon Gaillard,Sochaux,1.0,1.0,D,15.0,9.0,8.0,6.0,5.0,5.0,13.0,18.0,1.0,2.0,0.0,0.0
3,2013-08-10,Lille,Lorient,1.0,0.0,H,6.0,6.0,3.0,3.0,4.0,3.0,18.0,18.0,1.0,1.0,0.0,1.0
4,2013-08-10,Lyon,Nice,4.0,0.0,H,12.0,11.0,6.0,5.0,2.0,5.0,20.0,9.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2014-05-17,Paris SG,Montpellier,4.0,0.0,H,18.0,15.0,12.0,1.0,2.0,8.0,12.0,6.0,0.0,1.0,0.0,0.0
376,2014-05-17,Reims,Rennes,1.0,3.0,A,16.0,14.0,4.0,3.0,7.0,6.0,9.0,6.0,0.0,1.0,0.0,0.0
377,2014-05-17,Sochaux,Evian Thonon Gaillard,0.0,3.0,A,20.0,9.0,5.0,6.0,7.0,2.0,7.0,21.0,2.0,1.0,0.0,0.0
378,2014-05-17,St Etienne,Ajaccio,3.0,1.0,H,14.0,8.0,8.0,3.0,2.0,3.0,12.0,19.0,0.0,0.0,0.0,0.0
379,2014-05-17,Toulouse,Valenciennes,3.0,1.0,H,9.0,15.0,4.0,5.0,6.0,4.0,11.0,11.0,1.0,2.0,0.0,0.0

** GOALS SCORED AND CONCEDED AT THE END OF MATCHWEEK, ARRANGED BY TEAMS AND MATCHWEEK **

Bundesliga sind 18 Teams => 18x17 sind 306 Spiele
Premier League: sind 20 Teams => 20x19 sind 380 Spiele
=> ändere if ((i + 1)% 9) == 0: zu if ((i + 1)% 10) == 0:

In [247]:
# alle 302 mit 380 ersetzen!
# Shape of passed values is (38, 20), indices imply (34, 20) => jede 39 mit 39 ersetzen!

# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored



# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [248]:
# Apply to each dataset

#playing_statistics_1 = get_gss(playing_statistics_1)
#playing_statistics_2 = get_gss(playing_statistics_2)
#playing_statistics_3 = get_gss(playing_statistics_3)
#playing_statistics_4 = get_gss(playing_statistics_4)
#playing_statistics_5 = get_gss(playing_statistics_5)
#playing_statistics_6 = get_gss(playing_statistics_6)
#playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)
playing_statistics_9 = get_gss(playing_statistics_9)
playing_statistics_10 = get_gss(playing_statistics_10)
playing_statistics_11 = get_gss(playing_statistics_11)
playing_statistics_12 = get_gss(playing_statistics_12)
playing_statistics_13 = get_gss(playing_statistics_13)
playing_statistics_14 = get_gss(playing_statistics_14)
playing_statistics_15 = get_gss(playing_statistics_15)
playing_statistics_16 = get_gss(playing_statistics_16)
playing_statistics_17 = get_gss(playing_statistics_17)
playing_statistics_18 = get_gss(playing_statistics_18)
playing_statistics_19 = get_gss(playing_statistics_19)
#playing_statistics_20 = get_gss(playing_statistics_20)

# danach immer kopieren und befehlt get_gss mit jeweiliger funktion für alle ersetzen! + loops verbessern!

<ipython-input-247-744d34d6ae2f>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGS'] = HTGS
<ipython-input-247-744d34d6ae2f>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGS'] = ATGS
<ipython-input-247-744d34d6ae2f>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTGC'] = HTGC
<ipython-input-247-744d34d6ae2f>:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATGC'] = ATGC

In [249]:
playing_statistics_8[['Date', "HomeTeam", "AwayTeam", "FTHG", "FTAG", "HTGS", "ATGS", "HTGC", "ATGC"]].head(60)

          Date      HomeTeam      AwayTeam  FTHG  FTAG  HTGS  ATGS  HTGC  ATGC
0   2007-08-04      Bordeaux          Lens     1     0     0     0     0     0
1   2007-08-04          Caen          Nice     1     0     0     0     0     0
2   2007-08-04         Lille       Lorient     0     0     0     0     0     0
3   2007-08-04        Monaco    St Etienne     1     1     0     0     0     0
4   2007-08-04      Paris SG       Sochaux     0     0     0     0     0     0
5   2007-08-04        Rennes         Nancy     0     2     0     0     0     0
6   2007-08-04    Strasbourg     Marseille     0     0     0     0     0     0
7   2007-08-04  Valenciennes      Toulouse     3     1     0     0     0     0
8   2007-08-05       Le Mans          Metz     1     0     0     0     0     0
9   2007-08-05          Lyon       Auxerre     2     0     0     0     0     0
10  2007-08-11       Auxerre      Bordeaux     0     2     0     1     2     0
11  2007-08-11       Lorient        Monaco     2     1     0     1     0     1
12  2007-08-11     Marseille        Rennes     0     0     0     0     0     2
13  2007-08-11         Nancy          Caen     1     0     2     1     0     0
14  2007-08-11          Nice    Strasbourg     1     0     0     0     1     0
15  2007-08-11       Sochaux       Le Mans     1     3     0     1     0     0
16  2007-08-11    St Etienne  Valenciennes     3     1     1     3     1     1
17  2007-08-11      Toulouse          Lyon     1     0     1     2     3     0
18  2007-08-12          Lens      Paris SG     0     0     0     0     1     0
19  2007-08-12          Metz         Lille     1     2     0     0     1     0
20  2007-08-15      Bordeaux       Le Mans     1     2     3     4     0     1
21  2007-08-15         Lille       Sochaux     1     1     2     1     1     3
22  2007-08-15        Monaco          Metz     2     0     2     1     3     3
23  2007-08-15      Paris SG       Lorient     1     3     0     2     0     1
24  2007-08-15        Rennes    St Etienne     1     0     0     4     2     2
25  2007-08-15    Strasbourg       Auxerre     3     0     0     0     1     4
26  2007-08-15  Valenciennes     Marseille     2     1     4     0     4     0
27  2007-08-16         Nancy          Nice     2     1     3     1     0     1
28  2007-08-18       Auxerre          Caen     1     0     0     1     4     1
29  2007-08-18       Le Mans         Lille     1     1     4     2     1     1
30  2007-08-18       Lorient          Lyon     2     1     5     3     2     3
31  2007-08-18          Metz      Paris SG     0     0     1     1     5     3
32  2007-08-18       Sochaux        Monaco     0     3     2     4     4     3
33  2007-08-18    St Etienne      Bordeaux     0     0     4     4     3     2
34  2007-08-18      Toulouse    Strasbourg     1     3     3     3     6     1
35  2007-08-19          Lens  Valenciennes     0     0     0     6     1     5
36  2007-08-19     Marseille         Nancy     2     2     1     5     2     1
37  2007-08-19          Nice        Rennes     1     1     2     1     3     2
38  2007-08-25      Bordeaux       Lorient     2     2     4     5     2     2
39  2007-08-25          Caen     Marseille     1     2     1     1     2     2
40  2007-08-25        Monaco       Le Mans     3     1     7     7     3     3
41  2007-08-25         Nancy       Auxerre     4     1     7     1     3     7
42  2007-08-25          Nice      Toulouse     1     1     3     4     4     7
43  2007-08-25        Rennes          Metz     2     0     2     1     3     5
44  2007-08-25    Strasbourg          Lens     2     1     6     1     2     3
45  2007-08-25  Valenciennes       Sochaux     3     1     6     2     5     7
46  2007-08-26          Lyon    St Etienne     1     0     4     4     3     3
47  2007-08-26      Paris SG         Lille     1     1     1     4     3     3
48  2007-08-28       Lorient  Valenciennes     1     3     7     6     3     5
49  2007-08-29       Auxerre        Rennes     0     2     1     2     7     3
50  2007-08-29       Le Mans      Paris SG     0     2     8     2     6     4
51  2007-08-29         Lille        Monaco     0     1     5    10     4     4
52  2007-08-29     Marseille          Nice     0     2     5     4     5     5
53  2007-08-29          Metz      Bordeaux     0     1     1     6     7     4
54  2007-08-29       Sochaux          Lyon     1     2     3     6    10     4
55  2007-08-29    St Etienne    Strasbourg     2     0     4     8     4     3
56  2007-09-01      Bordeaux        Monaco     2     1     6    10     4     4
57  2007-09-01          Caen       Sochaux     2     2     4     3     6    10
58  2007-09-01          Lyon       Le Mans     3     2     6     8     4     6
59  2007-09-01         Nancy    St Etienne     2     0    11     4     4     4

Get Home and Away Shots

In [250]:
# Gets the shots fired agg arranged by teams and matchweek
def get_shots_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSF = playing_stat.iloc[i]['HS']
        # aggregated Home Team shots
        AGASF = playing_stat.iloc[i]['AS']
        # aggregated Away Team shots
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired




# Gets the goals conceded agg arranged by teams and matchweek
def get_shots_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASC = playing_stat.iloc[i]['HS']
        # aggregated home team shots conceded
        AGHSC = playing_stat.iloc[i]['AS']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded



def get_sf(playing_stat):
    SF = get_shots_fired(playing_stat)
    SC = get_shots_conceded(playing_stat)
   
    j = 0
    AGHSF = []
    AGASF = []
    AGHSC = []
    AGASC = []    

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSF.append(SF.loc[ht][j])
        AGASF.append(SF.loc[at][j])
        AGHSC.append(SC.loc[ht][j])
        AGASC.append(SC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHSF'] = AGHSF
    playing_stat['AGASF'] = AGASF
    playing_stat['AGHSC'] = AGHSC
    playing_stat['AGASC'] = AGASC
    return playing_stat

In [251]:
#playing_statistics_1 = get_sf(playing_statistics_1)
#playing_statistics_2 = get_sf(playing_statistics_2)
#playing_statistics_3 = get_sf(playing_statistics_3)
#playing_statistics_4 = get_sf(playing_statistics_4)
#playing_statistics_5 = get_sf(playing_statistics_5)
#playing_statistics_6 = get_sf(playing_statistics_6)
#playing_statistics_7 = get_sf(playing_statistics_7)
playing_statistics_8 = get_sf(playing_statistics_8)
playing_statistics_9 = get_sf(playing_statistics_9)
playing_statistics_10 = get_sf(playing_statistics_10)
playing_statistics_11 = get_sf(playing_statistics_11)
playing_statistics_12 = get_sf(playing_statistics_12)
playing_statistics_13 = get_sf(playing_statistics_13)
playing_statistics_14 = get_sf(playing_statistics_14)
playing_statistics_15 = get_sf(playing_statistics_15)
playing_statistics_16 = get_sf(playing_statistics_16)
playing_statistics_17 = get_sf(playing_statistics_17)
playing_statistics_18 = get_sf(playing_statistics_18)
playing_statistics_19 = get_sf(playing_statistics_19)
#playing_statistics_20 = get_sf(playing_statistics_20)

<ipython-input-250-86deb0bf7e72>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSF'] = AGHSF
<ipython-input-250-86deb0bf7e72>:76: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASF'] = AGASF
<ipython-input-250-86deb0bf7e72>:77: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSC'] = AGHSC
<ipython-input-250-86deb0bf7e72>:78: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASC'] = AGASC

In [252]:
playing_statistics_9[['Date', "HomeTeam", "AwayTeam", "HS", "AS",'AGHSF', "AGASF", "AGHSC", "AGASC"]].head(50)

          Date      HomeTeam      AwayTeam  HS  AS  AGHSF  AGASF  AGHSC  AGASC
0   2008-08-09       Auxerre        Nantes  10  15      0      0      0      0
1   2008-08-09      Bordeaux          Caen  24   8      0      0      0      0
2   2008-08-09      Le Havre          Nice  14  15      0      0      0      0
3   2008-08-09       Le Mans       Lorient  10  12      0      0      0      0
4   2008-08-09        Monaco      Paris SG  10   7      0      0      0      0
5   2008-08-09         Nancy         Lille   8  11      0      0      0      0
6   2008-08-09        Rennes     Marseille  14  19      0      0      0      0
7   2008-08-09       Sochaux      Grenoble  18   7      0      0      0      0
8   2008-08-09  Valenciennes    St Etienne  11  26      0      0      0      0
9   2008-08-10          Lyon      Toulouse  10   8      0      0      0      0
10  2008-08-16          Caen  Valenciennes  20  19      8     11     24     26
11  2008-08-16         Lille       Le Mans  11   6     11     10      8     12
12  2008-08-16        Nantes        Monaco  13  10     15     10     10      7
13  2008-08-16          Nice         Nancy   5   9     15      8     14     11
14  2008-08-16      Paris SG      Bordeaux   6  16      7     24     10      8
15  2008-08-16    St Etienne       Sochaux  18  18     26     18     11      7
16  2008-08-16      Toulouse      Le Havre  16  10      8     14     10     15
17  2008-08-17      Grenoble        Rennes   8  18      7     14     18     19
18  2008-08-17       Lorient          Lyon   7  13     12     10     10      8
19  2008-08-17     Marseille       Auxerre  18   7     19     10     14     15
20  2008-08-23      Le Havre     Marseille  11  16     24     37     31     21
21  2008-08-23       Le Mans    St Etienne   5  12     16     44     23     29
22  2008-08-23          Lyon      Grenoble  16   9     23     15     15     36
23  2008-08-23        Monaco          Caen  12  15     20     28     20     43
24  2008-08-23         Nancy      Toulouse  12   7     17     24     16     20
25  2008-08-23       Sochaux      Paris SG  17  15     36     13     25     26
26  2008-08-23  Valenciennes       Lorient  15  15     30     19     46     23
27  2008-08-24       Auxerre          Nice  12  12     17     20     33     23
28  2008-08-24      Bordeaux        Nantes  22   7     40     28     14     20
29  2008-08-24        Rennes         Lille  20  11     32     22     27     14
30  2008-08-30          Caen      Paris SG  15  13     43     28     55     43
31  2008-08-30      Grenoble        Monaco   9   8     24     32     52     35
32  2008-08-30       Lorient       Auxerre  14   9     34     29     38     45
33  2008-08-30     Marseille       Sochaux  14  11     53     53     32     40
34  2008-08-30         Nancy      Le Havre  21  12     29     35     23     47
35  2008-08-30        Nantes       Le Mans  14  12     35     21     42     35
36  2008-08-30          Nice  Valenciennes  13  10     32     45     35     61
37  2008-08-31         Lille      Bordeaux  17  11     33     62     34     21
38  2008-08-31    St Etienne          Lyon   9  15     56     39     34     24
39  2008-08-31      Toulouse        Rennes   7  12     31     52     32     38
40  2008-09-13       Auxerre         Nancy  14   8     38     50     59     35
41  2008-09-13      Bordeaux     Marseille  14  13     73     67     38     43
42  2008-09-13       Le Mans      Toulouse  11   5     33     38     49     44
43  2008-09-13          Lyon          Nice  28   4     54     45     33     45
44  2008-09-13        Monaco       Lorient   7  10     40     48     44     47
45  2008-09-13        Rennes      Le Havre  14  10     64     47     45     68
46  2008-09-13  Valenciennes      Grenoble   8   9     55     33     74     60
47  2008-09-14          Caen    St Etienne  14  18     58     65     68     49
48  2008-09-14      Paris SG        Nantes   9  13     41     49     58     54
49  2008-09-14       Sochaux         Lille  15  16     64     50     54     45

Team Shots on Taget

In [253]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_shots_fired_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHSTF = playing_stat.iloc[i]['HST']
        # aggregated Home Team shots on Taget
        AGASTF = playing_stat.iloc[i]['AST']
        # aggregated Away Team shots on Taget
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    ShotsFired = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsFired[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsFired[i] = ShotsFired[i] + ShotsFired[i-1]
    return ShotsFired

# Gets the goals conceded agg on target arranged by teams and matchweek
def get_shots_conceded_target(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGASTC = playing_stat.iloc[i]['HST']
        # aggregated home team shots conceded
        AGHSTC = playing_stat.iloc[i]['AST']
        # aggregated away team shots conceded
        teams[playing_stat.iloc[i].HomeTeam].append(AGHSTC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGASTC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    ShotsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    ShotsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        ShotsConceded[i] = ShotsConceded[i] + ShotsConceded[i-1]
    return ShotsConceded

def get_sf_target(playing_stat):
    SFT = get_shots_fired_target(playing_stat)
    SCT = get_shots_conceded_target(playing_stat)
    
    j = 0
    AGHSTF = []
    AGASTF = []
    AGHSTC = []
    AGASTC = []  

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHSTF.append(SFT.loc[ht][j])
        AGASTF.append(SFT.loc[at][j])
        AGHSTC.append(SCT.loc[ht][j])
        AGASTC.append(SCT.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHSTF'] = AGHSTF
    playing_stat['AGASTF'] = AGASTF
    playing_stat['AGHSTC'] = AGHSTC
    playing_stat['AGASTC'] = AGASTC
    
    return playing_stat

In [254]:
#playing_statistics_1 = get_sf_target(playing_statistics_1)
#playing_statistics_2 = get_sf_target(playing_statistics_2)
#playing_statistics_3 = get_sf_target(playing_statistics_3)
#playing_statistics_4 = get_sf_target(playing_statistics_4)
#playing_statistics_5 = get_sf_target(playing_statistics_5)
#playing_statistics_6 = get_sf_target(playing_statistics_6)
#playing_statistics_7 = get_sf_target(playing_statistics_7)
playing_statistics_8 = get_sf_target(playing_statistics_8)
playing_statistics_9 = get_sf_target(playing_statistics_9)
playing_statistics_10 = get_sf_target(playing_statistics_10)
playing_statistics_11 = get_sf_target(playing_statistics_11)
playing_statistics_12 = get_sf_target(playing_statistics_12)
playing_statistics_13 = get_sf_target(playing_statistics_13)
playing_statistics_14 = get_sf_target(playing_statistics_14)
playing_statistics_15 = get_sf_target(playing_statistics_15)
playing_statistics_16 = get_sf_target(playing_statistics_16)
playing_statistics_17 = get_sf_target(playing_statistics_17)
playing_statistics_18 = get_sf_target(playing_statistics_18)
playing_statistics_19 = get_sf_target(playing_statistics_19)
#playing_statistics_20 = get_sf_target(playing_statistics_20)

<ipython-input-253-d1efa55e6e86>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTF'] = AGHSTF
<ipython-input-253-d1efa55e6e86>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTF'] = AGASTF
<ipython-input-253-d1efa55e6e86>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHSTC'] = AGHSTC
<ipython-input-253-d1efa55e6e86>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGASTC'] = AGASTC

In [255]:
playing_statistics_12[['Date', "HomeTeam", "AwayTeam", "HST", "AST",'AGHSTF', "AGASTF", "AGHSTC", "AGASTC"]].head(60)

,Date,HomeTeam,AwayTeam,HST,AST,AGHSTF,AGASTF,AGHSTC,AGASTC
0,2011-08-06,Ajaccio,Toulouse,6,8,0,0,0,0
1,2011-08-06,Brest,Evian Thonon Gaillard,7,3,0,0,0,0
2,2011-08-06,Caen,Valenciennes,3,6,0,0,0,0
3,2011-08-06,Marseille,Sochaux,8,3,0,0,0,0
4,2011-08-06,Montpellier,Auxerre,4,8,0,0,0,0
5,2011-08-06,Nancy,Lille,1,6,0,0,0,0
6,2011-08-06,Nice,Lyon,4,9,0,0,0,0
7,2011-08-06,Paris SG,Lorient,3,4,0,0,0,0
8,2011-08-07,Bordeaux,St Etienne,5,2,0,0,0,0
9,2011-08-07,Dijon,Rennes,5,7,0,0,0,0
10,2011-08-13,Lorient,Bordeaux,5,6,4,5,3,2
11,2011-08-13,Lyon,Ajaccio,8,2,9,6,4,8
12,2011-08-13,Rennes,Paris SG,4,4,7,3,5,4
13,2011-08-13,Sochaux,Caen,8,6,3,3,8,6
14,2011-08-13,St Etienne,Nancy,4,2,2,1,5,6
15,2011-08-13,Toulouse,Dijon,7,3,8,5,6,7
16,2011-08-13,Valenciennes,Brest,6,6,6,7,3,3
17,2011-08-14,Auxerre,Marseille,5,2,8,8,4,3
18,2011-08-14,Evian Thonon Gaillard,Nice,4,3,3,4,7,9
19,2011-08-14,Lille,Montpellier,6,3,6,4,1,8
20,2011-08-20,Ajaccio,Evian Thonon Gaillard,2,3,8,7,16,10
21,2011-08-20,Bordeaux,Auxerre,4,2,11,13,7,6
22,2011-08-20,Brest,Lyon,6,2,13,17,9,6
23,2011-08-20,Caen,Lille,2,10,9,12,14,4
24,2011-08-20,Dijon,Lorient,2,6,8,9,14,9
25,2011-08-20,Nice,Toulouse,3,3,7,15,13,9
26,2011-08-21,Marseille,St Etienne,4,1,10,6,8,7
27,2011-08-21,Montpellier,Rennes,7,1,7,11,14,9
28,2011-08-21,Nancy,Sochaux,4,3,3,11,10,14
29,2011-08-21,Paris SG,Valenciennes,4,4,7,12,8,9
30,2011-08-27,Auxerre,Ajaccio,9,1,15,10,10,19
31,2011-08-27,Evian Thonon Gaillard,Dijon,5,4,10,10,12,20
32,2011-08-27,Lorient,Nancy,7,2,15,7,11,13
33,2011-08-27,Lyon,Montpellier,4,8,19,14,12,15
34,2011-08-27,Nice,Brest,3,5,10,19,16,11
35,2011-08-27,Valenciennes,Bordeaux,3,5,16,15,13,9
36,2011-08-28,Lille,Marseille,5,4,22,14,6,9
37,2011-08-28,Rennes,Caen,8,8,12,11,16,24
38,2011-08-28,Sochaux,St Etienne,5,1,14,7,18,11
39,2011-08-28,Toulouse,Paris SG,2,5,18,11,12,12
40,2011-09-10,Ajaccio,Valenciennes,9,6,11,19,28,18
41,2011-09-10,Bordeaux,Evian Thonon Gaillard,4,3,20,15,12,16
42,2011-09-10,Caen,Toulouse,0,6,19,20,32,17
43,2011-09-10,Dijon,Lyon,4,4,14,23,25,20
44,2011-09-10,Marseille,Rennes,8,3,18,20,14,24
45,2011-09-10,Sochaux,Lorient,2,2,19,22,19,13
46,2011-09-10,St Etienne,Lille,0,5,8,27,16,10
47,2011-09-11,Montpellier,Nice,4,1,22,13,19,21
48,2011-09-11,Nancy,Auxerre,8,4,9,24,20,11
49,2011-09-11,Paris SG,Brest,3,1,16,24,14,14
50,2011-09-17,Auxerre,Caen,2,6,28,19,19,38
51,2011-09-17,Brest,Montpellier,5,7,25,26,17,20
52,2011-09-17,Lille,Sochaux,4,4,32,21,10,21
53,2011-09-17,Lorient,St Etienne,6,3,24,8,15,21
54,2011-09-17,Nice,Ajaccio,6,2,14,20,25,34
55,2011-09-17,Toulouse,Bordeaux,8,3,26,24,17,15
56,2011-09-17,Valenciennes,Dijon,9,2,25,18,27,29
57,2011-09-18,Evian Thonon Gaillard,Paris SG,5,7,18,19,20,15
58,2011-09-18,Lyon,Marseille,5,3,27,26,24,17
59,2011-09-18,Rennes,Nancy,4,2,23,17,32,24

Team Fouls Committed

In [256]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_fouls(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHF = playing_stat.iloc[i]['HF']
        # aggregated Home Team Fouls
        AGAF = playing_stat.iloc[i]['AF']
        # aggregated Away Team Fouls
        teams[playing_stat.iloc[i].HomeTeam].append(AGHF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Fouls = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Fouls[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Fouls[i] = Fouls[i] + Fouls[i-1]
    return Fouls


def get_fouls_agg(playing_stat):
    FA = get_fouls(playing_stat)
   
    j = 0
    AGHF = []
    AGAF = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHF.append(FA.loc[ht][j])
        AGAF.append(FA.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHF'] = AGHF
    playing_stat['AGAF'] = AGAF
    return playing_stat

In [257]:
#playing_statistics_1 = get_fouls_agg(playing_statistics_1)
#playing_statistics_2 = get_fouls_agg(playing_statistics_2)
#playing_statistics_3 = get_fouls_agg(playing_statistics_3)
#playing_statistics_4 = get_fouls_agg(playing_statistics_4)
#playing_statistics_5 = get_fouls_agg(playing_statistics_5)
#playing_statistics_6 = get_fouls_agg(playing_statistics_6)
#playing_statistics_7 = get_fouls_agg(playing_statistics_7)
playing_statistics_8 = get_fouls_agg(playing_statistics_8)
playing_statistics_9 = get_fouls_agg(playing_statistics_9)
playing_statistics_10 = get_fouls_agg(playing_statistics_10)
playing_statistics_11 = get_fouls_agg(playing_statistics_11)
playing_statistics_12 = get_fouls_agg(playing_statistics_12)
playing_statistics_13 = get_fouls_agg(playing_statistics_13)
playing_statistics_14 = get_fouls_agg(playing_statistics_14)
playing_statistics_15 = get_fouls_agg(playing_statistics_15)
playing_statistics_16 = get_fouls_agg(playing_statistics_16)
playing_statistics_17 = get_fouls_agg(playing_statistics_17)
playing_statistics_18 = get_fouls_agg(playing_statistics_18)
playing_statistics_19 = get_fouls_agg(playing_statistics_19)
#playing_statistics_20 = get_fouls_agg(playing_statistics_20)

<ipython-input-256-b86ba37f240e>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHF'] = AGHF
<ipython-input-256-b86ba37f240e>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAF'] = AGAF

In [258]:
playing_statistics_12[['Date', "HomeTeam", "AwayTeam", "HF", "AF",'AGHF', "AGAF"]].head(60)

,Date,HomeTeam,AwayTeam,HF,AF,AGHF,AGAF
0,2011-08-06,Ajaccio,Toulouse,14.0,17.0,0.0,0.0
1,2011-08-06,Brest,Evian Thonon Gaillard,12.0,15.0,0.0,0.0
2,2011-08-06,Caen,Valenciennes,12.0,11.0,0.0,0.0
3,2011-08-06,Marseille,Sochaux,15.0,13.0,0.0,0.0
4,2011-08-06,Montpellier,Auxerre,16.0,22.0,0.0,0.0
5,2011-08-06,Nancy,Lille,17.0,21.0,0.0,0.0
6,2011-08-06,Nice,Lyon,18.0,13.0,0.0,0.0
7,2011-08-06,Paris SG,Lorient,21.0,10.0,0.0,0.0
8,2011-08-07,Bordeaux,St Etienne,16.0,19.0,0.0,0.0
9,2011-08-07,Dijon,Rennes,18.0,16.0,0.0,0.0
10,2011-08-13,Lorient,Bordeaux,13.0,15.0,10.0,16.0
11,2011-08-13,Lyon,Ajaccio,15.0,17.0,13.0,14.0
12,2011-08-13,Rennes,Paris SG,15.0,21.0,16.0,21.0
13,2011-08-13,Sochaux,Caen,13.0,20.0,13.0,12.0
14,2011-08-13,St Etienne,Nancy,11.0,17.0,19.0,17.0
15,2011-08-13,Toulouse,Dijon,8.0,11.0,17.0,18.0
16,2011-08-13,Valenciennes,Brest,17.0,16.0,11.0,12.0
17,2011-08-14,Auxerre,Marseille,18.0,18.0,22.0,15.0
18,2011-08-14,Evian Thonon Gaillard,Nice,14.0,13.0,15.0,18.0
19,2011-08-14,Lille,Montpellier,10.0,22.0,21.0,16.0
20,2011-08-20,Ajaccio,Evian Thonon Gaillard,22.0,18.0,31.0,29.0
21,2011-08-20,Bordeaux,Auxerre,14.0,16.0,31.0,40.0
22,2011-08-20,Brest,Lyon,16.0,17.0,28.0,28.0
23,2011-08-20,Caen,Lille,18.0,17.0,32.0,31.0
24,2011-08-20,Dijon,Lorient,19.0,15.0,29.0,23.0
25,2011-08-20,Nice,Toulouse,14.0,16.0,31.0,25.0
26,2011-08-21,Marseille,St Etienne,11.0,17.0,33.0,30.0
27,2011-08-21,Montpellier,Rennes,21.0,14.0,38.0,31.0
28,2011-08-21,Nancy,Sochaux,18.0,17.0,34.0,26.0
29,2011-08-21,Paris SG,Valenciennes,10.0,14.0,42.0,28.0
30,2011-08-27,Auxerre,Ajaccio,5.0,15.0,56.0,53.0
31,2011-08-27,Evian Thonon Gaillard,Dijon,16.0,18.0,47.0,48.0
32,2011-08-27,Lorient,Nancy,10.0,17.0,38.0,52.0
33,2011-08-27,Lyon,Montpellier,14.0,13.0,45.0,59.0
34,2011-08-27,Nice,Brest,14.0,18.0,45.0,44.0
35,2011-08-27,Valenciennes,Bordeaux,22.0,17.0,42.0,45.0
36,2011-08-28,Lille,Marseille,17.0,15.0,48.0,44.0
37,2011-08-28,Rennes,Caen,18.0,18.0,45.0,50.0
38,2011-08-28,Sochaux,St Etienne,17.0,16.0,43.0,47.0
39,2011-08-28,Toulouse,Paris SG,17.0,14.0,41.0,52.0
40,2011-09-10,Ajaccio,Valenciennes,13.0,16.0,68.0,64.0
41,2011-09-10,Bordeaux,Evian Thonon Gaillard,19.0,18.0,62.0,63.0
42,2011-09-10,Caen,Toulouse,15.0,17.0,68.0,58.0
43,2011-09-10,Dijon,Lyon,11.0,17.0,66.0,59.0
44,2011-09-10,Marseille,Rennes,8.0,17.0,59.0,63.0
45,2011-09-10,Sochaux,Lorient,6.0,16.0,60.0,48.0
46,2011-09-10,St Etienne,Lille,15.0,13.0,63.0,65.0
47,2011-09-11,Montpellier,Nice,8.0,13.0,72.0,59.0
48,2011-09-11,Nancy,Auxerre,7.0,16.0,69.0,61.0
49,2011-09-11,Paris SG,Brest,14.0,20.0,66.0,62.0
50,2011-09-17,Auxerre,Caen,22.0,15.0,77.0,83.0
51,2011-09-17,Brest,Montpellier,23.0,26.0,82.0,80.0
52,2011-09-17,Lille,Sochaux,9.0,16.0,78.0,66.0
53,2011-09-17,Lorient,St Etienne,11.0,13.0,64.0,78.0
54,2011-09-17,Nice,Ajaccio,18.0,13.0,72.0,81.0
55,2011-09-17,Toulouse,Bordeaux,24.0,22.0,75.0,81.0
56,2011-09-17,Valenciennes,Dijon,21.0,16.0,80.0,77.0
57,2011-09-18,Evian Thonon Gaillard,Paris SG,25.0,11.0,81.0,80.0
58,2011-09-18,Lyon,Marseille,NaN,NaN,76.0,67.0
59,2011-09-18,Rennes,Nancy,10.0,20.0,80.0,76.0

Team Corners

In [259]:
# Gets the shots fired on target agg arranged by teams and matchweek
def get_corners_fired(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHCF = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGACF = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCF)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACF)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners

def get_corners_conceived(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGACC = playing_stat.iloc[i]['HC']
        # aggregated Home Team corners
        AGHCC = playing_stat.iloc[i]['AC']
        # aggregated Away Team corners
        teams[playing_stat.iloc[i].HomeTeam].append(AGHCC)
        teams[playing_stat.iloc[i].AwayTeam].append(AGACC)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Corners = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Corners[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Corners[i] = Corners[i] + Corners[i-1]
    return Corners


def get_corners_agg(playing_stat):
    CF = get_corners_fired(playing_stat)
    CC = get_corners_conceived(playing_stat)
   
    j = 0
    AGHCF = []
    AGACF = []
    AGHCC = []
    AGACC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHCF.append(CF.loc[ht][j])
        AGACF.append(CF.loc[at][j])
        AGHCC.append(CC.loc[ht][j])
        AGACC.append(CC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHCF'] = AGHCF
    playing_stat['AGACF'] = AGACF
    playing_stat['AGHCC'] = AGHCC
    playing_stat['AGACC'] = AGACC
    
    return playing_stat

In [260]:
#playing_statistics_1 = get_corners_agg(playing_statistics_1)
#playing_statistics_2 = get_corners_agg(playing_statistics_2)
#playing_statistics_3 = get_corners_agg(playing_statistics_3)
#playing_statistics_4 = get_corners_agg(playing_statistics_4)
#playing_statistics_5 = get_corners_agg(playing_statistics_5)
#playing_statistics_6 = get_corners_agg(playing_statistics_6)
#playing_statistics_7 = get_corners_agg(playing_statistics_7)
playing_statistics_8 = get_corners_agg(playing_statistics_8)
playing_statistics_9 = get_corners_agg(playing_statistics_9)
playing_statistics_10 = get_corners_agg(playing_statistics_10)
playing_statistics_11 = get_corners_agg(playing_statistics_11)
playing_statistics_12 = get_corners_agg(playing_statistics_12)
playing_statistics_13 = get_corners_agg(playing_statistics_13)
playing_statistics_14 = get_corners_agg(playing_statistics_14)
playing_statistics_15 = get_corners_agg(playing_statistics_15)
playing_statistics_16 = get_corners_agg(playing_statistics_16)
playing_statistics_17 = get_corners_agg(playing_statistics_17)
playing_statistics_18 = get_corners_agg(playing_statistics_18)
playing_statistics_19 = get_corners_agg(playing_statistics_19)
#playing_statistics_20 = get_corners_agg(playing_statistics_20)

<ipython-input-259-8a4066657f67>:70: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCF'] = AGHCF
<ipython-input-259-8a4066657f67>:71: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACF'] = AGACF
<ipython-input-259-8a4066657f67>:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHCC'] = AGHCC
<ipython-input-259-8a4066657f67>:73: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGACC'] = AGACC

In [261]:
playing_statistics_12[['Date', "HomeTeam", "AwayTeam", "HC", "AC",'AGHCF', "AGACF", "AGHCC", "AGACC"]].head(50)

,Date,HomeTeam,AwayTeam,HC,AC,AGHCF,AGACF,AGHCC,AGACC
0,2011-08-06,Ajaccio,Toulouse,11,4,0,0,0,0
1,2011-08-06,Brest,Evian Thonon Gaillard,11,8,0,0,0,0
2,2011-08-06,Caen,Valenciennes,3,11,0,0,0,0
3,2011-08-06,Marseille,Sochaux,4,5,0,0,0,0
4,2011-08-06,Montpellier,Auxerre,4,5,0,0,0,0
5,2011-08-06,Nancy,Lille,6,8,0,0,0,0
6,2011-08-06,Nice,Lyon,12,9,0,0,0,0
7,2011-08-06,Paris SG,Lorient,7,6,0,0,0,0
8,2011-08-07,Bordeaux,St Etienne,3,4,0,0,0,0
9,2011-08-07,Dijon,Rennes,9,3,0,0,0,0
10,2011-08-13,Lorient,Bordeaux,5,10,6,3,7,4
11,2011-08-13,Lyon,Ajaccio,13,1,9,11,12,4
12,2011-08-13,Rennes,Paris SG,3,3,3,7,9,6
13,2011-08-13,Sochaux,Caen,8,3,5,3,4,11
14,2011-08-13,St Etienne,Nancy,9,2,4,6,3,8
15,2011-08-13,Toulouse,Dijon,6,1,4,9,11,3
16,2011-08-13,Valenciennes,Brest,7,4,11,11,3,8
17,2011-08-14,Auxerre,Marseille,9,2,5,4,4,5
18,2011-08-14,Evian Thonon Gaillard,Nice,2,5,8,12,11,9
19,2011-08-14,Lille,Montpellier,7,0,8,4,6,5
20,2011-08-20,Ajaccio,Evian Thonon Gaillard,1,9,12,10,17,16
21,2011-08-20,Bordeaux,Auxerre,10,1,13,14,9,6
22,2011-08-20,Brest,Lyon,5,8,15,22,15,13
23,2011-08-20,Caen,Lille,0,7,6,15,19,6
24,2011-08-20,Dijon,Lorient,1,14,10,11,9,17
25,2011-08-20,Nice,Toulouse,3,1,17,10,11,12
26,2011-08-21,Marseille,St Etienne,9,3,6,13,14,5
27,2011-08-21,Montpellier,Rennes,4,1,4,6,12,12
28,2011-08-21,Nancy,Sochaux,4,4,8,13,17,7
29,2011-08-21,Paris SG,Valenciennes,3,0,10,18,9,7
30,2011-08-27,Auxerre,Ajaccio,10,2,15,13,16,26
31,2011-08-27,Evian Thonon Gaillard,Dijon,5,4,19,11,17,23
32,2011-08-27,Lorient,Nancy,10,1,25,12,18,21
33,2011-08-27,Lyon,Montpellier,5,7,30,8,18,13
34,2011-08-27,Nice,Brest,7,3,20,20,12,23
35,2011-08-27,Valenciennes,Bordeaux,4,4,18,23,10,10
36,2011-08-28,Lille,Marseille,5,6,22,15,6,17
37,2011-08-28,Rennes,Caen,5,10,7,6,16,26
38,2011-08-28,Sochaux,St Etienne,4,5,17,16,11,14
39,2011-08-28,Toulouse,Paris SG,5,3,11,13,15,9
40,2011-09-10,Ajaccio,Valenciennes,3,7,15,22,36,14
41,2011-09-10,Bordeaux,Evian Thonon Gaillard,5,3,27,24,14,21
42,2011-09-10,Caen,Toulouse,6,5,16,16,31,18
43,2011-09-10,Dijon,Lyon,7,5,15,35,28,25
44,2011-09-10,Marseille,Rennes,13,6,21,12,22,26
45,2011-09-10,Sochaux,Lorient,1,6,21,35,16,19
46,2011-09-10,St Etienne,Lille,3,2,21,27,18,12
47,2011-09-11,Montpellier,Nice,2,6,15,27,18,15
48,2011-09-11,Nancy,Auxerre,1,6,13,25,31,18
49,2011-09-11,Paris SG,Brest,4,6,16,23,14,30

Yellow Cards

In [262]:
# Gets yellow cards agg arranged by teams and matchweek
def get_yellow(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHY = playing_stat.iloc[i]['HY']
        # aggregated Home Team yellow cards
        AGAY = playing_stat.iloc[i]['AY']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHY)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAY)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Yellow = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Yellow[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Yellow[i] = Yellow[i] + Yellow[i-1]
    return Yellow


def get_yellow_agg(playing_stat):
    Y = get_yellow(playing_stat)
   
    j = 0
    AGHY = []
    AGAY = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHY.append(Y.loc[ht][j])
        AGAY.append(Y.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHY'] = AGHY
    playing_stat['AGAY'] = AGAY
    return playing_stat

In [263]:
#playing_statistics_1 = get_yellow_agg(playing_statistics_1)
#playing_statistics_2 = get_yellow_agg(playing_statistics_2)
#playing_statistics_3 = get_yellow_agg(playing_statistics_3)
#playing_statistics_4 = get_yellow_agg(playing_statistics_4)
#playing_statistics_5 = get_yellow_agg(playing_statistics_5)
#playing_statistics_6 = get_yellow_agg(playing_statistics_6)
#playing_statistics_7 = get_yellow_agg(playing_statistics_7)
playing_statistics_8 = get_yellow_agg(playing_statistics_8)
playing_statistics_9 = get_yellow_agg(playing_statistics_9)
playing_statistics_10 = get_yellow_agg(playing_statistics_10)
playing_statistics_11 = get_yellow_agg(playing_statistics_11)
playing_statistics_12 = get_yellow_agg(playing_statistics_12)
playing_statistics_13 = get_yellow_agg(playing_statistics_13)
playing_statistics_14 = get_yellow_agg(playing_statistics_14)
playing_statistics_15 = get_yellow_agg(playing_statistics_15)
playing_statistics_16 = get_yellow_agg(playing_statistics_16)
playing_statistics_17 = get_yellow_agg(playing_statistics_17)
playing_statistics_18 = get_yellow_agg(playing_statistics_18)
playing_statistics_19 = get_yellow_agg(playing_statistics_19)
#playing_statistics_20 = get_yellow_agg(playing_statistics_20)

<ipython-input-262-697b7ad671dc>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHY'] = AGHY
<ipython-input-262-697b7ad671dc>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAY'] = AGAY

In [264]:
playing_statistics_19[['Date', "HomeTeam", "AwayTeam", "HY", "AY",'AGHY', "AGAY"]].head(50)

          Date     HomeTeam     AwayTeam  HY  AY  AGHY  AGAY
0   2018-08-10    Marseille     Toulouse   1   3     0     0
1   2018-08-11       Angers        Nimes   2   2     0     0
2   2018-08-11        Lille       Rennes   1   0     0     0
3   2018-08-11  Montpellier        Dijon   2   2     0     0
4   2018-08-11       Nantes       Monaco   1   0     0     0
5   2018-08-11         Nice        Reims   1   2     0     0
6   2018-08-11   St Etienne     Guingamp   3   1     0     0
7   2018-08-12     Bordeaux   Strasbourg   1   0     0     0
8   2018-08-12         Lyon       Amiens   0   2     0     0
9   2018-08-12     Paris SG         Caen   1   0     0     0
10  2018-08-17        Reims         Lyon   2   0     2     0
11  2018-08-18       Amiens  Montpellier   1   3     2     2
12  2018-08-18         Caen         Nice   2   2     0     1
13  2018-08-18        Dijon       Nantes   0   1     2     1
14  2018-08-18     Guingamp     Paris SG   0   1     1     1
15  2018-08-18       Monaco        Lille   0   0     0     1
16  2018-08-18       Rennes       Angers   1   2     0     2
17  2018-08-19        Nimes    Marseille   3   1     2     1
18  2018-08-19   Strasbourg   St Etienne   1   2     0     3
19  2018-08-19     Toulouse     Bordeaux   1   1     3     1
20  2018-08-24         Lyon   Strasbourg   1   2     0     1
21  2018-08-25       Amiens        Reims   1   1     3     4
22  2018-08-25  Montpellier   St Etienne   3   0     5     5
23  2018-08-25       Nantes         Caen   2   3     2     2
24  2018-08-25         Nice        Dijon   2   3     3     2
25  2018-08-25     Paris SG       Angers   2   0     2     4
26  2018-08-25     Toulouse        Nimes   1   3     4     5
27  2018-08-26     Bordeaux       Monaco   1   2     2     0
28  2018-08-26        Lille     Guingamp   2   1     1     1
29  2018-08-26    Marseille       Rennes   1   1     2     1
30  2018-08-31         Lyon         Nice   0   2     1     5
31  2018-09-01       Angers        Lille   0   1     4     3
32  2018-09-01        Dijon         Caen   0   3     5     5
33  2018-09-01     Guingamp     Toulouse   3   2     2     5
34  2018-09-01        Nimes     Paris SG   1   3     8     4
35  2018-09-01        Reims  Montpellier   0   0     5     8
36  2018-09-01   Strasbourg       Nantes   1   2     3     4
37  2018-09-02       Monaco    Marseille   1   1     2     3
38  2018-09-02       Rennes     Bordeaux   0   3     2     3
39  2018-09-02   St Etienne       Amiens   3   2     5     4
40  2018-09-14         Nice       Rennes   4   1     7     2
41  2018-09-14     Paris SG   St Etienne   1   1     7     8
42  2018-09-15       Amiens        Lille   1   2     6     4
43  2018-09-15         Caen         Lyon   1   2     8     1
44  2018-09-15        Dijon       Angers   2   2     5     4
45  2018-09-15  Montpellier   Strasbourg   1   2     8     4
46  2018-09-15     Toulouse       Monaco   2   3     7     3
47  2018-09-16     Bordeaux        Nimes   2   0     6     9
48  2018-09-16    Marseille     Guingamp   1   1     4     5
49  2018-09-16       Nantes        Reims   3   4     6     5

Red cards

In [265]:
# Gets red cards agg arranged by teams and matchweek
def get_red(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        AGHR = playing_stat.iloc[i]['HR']
        # aggregated Home Team yellow cards
        AGAR = playing_stat.iloc[i]['AR']
        # aggregated Away Team yellow cards
        teams[playing_stat.iloc[i].HomeTeam].append(AGHR)
        teams[playing_stat.iloc[i].AwayTeam].append(AGAR)
    
    # Create a dataframe for shots fired (goals scored) where rows are teams and cols are matchweek.
    Red = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    Red[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        Red[i] = Red[i] + Red[i-1]
    return Red


def get_red_agg(playing_stat):
    R = get_red(playing_stat)
   
    j = 0
    AGHR = []
    AGAR = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        AGHR.append(R.loc[ht][j])
        AGAR.append(R.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['AGHR'] = AGHR
    playing_stat['AGAR'] = AGAR
    return playing_stat

In [266]:
#playing_statistics_1 = get_red_agg(playing_statistics_1)
#playing_statistics_2 = get_red_agg(playing_statistics_2)
#playing_statistics_3 = get_red_agg(playing_statistics_3)
#playing_statistics_4 = get_red_agg(playing_statistics_4)
#playing_statistics_5 = get_red_agg(playing_statistics_5)
#playing_statistics_6 = get_red_agg(playing_statistics_6)
#playing_statistics_7 = get_red_agg(playing_statistics_7)
playing_statistics_8 = get_red_agg(playing_statistics_8)
playing_statistics_9 = get_red_agg(playing_statistics_9)
playing_statistics_10 = get_red_agg(playing_statistics_10)
playing_statistics_11 = get_red_agg(playing_statistics_11)
playing_statistics_12 = get_red_agg(playing_statistics_12)
playing_statistics_13 = get_red_agg(playing_statistics_13)
playing_statistics_14 = get_red_agg(playing_statistics_14)
playing_statistics_15 = get_red_agg(playing_statistics_15)
playing_statistics_16 = get_red_agg(playing_statistics_16)
playing_statistics_17 = get_red_agg(playing_statistics_17)
playing_statistics_18 = get_red_agg(playing_statistics_18)
playing_statistics_19 = get_red_agg(playing_statistics_19)
#playing_statistics_20 = get_red_agg(playing_statistics_20)

<ipython-input-265-e098fe44355b>:42: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGHR'] = AGHR
<ipython-input-265-e098fe44355b>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AGAR'] = AGAR

In [267]:
playing_statistics_18[['Date', "HomeTeam", "AwayTeam", "HR", "AR",'AGHR', "AGAR"]].head(60)

          Date     HomeTeam     AwayTeam  HR  AR  AGHR  AGAR
0   2017-08-04       Monaco     Toulouse   0   0     0     0
1   2017-08-05         Lyon   Strasbourg   0   0     0     0
2   2017-08-05         Metz     Guingamp   0   0     0     0
3   2017-08-05  Montpellier         Caen   0   0     0     0
4   2017-08-05     Paris SG       Amiens   0   0     0     0
5   2017-08-05   St Etienne         Nice   0   0     0     0
6   2017-08-05       Troyes       Rennes   0   0     0     0
7   2017-08-06       Angers     Bordeaux   0   0     0     0
8   2017-08-06        Lille       Nantes   0   0     0     0
9   2017-08-06    Marseille        Dijon   0   0     0     0
10  2017-08-11         Nice       Troyes   0   0     0     0
11  2017-08-11       Rennes         Lyon   0   0     0     0
12  2017-08-12       Amiens       Angers   0   0     0     0
13  2017-08-12     Bordeaux         Metz   0   0     0     0
14  2017-08-12         Caen   St Etienne   0   0     0     0
15  2017-08-12       Nantes    Marseille   0   0     0     0
16  2017-08-12     Toulouse  Montpellier   0   0     0     0
17  2017-08-13        Dijon       Monaco   0   0     0     0
18  2017-08-13     Guingamp     Paris SG   0   0     0     0
19  2017-08-13   Strasbourg        Lille   0   1     0     0
20  2017-08-18         Metz       Monaco   0   0     0     0
21  2017-08-19         Lyon     Bordeaux   1   0     0     0
22  2017-08-19  Montpellier   Strasbourg   0   0     0     0
23  2017-08-19         Nice     Guingamp   0   0     0     0
24  2017-08-19       Rennes        Dijon   0   0     0     0
25  2017-08-19   St Etienne       Amiens   0   0     0     0
26  2017-08-19       Troyes       Nantes   0   1     0     0
27  2017-08-20        Lille         Caen   0   0     1     0
28  2017-08-20    Marseille       Angers   1   0     0     0
29  2017-08-20     Paris SG     Toulouse   1   0     0     0
30  2017-08-25     Paris SG   St Etienne   0   0     1     0
31  2017-08-26       Amiens         Nice   0   0     0     0
32  2017-08-26     Bordeaux       Troyes   0   0     0     0
33  2017-08-26         Caen         Metz   0   0     0     0
34  2017-08-26        Dijon  Montpellier   0   0     0     0
35  2017-08-26       Nantes         Lyon   0   0     1     1
36  2017-08-26     Toulouse       Rennes   0   1     0     0
37  2017-08-27       Angers        Lille   0   0     0     1
38  2017-08-27     Guingamp   Strasbourg   0   0     0     0
39  2017-08-27       Monaco    Marseille   0   0     0     1
40  2017-09-08        Lille     Bordeaux   1   0     1     0
41  2017-09-08         Metz     Paris SG   1   0     0     1
42  2017-09-09         Caen        Dijon   1   0     0     0
43  2017-09-09  Montpellier       Nantes   1   0     0     1
44  2017-09-09         Nice       Monaco   0   0     0     0
45  2017-09-09   Strasbourg       Amiens   1   0     0     0
46  2017-09-09       Troyes     Toulouse   0   0     0     0
47  2017-09-10         Lyon     Guingamp   0   0     1     0
48  2017-09-10    Marseille       Rennes   0   0     1     1
49  2017-09-10   St Etienne       Angers   1   1     0     0
50  2017-09-15     Toulouse     Bordeaux   0   0     0     0
51  2017-09-16        Dijon   St Etienne   0   0     0     1
52  2017-09-16     Guingamp        Lille   0   0     0     2
53  2017-09-16       Monaco   Strasbourg   0   0     0     1
54  2017-09-16       Nantes         Caen   0   0     1     1
55  2017-09-16       Troyes  Montpellier   1   0     0     1
56  2017-09-17       Amiens    Marseille   0   0     0     1
57  2017-09-17       Angers         Metz   0   0     1     1
58  2017-09-17     Paris SG         Lyon   0   0     1     1
59  2017-09-17       Rennes         Nice   0   0     1     0

GET RESPECTIVE POINTS: 
-> 18 mit 20 ersetzen: number of teams

In [268]:
def get_points(result):
    if result == 'W':
        return 3
    elif result == 'D':
        return 1
    else:
        return 0
    

def get_cuml_points(matchres):
    matchres_points = matchres.applymap(get_points)
    for i in range(2,39):
        matchres_points[i] = matchres_points[i] + matchres_points[i-1]
        
    matchres_points.insert(column =0, loc = 0, value = [0*i for i in range(20)])
    return matchres_points


def get_matchres(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []

    # the value corresponding to keys is a list containing the match result
    for i in range(len(playing_stat)):
        if playing_stat.iloc[i].FTR == 'H':
            teams[playing_stat.iloc[i].HomeTeam].append('W')
            teams[playing_stat.iloc[i].AwayTeam].append('L')
        elif playing_stat.iloc[i].FTR == 'A':
            teams[playing_stat.iloc[i].AwayTeam].append('W')
            teams[playing_stat.iloc[i].HomeTeam].append('L')
        else:
            teams[playing_stat.iloc[i].AwayTeam].append('D')
            teams[playing_stat.iloc[i].HomeTeam].append('D')
            
    return pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T

def get_agg_points(playing_stat):
    matchres = get_matchres(playing_stat)
    cum_pts = get_cuml_points(matchres)
    HTP = []
    ATP = []
    j = 0
    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTP.append(cum_pts.loc[ht][j])
        ATP.append(cum_pts.loc[at][j])

        if ((i + 1)% 10) == 0:
            j = j + 1
            
    playing_stat['HTP'] = HTP
    playing_stat['ATP'] = ATP
    return playing_stat

In [269]:
# Apply to each dataset

#playing_statistics_1 = get_agg_points(playing_statistics_1)
#playing_statistics_2 = get_agg_points(playing_statistics_2)
#playing_statistics_3 = get_agg_points(playing_statistics_3)
#playing_statistics_4 = get_agg_points(playing_statistics_4)
#playing_statistics_5 = get_agg_points(playing_statistics_5)
#playing_statistics_6 = get_agg_points(playing_statistics_6)
#playing_statistics_7 = get_agg_points(playing_statistics_7)
playing_statistics_8 = get_agg_points(playing_statistics_8)
playing_statistics_9 = get_agg_points(playing_statistics_9)
playing_statistics_10 = get_agg_points(playing_statistics_10)
playing_statistics_11 = get_agg_points(playing_statistics_11)
playing_statistics_12 = get_agg_points(playing_statistics_12)
playing_statistics_13 = get_agg_points(playing_statistics_13)
playing_statistics_14 = get_agg_points(playing_statistics_14)
playing_statistics_15 = get_agg_points(playing_statistics_15)
playing_statistics_16 = get_agg_points(playing_statistics_16)
playing_statistics_17 = get_agg_points(playing_statistics_17)
playing_statistics_18 = get_agg_points(playing_statistics_18)
playing_statistics_19 = get_agg_points(playing_statistics_19)
#playing_statistics_20 = get_agg_points(playing_statistics_20)

<ipython-input-268-cae68c17b88e>:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HTP'] = HTP
<ipython-input-268-cae68c17b88e>:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['ATP'] = ATP

In [270]:
playing_statistics_13[['Date', "HomeTeam", "AwayTeam", "FTHG", "FTAG","HTP", "ATP"]].head(60)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,HTP,ATP
0,2012-08-10,Montpellier,Toulouse,1,1,0,0
1,2012-08-11,Evian Thonon Gaillard,Bordeaux,2,3,0,0
2,2012-08-11,Nancy,Brest,1,0,0,0
3,2012-08-11,Nice,Ajaccio,0,1,0,0
4,2012-08-11,Paris SG,Lorient,2,2,0,0
5,2012-08-11,Rennes,Lyon,0,1,0,0
6,2012-08-11,Sochaux,Bastia,2,3,0,0
7,2012-08-11,St Etienne,Lille,1,2,0,0
8,2012-08-11,Troyes,Valenciennes,0,1,0,0
9,2012-08-12,Reims,Marseille,0,1,0,0
10,2012-08-17,Lille,Nancy,1,1,3,3
11,2012-08-18,Bastia,Reims,2,1,3,0
12,2012-08-18,Brest,Evian Thonon Gaillard,1,0,0,0
13,2012-08-18,Lorient,Montpellier,2,1,1,1
14,2012-08-18,Lyon,Troyes,4,1,3,0
15,2012-08-18,Toulouse,St Etienne,2,1,1,0
16,2012-08-18,Valenciennes,Nice,0,0,3,0
17,2012-08-19,Ajaccio,Paris SG,0,0,3,1
18,2012-08-19,Bordeaux,Rennes,1,0,3,0
19,2012-08-19,Marseille,Sochaux,2,0,3,0
20,2012-08-24,Evian Thonon Gaillard,Lyon,1,1,0,6
21,2012-08-25,Nancy,Toulouse,0,1,4,4
22,2012-08-25,Nice,Lille,2,2,1,4
23,2012-08-25,Reims,Sochaux,1,0,0,0
24,2012-08-25,Rennes,Bastia,3,2,0,6
25,2012-08-25,Troyes,Lorient,2,2,0,4
26,2012-08-25,Valenciennes,Ajaccio,3,0,4,4
27,2012-08-26,Montpellier,Marseille,0,1,1,6
28,2012-08-26,Paris SG,Bordeaux,0,0,2,6
29,2012-08-26,St Etienne,Brest,4,0,0,3
30,2012-09-01,Ajaccio,Evian Thonon Gaillard,2,0,4,1
31,2012-09-01,Bastia,St Etienne,0,3,6,3
32,2012-09-01,Brest,Troyes,2,1,3,1
33,2012-09-01,Lorient,Nancy,3,0,5,4
34,2012-09-01,Lyon,Valenciennes,3,2,7,7
35,2012-09-01,Sochaux,Montpellier,1,3,0,1
36,2012-09-01,Toulouse,Reims,1,1,7,3
37,2012-09-02,Bordeaux,Nice,1,1,7,2
38,2012-09-02,Lille,Paris SG,1,2,5,3
39,2012-09-02,Marseille,Rennes,3,1,9,3
40,2012-09-14,Paris SG,Toulouse,2,0,6,8
41,2012-09-14,Reims,Montpellier,3,1,4,4
42,2012-09-15,Evian Thonon Gaillard,Bastia,3,0,1,6
43,2012-09-15,Nice,Brest,4,2,3,6
44,2012-09-15,St Etienne,Sochaux,0,1,6,0
45,2012-09-15,Troyes,Lille,1,1,1,5
46,2012-09-15,Valenciennes,Bordeaux,0,0,7,8
47,2012-09-16,Lyon,Ajaccio,2,0,10,7
48,2012-09-16,Nancy,Marseille,0,1,4,12
49,2012-09-16,Rennes,Lorient,1,2,3,8
50,2012-09-21,Montpellier,St Etienne,1,1,4,6
51,2012-09-22,Bastia,Paris SG,0,4,6,9
52,2012-09-22,Brest,Valenciennes,2,1,6,8
53,2012-09-22,Lorient,Nice,1,1,11,6
54,2012-09-22,Reims,Nancy,2,0,7,4
55,2012-09-22,Sochaux,Troyes,3,1,3,2
56,2012-09-22,Toulouse,Rennes,2,2,8,3
57,2012-09-23,Bordeaux,Ajaccio,2,2,9,7
58,2012-09-23,Lille,Lyon,1,1,6,13
59,2012-09-23,Marseille,Evian Thonon Gaillard,1,0,15,4

GET TEAM FORM: 
-> 9 mit 10 ersetzen!

In [271]:
def get_form(playing_stat,num):
    form = get_matchres(playing_stat)
    form_final = form.copy()
    for i in range(num,39):
        form_final[i] = ''
        j = 0
        while j < num:
            form_final[i] += form[i-j]
            j += 1           
    return form_final

def add_form(playing_stat,num):
    form = get_form(playing_stat,num)
    h = ['M' for i in range(num * 10)]  # since form is not available for n MW (n*10)
    a = ['M' for i in range(num * 10)]
    
    j = num
    for i in range((num*10),380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        
        past = form.loc[ht][j]               # get past n results
        h.append(past[num-1])                    # 0 index is most recent
        
        past = form.loc[at][j]               # get past n results.
        a.append(past[num-1])                   # 0 index is most recent
        
        if ((i + 1)% 10) == 0:
            j = j + 1

    playing_stat['HM' + str(num)] = h                 
    playing_stat['AM' + str(num)] = a

    
    return playing_stat


def add_form_df(playing_statistics):
    playing_statistics = add_form(playing_statistics,1)
    playing_statistics = add_form(playing_statistics,2)
    playing_statistics = add_form(playing_statistics,3)
    playing_statistics = add_form(playing_statistics,4)
    playing_statistics = add_form(playing_statistics,5)
    return playing_statistics

In [272]:
# Make changes to df
#playing_statistics_1 = add_form_df(playing_statistics_1)
#playing_statistics_2 = add_form_df(playing_statistics_2)
#playing_statistics_3 = add_form_df(playing_statistics_3)
#playing_statistics_4 = add_form_df(playing_statistics_4)
#playing_statistics_5 = add_form_df(playing_statistics_5)
#playing_statistics_6 = add_form_df(playing_statistics_6)
#playing_statistics_7 = add_form_df(playing_statistics_7)
playing_statistics_8 = add_form_df(playing_statistics_8)
playing_statistics_9 = add_form_df(playing_statistics_9)
playing_statistics_10 = add_form_df(playing_statistics_10)
playing_statistics_11 = add_form_df(playing_statistics_11)
playing_statistics_12 = add_form_df(playing_statistics_12)
playing_statistics_13 = add_form_df(playing_statistics_13)
playing_statistics_14 = add_form_df(playing_statistics_14)
playing_statistics_15 = add_form_df(playing_statistics_15)
playing_statistics_16 = add_form_df(playing_statistics_16)
playing_statistics_17 = add_form_df(playing_statistics_17)
playing_statistics_18 = add_form_df(playing_statistics_18)
playing_statistics_19 = add_form_df(playing_statistics_19)
#playing_statistics_20 = add_form_df(playing_statistics_20)

<ipython-input-271-7790a7af0e3e>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['HM' + str(num)] = h
<ipython-input-271-7790a7af0e3e>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['AM' + str(num)] = a

Get MatchWeek:

In [273]:
def get_mw(playing_stat):
    j = 1
    MatchWeek = []
    for i in range(380):
        MatchWeek.append(j)
        if ((i + 1)% 10) == 0:
            j = j + 1
    playing_stat['MW'] = MatchWeek
    return playing_stat

In [274]:
#playing_statistics_1 = get_mw(playing_statistics_1)
#playing_statistics_2 = get_mw(playing_statistics_2)
#playing_statistics_3 = get_mw(playing_statistics_3)
#playing_statistics_4 = get_mw(playing_statistics_4)
#playing_statistics_5 = get_mw(playing_statistics_5)
#playing_statistics_6 = get_mw(playing_statistics_6)
#playing_statistics_7 = get_mw(playing_statistics_7)
playing_statistics_8 = get_mw(playing_statistics_8)
playing_statistics_9 = get_mw(playing_statistics_9)
playing_statistics_10 = get_mw(playing_statistics_10)
playing_statistics_11 = get_mw(playing_statistics_11)
playing_statistics_12 = get_mw(playing_statistics_12)
playing_statistics_13 = get_mw(playing_statistics_13)
playing_statistics_14 = get_mw(playing_statistics_14)
playing_statistics_15 = get_mw(playing_statistics_15)
playing_statistics_16 = get_mw(playing_statistics_16)
playing_statistics_17 = get_mw(playing_statistics_17)
playing_statistics_18 = get_mw(playing_statistics_18)
playing_statistics_19 = get_mw(playing_statistics_19)
#playing_statistics_20 = get_mw(playing_statistics_20)

<ipython-input-273-4940c39006da>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playing_stat['MW'] = MatchWeek

In [275]:
playing_statistics_14

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2013-08-09,Montpellier,Paris SG,1.0,1.0,D,6.0,12.0,1.0,4.0,...,M,M,M,M,M,M,M,M,M,1
1,2013-08-10,Bordeaux,Monaco,0.0,2.0,A,11.0,13.0,2.0,6.0,...,M,M,M,M,M,M,M,M,M,1
2,2013-08-10,Evian Thonon Gaillard,Sochaux,1.0,1.0,D,15.0,9.0,8.0,6.0,...,M,M,M,M,M,M,M,M,M,1
3,2013-08-10,Lille,Lorient,1.0,0.0,H,6.0,6.0,3.0,3.0,...,M,M,M,M,M,M,M,M,M,1
4,2013-08-10,Lyon,Nice,4.0,0.0,H,12.0,11.0,6.0,5.0,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2014-05-17,Paris SG,Montpellier,4.0,0.0,H,18.0,15.0,12.0,1.0,...,L,L,L,D,W,W,D,L,L,38
376,2014-05-17,Reims,Rennes,1.0,3.0,A,16.0,14.0,4.0,3.0,...,L,W,W,L,D,L,D,D,L,38
377,2014-05-17,Sochaux,Evian Thonon Gaillard,0.0,3.0,A,20.0,9.0,5.0,6.0,...,W,W,L,D,L,W,L,W,W,38
378,2014-05-17,St Etienne,Ajaccio,3.0,1.0,H,14.0,8.0,8.0,3.0,...,W,W,L,W,L,D,L,D,D,38
379,2014-05-17,Toulouse,Valenciennes,3.0,1.0,H,9.0,15.0,4.0,5.0,...,L,D,L,L,L,D,L,L,L,38

FINAL DATAFRAME

In [276]:
playing_stat = pd.concat([#playing_statistics_1,
                          #playing_statistics_2,
                          #playing_statistics_3,
                          #playing_statistics_4,
                          #playing_statistics_5,
                          #playing_statistics_6,
                          #playing_statistics_7,
                          playing_statistics_8,
                          playing_statistics_9,
                          playing_statistics_10,
                          playing_statistics_11,
                          playing_statistics_12,
                          playing_statistics_13,
                          playing_statistics_14,
                          playing_statistics_15,
                          playing_statistics_16,
                          playing_statistics_17,
                          playing_statistics_18,
                          playing_statistics_19,], ignore_index=True)

In [277]:
playing_stat

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,AM1,HM2,AM2,HM3,AM3,HM4,AM4,HM5,AM5,MW
0,2007-08-04,Bordeaux,Lens,1.0,0.0,H,13.0,4.0,4.0,2.0,...,M,M,M,M,M,M,M,M,M,1
1,2007-08-04,Caen,Nice,1.0,0.0,H,16.0,14.0,6.0,4.0,...,M,M,M,M,M,M,M,M,M,1
2,2007-08-04,Lille,Lorient,0.0,0.0,D,6.0,5.0,2.0,3.0,...,M,M,M,M,M,M,M,M,M,1
3,2007-08-04,Monaco,St Etienne,1.0,1.0,D,16.0,19.0,5.0,6.0,...,M,M,M,M,M,M,M,M,M,1
4,2007-08-04,Paris SG,Sochaux,0.0,0.0,D,11.0,8.0,10.0,5.0,...,M,M,M,M,M,M,M,M,M,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,2019-05-24,Nantes,Strasbourg,0.0,1.0,A,21.0,5.0,1.0,1.0,...,L,D,L,W,D,W,D,W,L,38
4556,2019-05-24,Nice,Monaco,2.0,0.0,H,8.0,11.0,2.0,4.0,...,W,D,L,D,L,W,D,L,L,38
4557,2019-05-24,Nimes,Lyon,2.0,3.0,A,17.0,19.0,8.0,8.0,...,W,W,W,W,D,L,W,W,W,38
4558,2019-05-24,Reims,Paris SG,3.0,1.0,H,10.0,13.0,6.0,2.0,...,W,L,W,L,D,D,L,L,W,38
4559,2019-05-24,Rennes,Lille,3.0,1.0,H,13.0,14.0,8.0,7.0,...,W,D,W,D,D,D,W,L,D,38

In [278]:
# Gets the form points.
def get_form_points(string):
    sum = 0
    for letter in string:
        sum += get_points(letter)
    return sum

playing_stat['HTFormPtsStr'] = playing_stat['HM1'] + playing_stat['HM2'] + playing_stat['HM3'] + playing_stat['HM4'] + playing_stat['HM5']
playing_stat['ATFormPtsStr'] = playing_stat['AM1'] + playing_stat['AM2'] + playing_stat['AM3'] + playing_stat['AM4'] + playing_stat['AM5']

playing_stat['HTFormPts'] = playing_stat['HTFormPtsStr'].apply(get_form_points)
playing_stat['ATFormPts'] = playing_stat['ATFormPtsStr'].apply(get_form_points)

# Identify Win/Loss Streaks if any.
def get_3game_ws(string):
    if string[-3:] == 'WWW':
        return 1
    else:
        return 0
    
def get_5game_ws(string):
    if string == 'WWWWW':
        return 1
    else:
        return 0
    
def get_3game_ls(string):
    if string[-3:] == 'LLL':
        return 1
    else:
        return 0
    
def get_5game_ls(string):
    if string == 'LLLLL':
        return 1
    else:
        return 0
    
playing_stat['HTWinStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ws)
playing_stat['HTWinStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ws)
playing_stat['HTLossStreak3'] = playing_stat['HTFormPtsStr'].apply(get_3game_ls)
playing_stat['HTLossStreak5'] = playing_stat['HTFormPtsStr'].apply(get_5game_ls)

playing_stat['ATWinStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ws)
playing_stat['ATWinStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ws)
playing_stat['ATLossStreak3'] = playing_stat['ATFormPtsStr'].apply(get_3game_ls)
playing_stat['ATLossStreak5'] = playing_stat['ATFormPtsStr'].apply(get_5game_ls)

playing_stat.keys()

Index(['Date', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HS', 'AS',
       'HST', 'AST', 'HC', 'AC', 'HF', 'AF', 'HY', 'AY', 'HR', 'AR', 'HTGS',
       'ATGS', 'HTGC', 'ATGC', 'AGHSF', 'AGASF', 'AGHSC', 'AGASC', 'AGHSTF',
       'AGASTF', 'AGHSTC', 'AGASTC', 'AGHF', 'AGAF', 'AGHCF', 'AGACF', 'AGHCC',
       'AGACC', 'AGHY', 'AGAY', 'AGHR', 'AGAR', 'HTP', 'ATP', 'HM1', 'AM1',
       'HM2', 'AM2', 'HM3', 'AM3', 'HM4', 'AM4', 'HM5', 'AM5', 'MW',
       'HTFormPtsStr', 'ATFormPtsStr', 'HTFormPts', 'ATFormPts',
       'HTWinStreak3', 'HTWinStreak5', 'HTLossStreak3', 'HTLossStreak5',
       'ATWinStreak3', 'ATWinStreak5', 'ATLossStreak3', 'ATLossStreak5'],
      dtype='object')

In [279]:
# Get Goal Difference
playing_stat['HTGD'] = playing_stat['HTGS'] - playing_stat['HTGC']
playing_stat['ATGD'] = playing_stat['ATGS'] - playing_stat['ATGC']

# Diff in points
playing_stat['DiffPts'] = playing_stat['HTP'] - playing_stat['ATP']
playing_stat['DiffFormPts'] = playing_stat['HTFormPts'] - playing_stat['ATFormPts']

# Diff in Shots fired
playing_stat['HTSD'] = playing_stat['AGHSF'] - playing_stat['AGHSC']
playing_stat['ATSD'] = playing_stat['AGASF'] - playing_stat['AGASC']

# Diff in shots on target
playing_stat['HTSTD'] = playing_stat['AGHSTF'] - playing_stat['AGHSTC']
playing_stat['ATSTD'] = playing_stat['AGASTF'] - playing_stat['AGASTC']

# Diff in corners
playing_stat['HTCD'] = playing_stat['AGHCF'] - playing_stat['AGHCC']
playing_stat['ATCD'] = playing_stat['AGACF'] - playing_stat['AGACC']

In [280]:
# Datensatz nicht gescaled
#playing_stat_raw = playing_stat
#playing_stat_raw.to_csv(loc + "2019_2020_ingame_1und2_raw.csv")

In [281]:
# Scale DiffPts , DiffFormPts, HTGD, ATGD by Matchweek.
cols = ['HTGD','ATGD','DiffPts','DiffFormPts','HTP','ATP', "HTSD", "ATSD", "HTSTD", "ATSTD", "HTCD", "ATCD",
        "AGHY", "AGHR", "AGAR", "AGHF", "AGAF", "AGAY", 'AGHSF','AGASF', 'AGHSC', 'AGASC', 'AGHSTF', 'AGASTF', 
        'AGHSTC', 'AGASTC', 'AGHCF', 'AGACF', 'AGHCC', 'AGACC']
playing_stat.MW = playing_stat.MW.astype(float)

for col in cols:
    playing_stat[col] = playing_stat[col] / playing_stat.MW

In [282]:
playing_stat.MW

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
4555    38.0
4556    38.0
4557    38.0
4558    38.0
4559    38.0
Name: MW, Length: 4560, dtype: float64

In [283]:
playing_stat

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HS,AS,HST,AST,...,HTGD,ATGD,DiffPts,DiffFormPts,HTSD,ATSD,HTSTD,ATSTD,HTCD,ATCD
0,2007-08-04,Bordeaux,Lens,1.0,0.0,H,13.0,4.0,4.0,2.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,2007-08-04,Caen,Nice,1.0,0.0,H,16.0,14.0,6.0,4.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2007-08-04,Lille,Lorient,0.0,0.0,D,6.0,5.0,2.0,3.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,2007-08-04,Monaco,St Etienne,1.0,1.0,D,16.0,19.0,5.0,6.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2007-08-04,Paris SG,Sochaux,0.0,0.0,D,11.0,8.0,10.0,5.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,2019-05-24,Nantes,Strasbourg,0.0,1.0,A,21.0,5.0,1.0,1.0,...,0.026316,0.236842,0.052632,0.236842,2.526316,-2.078947,0.473684,0.052632,0.157895,-0.789474
4556,2019-05-24,Nice,Monaco,2.0,0.0,H,8.0,11.0,2.0,4.0,...,-0.184211,-0.447368,0.447368,0.026316,-1.421053,0.947368,-0.631579,0.263158,-0.710526,0.526316
4557,2019-05-24,Nimes,Lyon,2.0,3.0,A,17.0,19.0,8.0,8.0,...,0.000000,0.578947,-0.421053,-0.078947,0.868421,5.000000,-0.052632,2.605263,0.842105,1.605263
4558,2019-05-24,Reims,Paris SG,3.0,1.0,H,10.0,13.0,6.0,2.0,...,-0.131579,1.894737,-1.026316,-0.157895,-1.052632,4.184211,-0.500000,2.552632,-1.210526,2.236842
4559,2019-05-24,Rennes,Lille,3.0,1.0,H,13.0,14.0,8.0,7.0,...,0.026316,0.973684,-0.684211,-0.131579,-0.105263,3.105263,-0.026316,1.842105,0.710526,-0.473684

In [284]:
playing_stat.to_csv(loc + "final_championnat_.csv")
# playing_stat_test.to_csv(loc+"test.csv")